app/models/namespace.rb, app/models/route.rb, app/services/groups/create_service.rb, test/fixtures/routes.yml, test/models/group_test.rb, test/models/namespaces/project_namespace_test.rb, test/models/namespaces/user_namespace_test.rb
Replace recursive traversal of ancestors with linear traversal using route paths.
Fix bug in groups create service, that was passing the group to be created to permission evaluator instead of the parent.
=> Feature: Linear ancestor traversal

Dockerfile, bin/docker-entrypoint.sh
Adds in `bin/entrypoint.sh` that accepts an env variable `RUN_PENDING_MIGRATIONS` that when set to `true`, `True`, or `1` it runs `bin/rails db:migrate` before running normal docker command.
=> Docker: Add Entrypoint

app/views/groups/index.html.erb, app/views/projects/samples/index.html.erb, config/locales/en.yml
Groups index and Project Samples index, where not migrated over to Viral::DropdownComponent. This PR fixes that.
=> Update: Migrate old dropdowns to Viral::DropdownComponent

app/controllers/groups_controller.rb, app/controllers/projects_controller.rb, app/models/member.rb, app/models/namespace.rb, app/models/user.rb, app/services/base_service.rb, test/fixtures/groups.yml, test/fixtures/members.yml, test/models/group_test.rb, test/models/namespace_test.rb, test/models/namespaces/project_namespace_test.rb, test/models/namespaces/user_namespace_test.rb, test/system/groups_test.rb, test/system/projects_test.rb
Updated Namespace instance lineage methods (e.g. `ancestors`, `descendants`, etc) to only return instances of the current class (e.g. `Group` when calling on a `Group` instance, etc).
Added in Namespace class lineage methods, so that we can get all the Namespaces of a specific type that a User has access to.
Updated Groups Index and Projects Index to only show the corresponding models that the current_user has access to through `membership`.
=> Internal: Namespace Traversal Updates

app/controllers/concerns/membership_actions.rb, app/views/projects/members/new.html.erb, config/locales/en.yml, test/system/projects/members_test.rb
Fixed bug:
- which prevented project owner under their own user_namespace from adding a project member due to a nil error.
- added test to ensure the owner could add a project member
Fixed translation key
=> Bugfix: Access_level nil error when adding a project member under user namespace

app/models/group.rb, app/models/namespace.rb, app/models/namespaces/project_namespace.rb, app/models/namespaces/user_namespace.rb, app/models/project.rb, app/models/user.rb, db/migrate/20230208193900_create_namespaces.rb, db/migrate/20230227172418_create_projects.rb, db/migrate/20230228214717_create_members.rb, db/migrate/20230316180414_create_samples.rb, db/migrate/20230327202710_create_personal_access_tokens.rb, db/schema.rb, test/controllers/groups_controller_test.rb, test/models/group_test.rb, test/models/namespaces/project_namespace_test.rb, test/models/project_test.rb, test/models/user_test.rb, test/services/groups/destroy_service_test.rb, test/system/groups_test.rb
Previously we we're adding foreign keys with `t.integer blah_id` instead of `t.references :blah`. Using the `references` syntax results in the type of `blah_id` to be `:bigint` which matches the type of the id column in the database.
Note: This change will require you to run the following command:
`bin/rails db:drop db:create db:migrate db:seed`
=> Internal: Fix Migrations

app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/_project.html.erb, app/views/projects/index.html.erb, db/seeds.rb
This PR updates the Projects index action to only load a page of projects when the user has access to Projects, and only when processing the turbo_stream request.
Prior to this PR a page of projects was loaded when processing the html request, but the index.html.erb action was not utilizing the page as we defer loading of the table via turbo_stream request.
This PR also updates the db/seeds.rb to seed a user with email `user9@email.com` who does not have access to any projects. This user can be used to test accessing the Projects Index without any projects to see that it does not attempt to load a page of projects.
=> Update: Projects Index Action

app/components/viral/alert_component.html.erb, app/components/viral/alert_component.rb, app/helpers/view_helper.rb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/layouts/devise.html.erb, test/components/previews/alert_component_preview.rb, test/components/viral/alert_component_test.rb
Created an alert component to specifically handle login notices where the flash component is not appropriate.  Has two states:
Notice:
Alert:
=> Feature: Alert component for login flash notices

app/controllers/concerns/sessionless_authentication.rb, app/controllers/graphql_controller.rb, db/seeds.rb, test/controllers/concerns/sessionless_authentication_concern_test.rb, test/controllers/graphql_controller_test.rb
This PR introduces sessionless authentication, specifically to be used by external tools accessing the Graphql API. Without this change, users could only interact with our Graphql api while the app was running in `development` mode and if they accessed it via the `graphiql` interface available at `http://localhost:3000/graphiql`.
This uses [Basic HTTP Authentication](https://datatracker.ietf.org/doc/html/rfc7617), in the form of `$USEREMAIL:$ACCESSTOKEN` that is Base64 encoded.
e.g. `admin@email.com:yK1euURqVRtQ1D-3uKsW` becomes `YWRtaW5AZW1haWwuY29tOnlLMWV1VVJxVlJ0UTFELTN1S3NX`
Which would be used like the following:
e.g. `Authorization: Basic YWRtaW5AZW1haWwuY29tOnlLMWV1VVJxVlJ0UTFELTN1S3NX`
_Screenshots are required for UI …
=> Feature: Sessionless authentication

test/components/viral/system/tooltip_component_test.rb
This PR fixes the flaky tooltip component test.
The test is flaky because sometimes the javascript is not initialized as quickly as the test would like. This uses `within('.Viral-Preview > [data-controller-connected="true"]')` to ensure that the javascript has been intialized before performing the test.
1. Execute the test with `bin/rails test test/components/viral/system/tooltip_component_test.rb`
2. See that it passes
=> Tests: fix flaky tooltip component test

Gemfile, Gemfile.lock, app/controllers/graphql_controller.rb, app/graphql/irida_schema.rb, app/graphql/mutations/base_mutation.rb, app/graphql/resolvers/base_resolver.rb, app/graphql/resolvers/groups_resolver.rb, app/graphql/resolvers/nested_groups_resolver.rb, app/graphql/schema.graphql, app/graphql/types/base_connection.rb, app/graphql/types/base_object.rb, app/graphql/types/query_type.rb, config/locales/en.yml, test/graphql/group_query_test.rb, test/graphql/groups_query_test.rb
This PR adds in [Action Policy GraphQL](https://github.com/palkan/action_policy-graphql), for using our Action Policy Authorizations in the GraphQL API.
Specifically that means that Users are only able to view and list Groups that they are authorized to do so.
In addition this added a `totalCount` field to the Relay Connections so that it is easy to determine that the correct number of Groups are queried/return.
Note: This PR adds a gem so make sure to run `bundle` before testing.
If you login as `admin@email.com` and try to query for the `borrelia` group, which you don't have access to you will get the following:
If you login as …
=> GraphQL Authorization

app/assets/stylesheets/application.tailwind.css, app/components/viral/alert_component.rb, app/controllers/concerns/membership_actions.rb, app/models/member.rb, app/services/members/update_service.rb, app/views/groups/members/_access_level.html.erb, app/views/groups/members/index.html.erb, app/views/groups/members/update.turbo_stream.erb, app/views/projects/members/_access_level.html.erb, app/views/projects/members/index.html.erb, app/views/projects/members/update.turbo_stream.erb, config/locales/en.yml, config/routes/group.rb, config/routes/project.rb, test/controllers/concerns/groups_membership_actions_concern_test.rb, test/controllers/concerns/projects_membership_actions_concern_test.rb, test/fixtures/groups.yml, test/fixtures/members.yml, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/projects.yml, test/fixtures/routes.yml, test/policies/group_policy_test.rb, test/policies/project_policy_test.rb, test/services/members/update_service_test.rb, test/system/groups/members_test.rb, test/system/projects/members_test.rb, test/system/projects_test.rb
Added in functionality to allow a member's access level to be updated from the group and project members listing page using turbo_stream. Using turbo_stream allows us to update just the access level select box for the particular member that is being updated rather than having to do a full page reload. 
A few other UI related things were added in such as an 'It's you' tag next to any member listing which matches the current user, as well as, an updated_at column to the projects and group members tables/ 
**Error when attempting to set a lower access level for user than they have in a parent group:**
**Success message when an update is …
=> Feature: Member Access Level Update

config/locales/en.yml, test/system/profile_test.rb, test/system/projects/members_test.rb, test/system/projects_test.rb
This PR cleans up our UI system tests that were previously finding an input field by it's selector and they asserting the value of the field.  This PR changes the sytax to use the [cabybara  find\_field](https://github.com/teamcapybara/capybara#finding) method.
Since this is just an update to testing syntax, there are no updates or recordigns.
 Since this is just an update to the UI system tests, run tests within `test/system` and ensure all pass
=> refactor: Updated tests to remove finding by selectors

app/graphql/irida_schema.rb, app/graphql/schema.graphql, app/graphql/types/namespace_type.rb, test/graphql/node_query_test.rb, test/graphql/nodes_query_test.rb
This PR updates the Group type to implement the Relay Node interface. This allows us to query Groups via Node or Nodes queries. This will be really useful later on when we add additional types as it will give our clients the ability to query different types of objects within a single query.
To achieve this I updated the Group type to implement the [Node interface](https://graphql-ruby.org/schema/object_identification.html#node-interface).
1. Login with 'user1@email.com` and then navigate to `http://localhost:3000/graphiql`
2. Query for a group that the user has …
=> Feature: GraphQL Relay Node Interface

Gemfile, app/javascript/controllers/selection_controller.js, test/components/previews/selection_preview.rb, test/components/previews/selection_preview/default.html.erb, test/components/previews/selection_preview/with_a_storage_key.html.erb, test/components/previews/selection_preview/within_a_table.html.erb, test/components/viral/system/selection_test.rb
The selection controller is used to store a list of checkbox values in a hash within local storage. The url being the local storage key.
Pulled from https://github.com/phac-nml/irida-next/pull/90.
1. Navigate to http://localhost:3000/rails/lookbook.
2. Click on "Selection" previews.
3. Ensure the checkbox values are stored in local storage with the key being the url.
4. Ensure the latest value is populated on page refresh.
=> Selection controller

app/assets/icons/heroicons/check_circle_solid.svg, app/assets/icons/heroicons/exclamation_circle_solid.svg, app/assets/icons/heroicons/information_circle_solid.svg, app/assets/icons/heroicons/x_circle_solid.svg, app/components/viral/flash_component.html.erb, app/components/viral/flash_component.rb, app/components/viral/flash_controller.js, config/locales/en.yml, test/components/viral/flash_component_test.rb, test/components/viral/system/flash_component_test.rb
1. Update the look of the flash component to match the[ Flowbite Toast component](https://flowbite.com/docs/components/toast/).
2. When a timeout is set on a flash message, the user can now how to keep it on the screen.
**Error**
**Info**
**Success**
**Warning**
- All flash components can be viewed in [Lookbook](http://localhost:3000/rails/lookbook/inspect/viral_flash/error_flash)
- To test the hover delayed close, run IRIDA Next (clean db seed)
* Login as user1
* Go to the settings of a project the user has permissions on (e.g. [Outbreak …
=> enhancement: Updates to flash notification

app/controllers/projects_controller.rb, app/views/projects/transfer.turbo_stream.erb, test/system/projects/transfer_test.rb
Currently when a project transfer fails, the whole page refreshes because the response was not set to be a turbo stream.  This updates the response type and fixes the path to the transfer form template.
Here you can see that the response is only a turbo stream with the updated form:
With the default database seed:
1. Login with user1
2. Go to http://localhost:3000/streptococcus/streptococcus-pyogenes/outbreak-2022/-/edit
3. Open the network tab on chrome/firefox developer tools
4. Select `Neisseria / Neisseria meningitidis` from the new namespace select
5. …
=> Fix: Use turbo stream when project transfer fails

app/components/viral/dialog_component.html.erb, test/components/viral/alert_component_test.rb, test/components/viral/avatar_component_test.rb, test/components/viral/breadcrumb_component_test.rb, test/components/viral/button_component_test.rb, test/components/viral/card_component_test.rb, test/components/viral/dialog_component_test.rb, test/components/viral/flash_component_test.rb, test/components/viral/icon_component_test.rb, test/test_helpers/markup_validation_helpers.rb, test/view_component_test_case.rb
Fixes the case of the Dialog component having a hanging closing div tag when no footer is present. This issue causes the dialog to break components that it is put into (e.g. having the dialog be contained within the card component).
This also adds in a `ViewComponentTestCase` class and `MarkupValidationHelpers` class. Whenever `render_inline` or `render_preview` is called in a class based on `ViewComponentTestCase` the resulting HTML is validated using Nokogiri. This will ensure that invalid markup is caught and reported.
This checklist encourages us to confirm …
=> Fix: Dialog Component

app/controllers/concerns/share_actions.rb, app/models/member.rb, app/policies/group_policy.rb, app/policies/namespaces/project_namespace_policy.rb, app/services/namespaces/group_share_update_service.rb, config/locales/en.yml, config/routes/group.rb, config/routes/project.rb, test/controllers/groups_controller_test.rb, test/controllers/projects_controller_test.rb, test/policies/group_policy_test.rb, test/policies/namespaces/project_namespace_policy_test.rb, test/services/namespaces/group_share_update_service_test.rb
This PR adds in functionality to update NamespaceGroupLinks (group access level and expiration date). 
The following changes were made:
Controller action added to `share_actions` concern to update namespace_group_link
Routes added for project and group for `share_update`
Service added to do the actual updating of the namespace_group_link
Policy methods added to `ProjectNamespacePolicy` and `GroupPolicy` to handle authorization
Testing added for controller, service and policies
**Note**: The commented out code in `share_actions.rb` will be used in the UI branch which is ongoing.
No screenshots as this only adds in back-end code …
=> NamespaceGroupLink updating

README.md, docs-site/docs/development/development_processes/code_review.md
Fix broken links for docs
N/A
Using vscode you can open the markdown preview and click the link to move to the linked page
=> Fix documentation links

app/controllers/projects/samples/transfers_controller.rb, app/views/projects/samples/index.html.erb, app/views/projects/samples/transfers/new.html.erb, app/views/projects/samples/transfers/new.turbo_stream.erb, test/controllers/projects/samples/transfers_controller_test.rb
Updating the sample transfer modal to use turbo_stream.
Pulled from https://github.com/phac-nml/irida-next/pull/135.
1. Navigate to a project that is owned by the logged-in user.
2. Hit `Samples` on the left side menu.
3. Check the samples you wish to transfer.
4. Click the `Transfer samples` button.
5. A dialog should appear. Verify the modal was rendered via turbo_stream.
=> Updating sample transfer modal to use turbo_stream

app/components/viral/form/datepicker_component.html.erb, app/components/viral/form/datepicker_component.rb, app/helpers/view_helper.rb, app/javascript/controllers/datepicker_controller.js, test/components/previews/viral_form_datepicker_component_preview.rb, test/components/previews/viral_form_datepicker_component_preview/default.html.erb, test/components/previews/viral_form_datepicker_component_preview/with_help_text.html.erb, test/components/previews/viral_form_datepicker_component_preview/with_label.html.erb, test/components/previews/viral_form_datepicker_component_preview/with_placeholder.html.erb, test/components/viral/form/datepicker_component_test.rb
Custom datepicker components:
- Accomodates with and without a label
- Can add any attributes to the input (e.g. data args)
Fixes #199 
**Default**
**With label**
**With help text**
**With placeholder**
Lookbook Previews:
1. [Default](http://localhost:3000/rails/lookbook/inspect/viral_form_datepicker/default)
2. [With label](http://localhost:3000/rails/lookbook/inspect/viral_form_datepicker/with_label)
3. [With help text](http://localhost:3000/rails/lookbook/inspect/viral_form_datepicker/with_help_text)
4. [With …
=> Datepicker View Component

app/components/namespace_tree/row/row_contents_component.html.erb, app/controllers/dashboard/groups_controller.rb, app/views/dashboard/groups/group.turbo_stream.erb, app/views/dashboard/groups/index.html.erb, app/views/dashboard/groups/index.turbo_stream.erb, config/locales/en.yml, test/fixtures/groups.yml, test/fixtures/members.yml, test/fixtures/routes.yml, test/fixtures/users.yml, test/system/dashboard/groups_test.rb
This PR updates the Groups Dashboard to use pagination and also adds in sorting.
1. As a User create at least 21 groups (our default pagination is set to 20)
2. Navigate to Groups Dashboard
3. Observer that pagination buttons appear
4. Test out sorting and see that table is updated
=> Dashboard Groups pagination

app/components/viral/breadcrumb_component.rb, app/controllers/application_controller.rb, app/controllers/concerns/breadcrumb_navigation.rb, app/controllers/groups/application_controller.rb, app/controllers/groups/group_links_controller.rb, app/controllers/groups/members_controller.rb, app/controllers/groups/samples_controller.rb, app/controllers/groups_controller.rb, app/controllers/projects/application_controller.rb, app/controllers/projects/group_links_controller.rb, app/controllers/projects/members_controller.rb, app/controllers/projects/samples/attachments_controller.rb, app/controllers/projects/samples/transfers_controller.rb, app/controllers/projects/samples_controller.rb, app/controllers/projects_controller.rb, app/helpers/route_helper.rb, app/views/groups/update.turbo_stream.erb, app/views/layouts/groups.html.erb, app/views/layouts/projects.html.erb, app/views/projects/update.turbo_stream.erb, test/components/previews/viral_breadcrumb_component_preview/default.html.erb, test/components/previews/viral_breadcrumb_component_preview/with_crumbs.html.erb, test/components/viral/breadcrumb_component_test.rb, test/helpers/route_helper_test.rb
This PR refactors the breadcrumbs component so that the component no longer requires a ```Route``` object passed as an argument, only the ```context_crumbs```. A ```RouteHelper``` is now available to breakdown ```Routes``` into the ```context_crumbs``` format prior to being passed as the argument when initializing a ```Breadcrumb component```. All existing breadcrumbs should still have the same functionality as prior to this PR.
1. Pull down this branch
2. Clickthrough the groups and projects pages, ensuring breadcrumb names and links are accurate.
3. Compare with breadcrumb names and links on ```main```.
This checklist encourages us to confirm any changes have been analyzed to reduce risks in …
=> Refactor breadcrumbs

app/models/attachment.rb, db/schema.rb, test/models/attachment_test.rb
This PR adds the ```type: assembly``` to an ```Attachment```'s metadata for ```fasta``` files. In addition, ```Attachments``` now has a ```fasta?``` method that will return ```true``` if the ```Attachment``` ```metadata``` ```format``` is ```fasta```.
Add attachments with a ```fasta``` format to samples, and check that the new database entries contain both ```type: assembly``` and ```format: fasta``` under metadata.
=> Add assembly type to attachment metadata for fasta files

app/models/member.rb, app/models/namespace_group_link.rb, test/models/members/group_member_test.rb, test/models/members/project_member_test.rb, test/models/namespace_group_link_test.rb, test/test_helper.rb, test/test_helpers/array_helpers.rb
This PR removes `not_expired scope` from `for_namespace_and_ancestors` scope and instead applies it to the collection of for_namespace_and_ancestors when getting the user's access level through group links. The reasoning for this is we will need the scope to be able to display the expired and non expired group links on the Members -> Groups tab
1. Login as a `user1@email.com`
2. Create 2 groups `Group A` and `Group B`
3. Create a namespace group link between 2 groups `Group A` and `Group B` where `Group B` is invited to `Group A`
4. Update the group link to a …
=> Remove not_expired scope from for_namespace_and_ancestors scope

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/profiles/preferences_controller.rb, app/views/profiles/preferences/_locale_form.html.erb, app/views/profiles/preferences/show.html.erb, config/application.rb, config/initializers/locale.rb, config/locales/devise.fr.yml, config/locales/en.yml, config/locales/fr.yml, config/routes/profile.rb, db/migrate/20231025155037_add_locale_to_user.rb, db/schema.rb, test/system/profile_test.rb
In this PR, locale selection has been implemented under the user's profile preferences settings. This will allow users to select between English and French language translations for the website.
1. Navigate to profile preferences.
2. Under language, select either English or French and submit.
- Only the language card contains translations currently. Therefore, the language card's wording should be translated based on the language selected.
=> Language Selection

app/components/updated_component.html.erb, app/components/updated_component.rb, app/components/viral/time_ago_component.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/previews/updated_component_preview.rb, test/components/previews/updated_component_preview/with_custom_description.html.erb, test/components/updated_component_test.rb
This PR updates the translation for `UpdatedComponent` to use scope for distance_in_words instead of having 2 translations joined. Fixed lookbook preview for `UpdatedComponent` and `TimeAgoComponent` so they display correctly in dark mode. Also, the custom description was removed for the `UpdatedComponent`
1) Ensure the translations display correctly in the lookbook previews
2) Ensure the translations display correctly for updated at in the members tables for groups and projects when the member is updated
This checklist encourages us to confirm any changes have …
=> UpdatedComponent: translation and lookbook preview fix

app/controllers/dashboard/projects_controller.rb, app/models/user.rb, app/policies/project_policy.rb, test/controllers/concerns/projects_membership_actions_concern_test.rb, test/fixtures/members.yml, test/fixtures/namespaces/user_namespaces.yml, test/fixtures/routes.yml, test/fixtures/users.yml, test/services/projects/destroy_service_test.rb, test/system/dashboard/projects_test.rb
This PR updates the Project Policy default scope to include Projects where a User is a Member of the Project but not the parent namespace.
1. As a User create a personal project and add another user as a member to it.
2. Login as the other user and verify that the Project appears in the project dashboard.
=> Fix: Missing Projects in Projects Dashboard where user is a member

app/views/projects/samples/_table.html.erb
Checkboxes on the project samples page are hard-coded to blue, they should be set to the primary colour.
**Before**
**After**
Go to any project that has samples and ensure the selected samples checkboxes are set to the appropriate colour.
=> style: Fix checkbox colour for project samples

app/views/profiles/preferences/_locale_form.html.erb
Removes a couple lines that were left behind when attempting to add a stimulus controller for language selection. They are now unneeded as the language selection is handled by submitting the language form onchange
Select languages to ensure it still works as expected.
=> Remove unnecessary lines from language selection

app/javascript/controllers/action_link_controller.js, app/javascript/controllers/selection_controller.js, app/views/projects/samples/_table.html.erb, app/views/projects/samples/index.html.erb
Currently, on the project samples page, the workflow execution and transfer samples links function without any samples being selected.  This PR add a check when the buttons are connected to the dom to see if there are any samples selected for that project, and when the selections are updated the buttons will update.
**No samples selected**
**Samples selected**
**EDIT**
This also works for buttons and both default and primary CSS button classes)
Go to any project samples page (that has samples).  
- If no samples are previously selected on the initial load, the …
=> Disable table action links if no samples are seleceted

app/controllers/projects/samples/attachments_controller.rb, app/services/attachments/destroy_service.rb, app/views/projects/samples/attachments/_attachment.html.erb, app/views/projects/samples/attachments/destroy.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/controllers/projects/samples/attachments_controller_test.rb, test/services/attachments/destroy_service_test.rb, test/system/projects/samples_test.rb
This PR creates the destroy service for attachments, moving the destroy functionality away from the attachments controller. In addition to the destroy service, deletion of paired sample attachments is now also fixed whereby the shared delete button on the samples attachment page for paired attachments will now delete both associated attachments. 
[Screencast from 2023-11-03 09:23:46 AM.webm](https://github.com/phac-nml/irida-next/assets/82407232/49204e67-e806-486f-921c-007aa0773132)
Upload both single and paired attachments to a sample and delete, ensuring delete functionality is handled as expected.
=> Attachment destroy service

app/services/projects/transfer_service.rb, test/jobs/update_memberships_job_test.rb, test/policies/group_policy_test.rb, test/services/groups/transfer_service_test.rb, test/services/projects/transfer_service_test.rb, test/services/samples/update_service_test.rb
Fixes the memberships after a project transfer, so that the access level is ascending through its descendants.
Fixes part of #226.
1. Create a new group called `Group A`.
2. Add user `user1@email.com` with `Maintainer` access to `Group A`.
3. Create a new group called `Group B`.
4. Create a new project within `Group B` called `Project B`.
5. Add user `user1@email.com` with `Guest` access to `Project B`.
6. Transfer `Project B` to parent group `Group A`.
7. Verify that `user1@email.com` has changed to `Maintainer` in `Project B`.
=> Fix for memberships on project transfer

app/components/layout_component.html.erb
Found an issue where the border on the bottom of the top navigation disappears during vertical scrolling.  Moved the border from the bottom to the navigation onto the top of the main section (which always borders the top).
Border disappearing on scroll:
After fix:
=> Fix issue with the bottom border of the top navigation

db/migrate/20231121200855_add_metadata_summary_to_namespaces.rb, db/schema.rb, test/fixtures/groups.yml, test/fixtures/namespaces/project_namespaces.yml, test/models/group_test.rb, test/models/namespaces/project_namespace_test.rb
This PR adds in the db representation for `metadata_summary` in the `namespaces` table. A `jsonb` column was added with the default value of `{}`. 
**Note** validation will be added later most likely in the update logic to ensure that a user namespace does not get assigned a summary of the metadata
Fixes #267 
Fixes #268 
1. Using the rails console create a new project and verify that the metadata_summary field contains an empty hash
2. Merge in `{"field1": 10, "field2": 15} to the project metadata summary from the above step
3. Verify that the project metadata …
=> Project Sample Metadata: Metadata summary db representation

app/controllers/projects/samples_controller.rb, app/services/samples/metadata/update_service.rb, config/locales/en.yml, config/locales/fr.yml, test/services/samples/metadata/update_service_test.rb
This PR creates the new project sample metadata update service. 
1. Open the rails console with `rails c`
2. Either create or assign a Sample (preferably that contains an empty metadata field) and assign it to variable `sample`.
3. Assign the sample's associated project to `project`.
4. Assign a user that is authorized to update the sample to `user`
**Keep the console values for each testing phase**
5. Test adding a new metadata hash to the sample and metadata_provenance with user:
a) Assign a new variable `params_1` with a new hash `metadata` (such as `params_1 = {'metadata' => {'key1': 'value1', 'key2': 'value2'}}`)
b) Execute the update service with …
=> Metadata update service

app/models/workflow_execution.rb, app/services/workflow_executions/submission_service.rb, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/services/workflow_executions/submission_service_test.rb
This PR adds in the WorkflowExecutions::PreparationService as described in https://github.com/phac-nml/irida-next/issues/247
This first checks that the `WorkflowExecution` is in the `prepared` state, if not it returns false.
If `prepared` it continues on and submits to WES run_workflow endpoint, and stores the `run_id` and updates the state `submitted`.
=> Workflow Executions: Submission Service

app/services/attachments/concatenation_service.rb, app/views/projects/samples/attachments/concatenations/_modal.html.erb, config/locales/en.yml, db/schema.rb, test/application_system_test_case.rb, test/services/attachments/concatenation_service_test.rb, test/system/projects/samples_test.rb, test/test_helpers/html5_helpers.rb
This PR fixes a bug that would set a concatenated file to format: `unknown` if the file basename had a space in it. User is now prompted with a validation error client side, as well as through the back-end advising them of which format the basename must follow. Currently set to allow letters, numbers, underscores, hypens, and periods.
1. Login as a user
2. Add a new project
3. Add a sample
4. Upload single end and paired-end files
5.  Concatenate files of the same type and add spaces to the basename
6. Verify that you get a browser validation error when clicking …
=> Concatenation file format fix

app/controllers/projects/samples/metadata_controller.rb, app/views/projects/samples/edit.html.erb, config/locales/en.yml, config/locales/fr.yml, config/routes/project.rb, test/controllers/projects/samples/metadata_controller_test.rb
This PR starts the `samples_metadata` controller. The controller currently only has the `update` action, and this action utilizes the `Samples::Metadata::UpdateService` to create, update, and delete sample metadata fields. There is currently no front-end/ui to interact with the controller on the website.
Notes: 
Because there's no `update` template, I'm unable to implement status' and their respective tests. These will be updated once the UI is tied in. 
This includes:
- `:ok` status if there are no errors and `metadata_fields[:updated].count.positive?`
- `:multi_status` status if there are both errors and `metadata_fields[:updated].count.positive?`. This captures the likely scenario that a user tried to update metafields including those they are unable to.
- `:unprocessable_entity` …
=> Sample metadata controller

app/jobs/workflow_execution_status_job.rb, app/jobs/workflow_execution_submission_job.rb, app/models/workflow_execution.rb, app/services/workflow_executions/status_service.rb, app/services/workflow_executions/submission_service.rb, lib/integrations/ga4gh_wes_api/v1/states.rb, test/services/workflow_executions/create_service_test.rb, test/services/workflow_executions/status_service_test.rb
This PR adds in the `status` service which checks the status of a workflow execution every 30 seconds and when in a final state updates the workflow state to this final state. This service is called via a status job which the submission job queues up once a run_id is returned from the submission service
1) Ensure that the tests pass locally
=> Workflow Executions: Status Service

app/controllers/groups/members_controller.rb, app/controllers/projects/members_controller.rb, app/models/member.rb, app/policies/group_policy.rb, app/policies/namespace_policy.rb, app/policies/project_policy.rb, app/services/groups/transfer_service.rb, db/migrate/20231030151719_add_expires_at_to_members.rb, db/schema.rb, test/controllers/groups_controller_test.rb, test/controllers/projects_controller_test.rb, test/models/members/group_member_test.rb, test/models/members/project_member_test.rb, test/policies/group_policy_test.rb, test/policies/namespace_policy_test.rb, test/policies/project_policy_test.rb
Fixes #230.
- Added a new `expires_at` column in the members table.
- Created a new scope `not_expired` for members.
- Updated policies to only retrieve non-expired members.
N/A
There are a couple ways to test:
1. Call the new scope via console
`Member.for_namespace_and_ancestors(@group).not_expired` or `Member.for_namespace_and_ancestors(@project.namespace).not_expired` and verify the members.
2. Even though this is not the fronted PR, you can log in as the user with an expired membership to make sure groups and projects are not displayed. Some areas to check are:
- the groups/projects dashboards
- transferring groups/projects drop-down list
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and …
=> Member expiration backend

Gemfile, Gemfile.lock, config/initializers/faraday.rb, lib/integrations/ga4gh_wes_api/v1/api_connection.rb
Fixes #326 
Add gem `faraday-net_http_persistent`
Remove gem `faraday-net_http` as it is now a dependency with version number specified by `faraday-net_http_persistent`
Setup basic persistence with default values provided by gem README
* `pool_size: 5`
* `http.idle_timeout = 100`
1. run `bundle` in some way to get the new gems
e.g. `./scripts/clean_dev.sh`
2. Ensure you have ga4gh_wes credentials in your credentials file
`EDITOR="vim --nofork " bin/rails credentials:edit`
3. run a rake task from `:ga4gh_wes`
`rake debug ga4gh_wes:service_info`
This checklist …
=> Re-use faraday net_http connections

app/components/nextflow_component.html.erb, app/controllers/workflow_executions/submissions_controller.rb, app/services/workflow_executions/preparation_service.rb
Remove `--validate-params` which is no longer required in nextflow 23.10.0
Remove `workflow_engine_params -> engine` as `workflow_engine` is now being used
Update `workflow_type`, `workflow_type_version`, and `workflow_engine_version` to match our WES implementation
=> Workflow Executions: Update WES Params

app/controllers/concerns/sessionless_authentication.rb, app/controllers/graphql_controller.rb, app/graphql/types/group_type.rb, app/graphql/types/mutation_type.rb, app/graphql/types/namespace_type.rb, app/graphql/types/project_type.rb, app/graphql/types/sample_type.rb, app/policies/application_policy.rb, app/policies/graphql_policy.rb, test/fixtures/personal_access_tokens.yml, test/models/user_test.rb, test/policies/graphql_policy_test.rb
This updates the ApplicationPolicy to have an optional `token` in the context, this can be used to determine if access is via the API and then the `scopes` of the `token` can be checked to ensure the attempted operation is allowed with that token.
Note: I did not update all the policy methods to check token and scope before proceeding with verifying rest of access, this will still need to be done. This might be solved by calling `query?` and `mutate?` methods from the new `GraphqlPolicy`. …
=> GraphQL: Add token to context for Policy checking

app/controllers/projects/samples/attachments/deletions_controller.rb, app/controllers/projects/samples/attachments_controller.rb, app/policies/sample_policy.rb, app/services/attachments/destroy_service.rb, app/views/projects/samples/_table.html.erb, app/views/projects/samples/attachments/_attachment.html.erb, app/views/projects/samples/attachments/_table.html.erb, app/views/projects/samples/show.html.erb, config/locales/en.yml, config/locales/fr.yml, test/controllers/projects/samples/attachments/deletions_controller_test.rb, test/policies/sample_policy_test.rb, test/services/attachments/destroy_service_test.rb, test/system/projects/samples_test.rb
This PR prevents non-owners of samples to delete attachments by hiding the `Delete` button in the row under the `Action` header, as well as the `Delete Files` button alongside the `Upload/Concatenate Files` buttons, which is used to delete multiple attachments.
The buttons are hidden under the `sample destroy_attachment?` policy. The `Attachments::DestroyService` and `attachments deletions_controller` have been updated with the same policy.
Non-Owner:
Owner:
Login as both an owner and non-owner of a sample with attachments, navigate to the attachments page and you can either see or not see the Delete buttons based on the access level.
=> Attachments listing update

app/controllers/projects/samples/metadata_controller.rb, app/models/namespace.rb, app/models/namespaces/project_namespace.rb, app/services/samples/metadata/update_service.rb, test/fixtures/groups.yml, test/fixtures/members.yml, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/projects.yml, test/fixtures/routes.yml, test/fixtures/samples.yml, test/policies/group_policy_test.rb, test/policies/namespace_policy_test.rb, test/policies/project_policy_test.rb, test/services/samples/metadata/update_service_test.rb, test/system/dashboard/projects_test.rb
As part of [issue 334](https://github.com/phac-nml/irida-next/issues/334), this PR implements `group` and `project` `metadata_summary` updating when metadata for a sample is changed via the `Samples::Metadata::UpdateServce`. 
When `sample_metadata` is updated by the `UpdateService`, the `project.namespace` and any `group` parents will have a count updated to track how many samples contain each metadata_field in their respective `update_summary`.
Note: updating `metadata_summary` by `project/group/sample` `transfer` will be implemented in a separate PR.
Note: Although not too clear in this PR, `subtract_from_metadata_summary` and `add_to_metadata_summary` were refactored to include the `update_by_one` argument in order for these functions to be usable by all `metadata_summary` updating …
=> Metadata Summary Update by Metadata::UpdateService

test/components/viral/system/time_ago_component_test.rb
This PR fixes the `viral_time_ago` tests where they would fail if the snapshot in time at the beginning of the test and by the time the system hovered and `assert_text` the hover time text was off (presumably the test started at ~59s, and the hover occurred in the new minute).
Adding `freeze_time` should remove this variability and eliminate the 'unlucky' failures.
=> Add freeze_time to time_ago tests

app/services/samples/metadata/update_service.rb, test/fixtures/samples.yml, test/services/samples/metadata/update_service_test.rb
This PR updates the `Sample::Metadata::UpdateService` to include an `updated_at` field in `sample.metadata_provenance` with a timestamp when that metadata field was updated.
Repeat the steps from [PR 311](https://github.com/phac-nml/irida-next/pull/311), and ensure when adding metadata, `sample.metadata_provenance['updated_at'] = Time.current` 
=> Add updated_at field to metadata_provenance

app/graphql/resolvers/sample_metadata_resolver.rb, app/graphql/schema.graphql, app/graphql/types/sample_type.rb, test/graphql/samples_query_test.rb
This PR updates SampleType in the GraphQL API to include a Metadata field, to access the metadata associated with a Sample.
To test out this GraphQL query you need to first add metadata to a Sample, since there is no method to do this through the UI currently you will have to use the rails console directly.
Setting up required data:
1. Create a new Project under a Users namespace (e.g. user1@email.com), called `metadata-test`.
2. Create a new Sample in the newly created Project called `sample1`.
3. Launch the rails console and assign the following variables …
=> GraphQL: Sample Metadata Field Query

app/controllers/projects/samples/transfers_controller.rb, app/models/namespace.rb, app/models/namespaces/project_namespace.rb, app/services/groups/destroy_service.rb, app/services/groups/transfer_service.rb, app/services/projects/destroy_service.rb, app/services/projects/transfer_service.rb, app/services/samples/destroy_service.rb, app/services/samples/transfer_service.rb, test/services/groups/destroy_service_test.rb, test/services/groups/transfer_service_test.rb, test/services/projects/destroy_service_test.rb, test/services/projects/transfer_service_test.rb, test/services/samples/destroy_service_test.rb, test/services/samples/metadata/update_service_test.rb, test/services/samples/transfer_service_test.rb
Note: Dependent and branched off of [PR 339](https://github.com/phac-nml/irida-next/pull/339)
This PR is the secondary part of the `metadata_summary` update and includes updating based on group/project/sample `transfers` and `deletion`.
When transferred or deleted, all namespaces  will be updated accordingly.
In the Rails console, set up your metadata as described in [PR 339](https://github.com/phac-nml/irida-next/pull/339)
Using the website UI, transfer groups, projects, and samples and subsequently check in the console that both old and new parents/ancestors are updated accordingly. Ie: if a sample with `metadata = {'metadatafield1' => 'value1'}` is transferred, ensure its old parents have …
=> Metadata Summary Update by Transfers and Deletions

app/controllers/projects/samples_controller.rb, app/views/projects/samples/show.html.erb, test/system/projects/samples_test.rb
This PR fixes a bug on the samples table UI which would cause the page to just display a loading skeleton after a sample from deleted using the `actions` dropdown for a sample in the table.
1. Login as any user
2. Create a project and a few samples
3. Delete a sample from the table using the sample's action dropdown in the table
4. The sample should get removed (verify in the UI and the server log), and a flash message should display advising you that the sample was deleted
5. Now go to the show page of another sample in the project
6. Click the `Remove` button …
=> Sample delete fix

app/controllers/groups/samples_controller.rb, app/models/concerns/routable.rb, app/views/groups/_edit_advanced_delete.html.erb, app/views/groups/_edit_advanced_path.html.erb, app/views/groups/_edit_name_and_description_form.html.erb, app/views/projects/_destroy.html.erb, config/locales/en.yml
Remove logic in routable.rb `full_path` that was present to handle updates to Groups and Projects to `path` that resulted in validation errors, and reload `route` to get correct path. Using route helpers without params in forms will use the correct url and no need to reload the route. In addition all updates to path and name are done via turbo streams so we only reload project/group name on page when a valid update has happened.
* Verify that Project/Group updates to taken paths, don't change the url in the forms
This checklist encourages us to confirm any …
=> Group Samples Table Performance Speedups

db/migrate/20240122144035_add_puid_to_sample.rb, db/migrate/20240124170054_add_puid_to_project.rb, db/schema.rb
This updates the PUID migrations to use `with_deleted` scope to include deleted records.
1. Checkout an earlier version of the software without PUID `git checkout fea35326463202258a1177e259d0c8e978ae0405`
2. Reset the database so no trace of `puid` `./scripts/clean_dev.sh`
3. Launch the server and delete a Sample and a Project
4. Checkout this branch and run `./bin/rails db:migrate`
=> Fix Persistent Unique Identifier Migrations to include deleted records

app/controllers/sessions_controller.rb, app/views/devise/shared/_form.html.erb, test/system/sessions_test.rb
Removed the redirect when attempting to login with local account when an omniauth provider is enabled. Login errors are now displayed above the local account sign in form. 
Fixes #399.
1. Run `OMNIAUTH_PROVIDERS=developer bin/dev` in a terminal.
2. Click `Sign in with Local Account`
3. Attempt to login with invalid credentials.
4. Verify the form errors appear above the local account sign in form.
=> Fixing displaying local account sign in errors

app/components/ransack/sort_component.rb, app/controllers/concerns/metadata.rb, app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, app/models/sample.rb, app/views/groups/samples/_table.html.erb, app/views/projects/samples/_table.html.erb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR adds support to sort by a metadata column on the Group and Project Samples tables.
Resolves #277 
1. Login as `admin@email.com`
2. Navigate to Group `Bacillus` Samples table
3. Toggle metadata and click on any metadata field to sort on it
4. Verify that the table is now sorted by metadata field
5. Toggle metadata
6. Verify that sort reverted to `Last Updated` column
7. Repeats step 3 - 6 on Project `Bacillus / Bacillus Anthracis / Outbreak 2023` Samples table
This checklist encourages us to confirm any changes have been analyzed to reduce risks in …
=> Samples table metadata sorting

app/helpers/nextflow_helper.rb
The `nextflow_helper` was trying to pass 2 parameters (`hidden` and `help_text`) that were not part of the `viral_select` component argument list.  This was causing the form to crash.
Copy `https://github.com/phac-nml/iridanextexample/blob/main/nextflow_schema.json` into `test/fixtures/files/nextflow/nextflow_schema.json` and try to submit a pipeline.  The newer schema has an "assembler" field which uses the select input and was causing the crash before this fix. …
=> Workflow: Fix select component

app/controllers/groups/history_controller.rb, app/models/concerns/history.rb, app/models/group.rb, app/models/namespace.rb, app/policies/group_policy.rb, app/views/groups/history/_group_history_modal.html.erb, app/views/groups/history/_group_history_modal_description.html.erb, app/views/groups/history/index.html.erb, app/views/groups/history/index.turbo_stream.erb, app/views/groups/history/new.turbo_stream.erb, app/views/layouts/groups.html.erb, config/locales/en.yml, config/routes/group.rb, test/controllers/concerns/history_actions_concern_test.rb, test/controllers/groups/history_controller_test.rb, test/models/concerns/history_concern_test.rb, test/system/groups/history_test.rb
This PR adds in a History page for groups which displays the record level changes made to the group (name, description, parent id, type). The versions are displayed in a timeline view and clicking on the version number displays a modal with which attributes were changed and by whom.
1. Reset db (drop, create, migrate, seed) 
2. Login as a user
3. Create a group
4. Go to the `History` page for the group 
5. You should see 1 version, and clicking the `Version 1` should launch a modal that displays the attributes which the group was created with
6. Go to the group …
=> Group history view

test/system/groups/samples_test.rb
The group samples test 'can sort the list of samples' would sometimes error. This is because the PUIDs generated for testing are not always the same, and therefore, the samples ordering when sorting by PUID would sometimes change.
Rather than expecting specific samples in a certain order, we now gather the first four PUIDs of the table listing, and compare them against one another to ensure they are listed properly.
1. Ensure tests pass locally
=> Fix for group samples test can sort the list of samples

.rubocop.yml, config/environments/production.rb, config/storage.yml, lib/azure/storage/blob/default.rb, lib/azure/storage/common/default.rb, test/test_helper.rb
This PR overrides `Azure::Storage::Common::Default` and `Azure::Storage::Blob::Default` to change api version from `2018-11-09` to `2019-12-12` which allows us to direct upload files > 256 MiB and <= 5,000 MiB (https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=microsoft-entra-id#remarks).
`lib/azure/storage/blob/default.rb` was based on https://github.com/honeyankit/azure-storage-ruby/blob/master/blob/lib/azure/storage/blob/default.rb
`lib/azure/storage/common/default.rb` was based on https://github.com/honeyankit/azure-storage-ruby/blob/master/common/lib/azure/storage/common/default.rb
_Numbered steps to set up …
=> Azure storage api version fix

app/components/nextflow/samplesheet_component.html.erb, app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb, test/system/workflow_executions/submissions_test.rb
1. Fixed issue where the incorrect javascript controller name (small typo in `_pipeline_selection_dialog.html.erb`) was preventing the samplesheet component from rendering within the nextflow component.
2. Added testing as there were none to test for this.
None required: No new components added
- Select multiple samples from a project samples page (e.g. `http://localhost:3000/yersinia/yersinia-pseudotuberculosis/outbreak-2023/-/samples`)
- Click the workflow submission launch button and select a workflow
- Ensure that there are no errors in the console, and that …
=> Fix: Sample sheet rendering to nextflow submission form

app/components/viral/breadcrumb_component.html.erb, test/components/viral/breadcrumb_component_test.rb
Updates BreadcrumbComponent to use `URI::join(root_url, path).to_s` instead of `[root_url, path].join("")` to prevent having double slashes in resulting URL which broke selection controller.
Before:
After:
1. Start server
2. Navigate to a `Group` and then click on `Samples`, verify that the breadcrumb titled `Samples` does not contain a double slash
3. Repeat test on `Project`
=> Fix: Breadcrumb Component Double Slashes

app/javascript/controllers/projects/samples/attachments/files_controller.js, app/models/attachment.rb, app/services/attachments/create_service.rb, app/views/projects/samples/attachments/_attachment.html.erb, app/views/projects/samples/attachments/_table.html.erb, app/views/projects/samples/attachments/concatenations/_modal.html.erb, app/views/projects/samples/attachments/deletions/_modal.html.erb, config/locales/en.yml, db/migrate/20240311145704_add_puid_to_attachment.rb, db/schema.rb, test/fixtures/attachments.yml, test/models/attachment_test.rb, test/system/groups_test.rb, test/test_helpers/axe_helpers.rb, test/test_helpers/cuprite_setup.rb
This updates the Attachment model to include PUIDs, for `illumina_pe` and `pe` the forward and reverse individual attachments will have the same PUID.
First ensure that migrations succeed with existing database that has both `pe` and `illumina_pe` files.
Next ensure that uploading PE files have the same PUID and still works as expected.
=> Attachments: PUID

app/controllers/workflow_executions_controller.rb, app/models/workflow_execution.rb, app/services/workflow_executions/destroy_service.rb, app/views/workflow_executions/_table.html.erb, app/views/workflow_executions/_workflow_execution.html.erb, app/views/workflow_executions/destroy.turbo_stream.erb, app/views/workflow_executions/index.html.erb, config/locales/en.yml, config/routes/workflow_executions.rb, test/controllers/workflow_executions_controller_test.rb, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/services/workflow_executions/cancelation_service_test.rb, test/services/workflow_executions/destroy_service_test.rb, test/system/workflow_executions_test.rb
A user can delete a WorkflowExecution after it has been completed, errored, or canceled.
Fixes #249.
1. Login to irida-next.
2. Create a new workflow execution.
3. Open a rails console and run the following:
```
w = WorkflowExecution.last
w.state = "completed"
w.save
```
5. Refresh the workflow execution page.
6. Click the `Delete` link.
7. Confirm the deletion.
8. Verify the workflow execution has been deleted.
Repeat with `w.state = "error"` and `w.state = "canceled"`.
=> Workflow destroy service

app/graphql/resolvers/project_resolver.rb, app/graphql/resolvers/sample_resolver.rb, app/graphql/schema.graphql, app/graphql/types/attachment_type.rb, app/graphql/types/project_type.rb, app/graphql/types/query_type.rb, app/graphql/types/sample_type.rb, test/graphql/project_query_test.rb, test/graphql/sample_query_test.rb
This PR adds a `puid` field to `Attachment`, `Sample` and `Project` types. It also updates `Project` query to accept either a `puid` or a `full_path` to find a `Project`. In addition a new `Sample` query has been added which allows a `Sample` to be found by its `puid`.
1. clean dev and run
2. sign in as admin
3. on localhost:3000/graphiql query a known sample by `puid` (Can view the samples table to identify a puid)
```
sample(puid: "PUID_HERE") {
id,
puid,
name
}
```
4. query a known project by `puid` (Can view a projects puid on the projects page)
``` …
```
=> GraphQL: Add querying by PUID to Sample and Project

app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb, config/initializers/pipelines.rb, lib/irida/pipelines.rb, test/lib/irida/pipelines_test.rb, test/system/workflow_executions/submissions_test.rb
This PR fixes the workflow executions submissions test that had assertions commented out in a previous PR due to failures. The issue was arising due to parallelization when running the test suite. Depending on how many capybara processes `n` were started `(n*3)` pipelines were being registered. This has now been fixed by only registering pipelines if they have not already been registered for the process, and the available_pipelines are now returned as a hash with each key being a combination of the name and version (for example `phac/iridanextexample_1.0.2`) which will prevent duplicate entries
_Numbered steps to set up and validate …
=> Fix submissions test

test/components/previews/nextflow_component_preview.rb, test/components/previews/nextflow_component_preview/default.html.erb, test/components/previews/nextflow_samplesheet_component_preview.rb
Currently the previews are broken for the nextflow component and the nextflow samplesheet component.  This was caused by removing hard-coded workflows.
N/A
Ensure previews are working:
1. [Nextflow Component](http://localhost:3000/rails/lookbook/inspect/nextflow/default)
2. [Nextflow Samplesheet Component](http://localhost:3000/rails/lookbook/inspect/nextflow_samplesheet/default)
=> Fix: nextflow component and nextflow samplesheet component preview

app/components/namespace_tree/row/row_contents_component.html.erb, app/components/viral/pill_component.rb, app/controllers/application_controller.rb, app/controllers/dashboard/groups_controller.rb, app/models/current.rb, app/models/member.rb, app/policies/group_policy.rb, app/views/dashboard/groups/group.turbo_stream.erb, app/views/shared/project/_row.html.erb, test/components/namespace_tree_component_test.rb, test/components/previews/viral_pill_component_preview.rb, test/components/previews/viral_pill_component_preview/with_border.html.erb, test/components/viral/pill_component_test.rb
This PR updates both the Groups Dashboard and Projects Dashboard to have a badge indicating the currently logged in Users access level for said Group or Project.
1. Verify that access role is displayed on Groups and Projects dashboard and that when you navigate to the members page for the Group or Project that it shows the same access level
=> Dashboard: Effective access role display

app/graphql/mutations/attach_files_to_sample.rb, app/graphql/mutations/create_sample.rb, app/graphql/mutations/update_sample_metadata.rb, app/graphql/schema.graphql, test/graphql/attach_files_to_sample_test.rb, test/graphql/create_sample_mutation_test.rb, test/graphql/update_sample_metadata_test.rb
Updates mutations which accepted global ids for Sample and Project, to also accept Puids for Sample and Project.
1. Login as admin@email.com
2. Open the graphiql interface http://localhost:3000/graphiql
3. Query for a Project that you can access.
```graphql
{
project(fullPath: "bacillus/bacillus-anthracis/outbreak-2022") {
id
puid
name
path
}
}
```
4. See that you get a valid result
5. Execute a mutation to create a Sample.
```graphql
{
createSample(input: { projectPuid: PUID_VALUE_FROM_ABOVE, name: "Sample Name", description: "Sample Description" }) {
errors …
```
=> GraphQL: Puid enabled mutations

app/models/concerns/has_puid.rb, app/services/attachments/create_service.rb, db/migrate/20240328145629_fix_pe_attachments_puid.rb, db/schema.rb
Prior to this fix, forward and reverse attachments did not have matching PUIDs as the code to ensure that the PUIDs match happened before the PUIDs were even set. This PR corrects that behavior and has a migration to correct existing reverse attachments with PUIDs that don't match forward.
1. Run migration
2. Use rails console to validate that PUIDs for reverse and forward attachments match
=> FIX: Update Reverse PE Attachments PUID to match Forward PE Attachments PUID

app/jobs/workflow_execution_completion_job.rb, app/jobs/workflow_execution_status_job.rb, app/models/workflow_execution.rb, app/services/workflow_executions/completion_service.rb, app/services/workflow_executions/status_service.rb, db/seeds.rb, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/services/workflow_executions/completion_service_test.rb, test/services/workflow_executions/create_service_test.rb, test/services/workflow_executions/status_service_test.rb
Fixes #437
* The WorkflowExecution `completed`  state has been renamed `completing`, which indicates the workflow execution has finished, but files have yet to be put onto WorkflowExecution/SamplesWorkflowExecutions objects
* The WorkflowExecution `finalized` state has been renamed `completed`, which indicates all jobs have finished
* Added WorkflowExecutionCompletionJob, which is queued by WorkflowExecutions::StatusService and related job
* reworked `workflow_executions/create_service_test`'s happy path test to stop at `completing`, and added a new test to validate the final `completing` to `completed` job steps.
* This is mainly to break the test into more logical parts as the final step needs active storage blobs to be setup. …
=> Workflow executions/completion job

app/graphql/mutations/create_sample.rb, app/graphql/resolvers/group_resolver.rb, app/graphql/resolvers/namespace_resolver.rb, app/graphql/resolvers/project_resolver.rb, app/graphql/schema.graphql, app/graphql/types/namespace_type.rb, app/models/concerns/history.rb, app/models/group.rb, app/models/namespace.rb, app/models/namespaces/project_namespace.rb, app/models/namespaces/user_namespace.rb, app/models/project.rb, app/views/groups/show.html.erb, db/migrate/20240325190420_add_puid_to_namespace.rb, db/schema.rb, test/fixtures/groups.yml, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/namespaces/user_namespaces.yml, test/fixtures/projects.yml, test/graphql/group_query_test.rb, test/models/group_test.rb, test/models/namespace_test.rb, test/models/namespaces/project_namespace_test.rb, test/models/project_test.rb
This PR adds in persistent unique identifiers `puid` to the `Namespace` model and removes the `puid` from the `Project` model
**Group PUID**
1. Run the migrations and in the `rails console` verify that all the `Namespace` records have a `puid` attribute with `Namespace.where(puid: nil)`
2. Verify that the `Project` records no longer have a `puid` attribute
3. Sign in as `admin@email.com`
4. Verify that the `puid` displays on the show page for a project
5. Verify that the `puid` displays on the show page for a group
6. Create a new Group
7. In rails console …
=> Namespace PUID

app/controllers/users/omniauth_callbacks_controller.rb
When a user logs in, it should show the custom authentication label instead of the underlying omni auth type.
Edit your `config/authentication/auth-config.yml` to have custom values.
example:
```yml
development:
omniauth_providers: [developer]
developer_text: 'my custom authenticator'
```
See here for detailed instructions: https://github.com/phac-nml/irida-next/pull/420
Sign in and verify that the popup shows your custom text.
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, …
=> add custom text to signin success/failure popup

app/javascript/controllers/nextflow/samplesheet_controller.js
This PR fixes an issue where when a fastq pair is required for workflow submission the second file was not being selected.
N/A
- Login was user5
- Go to http://localhost:3000/yersinia/yersinia-pseudotuberculosis/outbreak-2023/-/samples
- I uploaded a couple pairs of fastq files to the first sample
- Select the first sample or two
- Open the submission window and select the first pipeline
- In the samples table, both fastq files should be selected
- In the fastq_1 column for the first sample, select the one you upload and it's pair should be selected in the …
=> FIX: Fixed auto selection of fastq_2

app/controllers/concerns/bot_actions.rb, app/controllers/profiles/personal_access_tokens_controller.rb, app/policies/namespaces/project_namespace_policy.rb, app/policies/user_policy.rb, app/services/personal_access_tokens/create_service.rb, config/locales/en.yml, config/routes/project.rb, test/controllers/concerns/bot_actions_concern_test.rb, test/controllers/projects/bots_controller_test.rb, test/services/personal_access_tokens/create_service_test.rb
This PR adds in an endpoint to allow us to generate new personal access tokens for bot accounts. A new personal access tokens create service was also added which is used to generate personal access tokens for profiles and bot accounts.
=> Bot generate personal access token

app/javascript/controllers/selection_controller.js, app/views/projects/samples/_table.html.erb
- Fixes an issue where when an analyst goes to a project sample page the selection controller throws an error because it cannot find the select all checkbox (it's not there because they don't have the authority to do anything).
- Fixes issue where the table footer displayed the wrong information since the selection controller was not functioning.  Fixed by removing the table footer on tables without the ability to select
Console error:
Wrong table footer data:
1. Selection should still work normally on projects that the user is an owner of
2. Go to a project …
=> Fix: Select all JavaScript error when not available 

app/controllers/workflow_executions_controller.rb, app/jobs/workflow_execution_status_job.rb, app/models/workflow_execution.rb, app/services/workflow_executions/cancel_service.rb, app/views/workflow_executions/cancel.turbo_stream.erb, config/locales/en.yml, test/controllers/workflow_executions_controller_test.rb, test/system/workflow_executions_test.rb
Fixes #510 
Fixes error that happened when attempting to cancel a job that hadn't reached the submitted state
Adds `submitted` to the list of states that are cancelable
Also fixes bug where workflow execution will ignore `canceling` state when queuing completion/status job, causing a run to move to `completion` state when run has been queue'd to be canceled.
1. Submit a new workflow execution
2. While in the `new` or `prepared` state, cancel it. It should go directly to the `canceled` state
3. Submit a new workflow execution
4. Wait until it reaches the …
=> Fix cancel unsubmitted job error

app/components/nextflow_component.html.erb, app/controllers/workflow_executions_controller.rb, config/locales/en.yml, test/controllers/workflow_executions_controller_test.rb, test/system/workflow_executions/submissions_test.rb
Added a checkbox to allow the user to opt in for an email notification when a workflow submission is completed.
1. Ensure `sapporo` and `mailhog` are running
2. Login as users and go to [Yersinia > Yersinia pseudotuberculosis > Outbreak 2023 > Samples]( http://localhost:3000/yersinia/yersinia-pseudotuberculosis/outbreak-2023/-/samples) 
3. Select a couple sample and click the launch workflow button
4. Select workflow **phac-nml/iridanextexample v1.0.2**
5. Leave the default options selected and select the checkbox at the bottom `Receive an email notification …
=> Workflow Submissions: Added email notification for worklfow completion

config/pipelines/pipelines.json, lib/irida/pipeline.rb, lib/irida/pipelines.rb, test/config/pipelines/pipelines.json, test/lib/irida/pipelines_test.rb
This PR adds the `automatable` attribute to pipelines and a `automatable_pipelines` call to return any automatable pipelines
1. Open a `rails console`
2. Input the command
```
Irida::Pipelines.automatable_pipelines
```
3. Ensure only pipeline `phac-nml/iridanextexample_1.0.2` is returned
=> Pipelines - Add automatable

app/models/workflow_execution.rb, app/services/workflow_executions/cancel_service.rb, app/services/workflow_executions/cancelation_service.rb, app/services/workflow_executions/completion_service.rb, app/services/workflow_executions/create_service.rb, app/services/workflow_executions/preparation_service.rb, app/services/workflow_executions/status_service.rb, app/services/workflow_executions/submission_service.rb, app/views/workflow_executions/_workflow_execution.html.erb, app/views/workflow_executions/show.html.erb, config/locales/en.yml, config/locales/fr.yml, db/migrate/20240423155817_change_workflow_execution_state_to_enum.rb, db/schema.rb, db/seeds.rb, test/controllers/workflow_executions_controller_test.rb, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/models/workflow_execution_test.rb, test/services/workflow_executions/create_service_test.rb, test/services/workflow_executions/destroy_service_test.rb, test/services/workflow_executions/preparation_service_test.rb, test/services/workflow_executions/status_service_test.rb, test/system/workflow_executions_test.rb
This PR changes workflow execution state from type string to enum. It also sets the state to `running` when the returned state is `RUNNING` and removes the state `queued`.
1. With workflow executions stored in your database, run `bin/rails db:migrate`. Ensure the migration is successful
2. Through the UI, check the workflow executions page displays the expected states per WE
3. Run a workflow execution containing a large number of samples. After sometime in the `submitted` state, ensure the WE state eventually changes to `running`. Afterwards, check that the WE completes.
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, …
=> Workflow Execution: Change state to enum

app/services/workflow_executions/preparation_service.rb, test/fixtures/samples_workflow_executions.yml, test/services/workflow_executions/preparation_service_test.rb
Update `WorkflowExecutions::PreparationService` to ensure that the generated samplesheet.csv has the correct column ordering.
* Run Tests verify that they work
* Add a pipeline that has both metadata and files to `config/pipelines/pipelines.json`
```json
{
"url": "https://github.com/phac-nml/gasclustering",
"name": "phac-nml/gasclustering",
"description": "IRIDA clustering",
"versions": [
{
"name": "metadata"
}
]
}
```
* Submit a new workflow execution for the newly configured pipeline
* Look at the samplesheet.csv and verify that the columns are ordered …
=> Fix: samplesheet column ordering

app/mailers/data_export_mailer.rb, config/locales/fr.yml, test/mailers/data_export_mailer_test.rb
This PR adds locale to the data export mailer.
1. Load up mailhog with
```
~/go/bin/MailHog
```
2.  In a rails console, create a data export with email notification
```
user = User.find_by(email: 'user7@email.com')
params_1 = {'export_type' => 'sample', 'export_parameters' => {'ids' => [Sample.find_by(name: 'Yersinia pestis/Outbreak 2022 Sample 10').id]}, 'email_notification' => true, 'name' => 'test export'}
DataExports::CreateService.new(user, params_1).execute
```
3. After 30s, you should receive an email notification in maihog in english.
4. Repeat the above but set the user locale to fr
```
user = User.find_by(email: 'user7@email.com')
user.locale = :fr
user.save
params_1 = {'export_type' => 'sample', 'export_parameters' => {'ids' => [Sample.find_by(name: 'Yersinia pestis/Outbreak …
```
=> Add locale to Data Export Mailer

app/jobs/workflow_execution_cancelation_job.rb, app/jobs/workflow_execution_status_job.rb, app/jobs/workflow_execution_submission_job.rb, app/services/workflow_executions/cancelation_service.rb, db/migrate/20240418180337_add_error_code_to_workflow_execution.rb, db/schema.rb, lib/integrations/api_exceptions.rb, lib/integrations/ga4gh_wes_api/v1/api_requester.rb, test/active_job_test_case.rb, test/jobs/workflow_execution_cancelation_job_test.rb, test/jobs/workflow_execution_status_job_test.rb, test/jobs/workflow_execution_submission_job_test.rb, test/test_helpers/active_job_test_helpers.rb
Fixes #513
1. Adds retry and error rescue to jobs that connect to ga4gh wes. Details below.
2. Fixes a race condition bug where a job that a user cancelled sometimes finishes and completes(writes to samples) instead of cancelling.
3. Created a new set of helper functions `ActiveJobTestHelpers` to allow mocking Faraday based API integrations for active job tests.
You will need to have `Sapporo` running and connected to test
The following 3 jobs reach out to ga4gh wes.
1. WorkflowExecutionStatusJob
2. WorkflowExecutionSubmissionJob
3. …
=> Workflow executions: Requeue jobs

app/mailers/pipeline_mailer.rb, config/application.rb, config/locales/fr.yml, db/seeds.rb, test/mailers/pipeline_mailer_test.rb, test/mailers/previews/pipeline_mailer_preview.rb
Localized the pipeline mailer.
Pipeline **completed** email in **English**:
Pipeline **completed** email in **French**:
Pipeline **errored** email in **English**:
Pipeline **errored** email in **French**:
1. Install local mock email service, [Mailhog](https://github.com/mailhog/MailHog).
1. After setup, open a terminal and run `~/go/bin/MailHog`.
1. Run irida-next.
1. Open a rails console.
1. Select a workflow execution.
`w = WorkflowExecution.first`
1. Make sure email notifications are enabled.
`w.email_notification = true`
1. Set submitter locale:
`w.submitter.locale = :en`
1. Change state to `completed` or `error`.
`w.state = "completed"`
1. Save the workflow execution.
`w.save`
1.  Open a browser and navigate to http://0.0.0.0:8025/. Check mock email service for sent email.
1. Repeat …
=> Localize pipeline mailer

app/jobs/automated_workflow_executions/launch_job.rb, app/services/attachments/create_service.rb, app/services/automated_workflow_executions/launch_service.rb, test/fixtures/automated_workflow_executions.yml, test/fixtures/members.yml, test/fixtures/users.yml, test/jobs/automated_workflow_executions/launch_job_test.rb, test/services/attachments/create_service_test.rb, test/services/automated_workflow_executions/launch_service_test.rb
This PR adds in `AutomatedWorkflowExecution` launching upon upload of pair end data to a Sample in a Project that has `AutomatedWorkflowExecutions` configured.
1. Launch server using `bin/dev`
2. Login as `user1@email.com`
3. Create a personal project named `test awe`
4. Launch rails console (`bin/rails c`) and execute the following to add an automated workflow execution:
```irb
AutomatedWorkflowExecutions::CreateService.new(User.find_by(email: 'user1@email.com'), { namespace: Namespaces::ProjectNamespace.find_by_full_path('user1_at_email.com/test-awe'), …
```
=> Automated Workflow Execution launching

app/mailers/group_link_mailer.rb, app/mailers/member_mailer.rb, app/models/member.rb, app/models/namespace_group_link.rb, app/services/members/create_service.rb, app/services/members/destroy_service.rb, config/locales/fr.yml, test/fixtures/users.yml, test/mailers/group_link_mailer_test.rb, test/mailers/member_mailer_test.rb, test/mailers/pipeline_mailer_test.rb, test/mailers/previews/group_link_mailer_preview.rb, test/mailers/previews/member_mailer_preview.rb, test/services/group_links/group_link_service_test.rb, test/services/group_links/group_unlink_service_test.rb, test/services/members/create_service_test.rb, test/services/members/destroy_service_test.rb
Sending member & group link emails to users in the locale set within their account.
A continuation of #571. Fixes #566.
Please see #542 & #564.
Please see #542 & #564.
Verify users & managers received their email in their locale of choice.
Try changing the locale drop-down in the [member](http://localhost:3000/rails/mailers/member_mailer) & [group_link](http://localhost:3000/rails/mailers/group_link_mailer) mailer previews.
=> Localize member & group link mailers

app/services/automated_workflow_executions/launch_service.rb, test/services/automated_workflow_executions/launch_service_test.rb
When a WorkflowExecution is launched by an AutomatedWorkflowExecution, set the name to be the name of the AutomatedWorkflowExecution if present plus the Samples PUID.
Verify tests pass
=> Automated Workflow Executions: Launch Service auto naming

app/controllers/data_exports_controller.rb, app/controllers/projects/samples/attachments_controller.rb, app/policies/data_export_policy.rb, app/views/data_exports/_data_export.html.erb, app/views/data_exports/show.html.erb, app/views/projects/samples/attachments/_attachment.html.erb, config/routes.rb, config/routes/project.rb, test/controllers/data_exports_controller_test.rb, test/controllers/projects/samples/attachments_controller_test.rb, test/system/data_exports_test.rb
This PR changes from using the download endpoints for sample attachments and data exports to utilizing the Rails helper `rails_blob_path` to download the files.
1. Ensure you are able to create and download both sample and workflow execution exports
2. Ensure you can download both single and paired-end sample files.
=> [ENHC0010017] Change  download paths to use rails_blob_path

app/models/member.rb, app/policies/namespaces/project_namespace_policy.rb, app/views/layouts/projects.html.erb, config/locales/en.yml, test/controllers/projects/workflow_executions_controller_test.rb, test/fixtures/members.yml, test/services/data_exports/create_service_test.rb, test/system/workflow_executions/submissions_test.rb
Fixing access to project workflow executions & analysis data exports. Only members with `analyst` access or higher should have access.
Fixes #617.
A project member with a role less than an `analyst` should not be able to view a project workflow execution:
A project member with a role of an `analyst` or higher should be able to view a project workflow execution & create a data export:
1. Create a new project.
1. Select "Settings" -> "Automated Workflow Executions" from the sidebar menu.
1. Click the "New automated workflow execution" button.
1. Select a workflow and click the "Submit" button.
1. Create a new sample within the project.
1. Upload files within the new sample.
1. Select "Workflow Executions" from the sidebar menu.
1. Verify the new project workflow exists.
1. Add members to …
=> [DFCT0010059] Fixing user permissions for project workflow executions

app/controllers/concerns/metadata.rb, app/models/group.rb, app/models/namespace.rb, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/samples.yml, test/models/group_test.rb, test/system/groups/samples_test.rb
When launching a Workflow Execution from the Group Samples page when the Samples come from a shared Project or a shared Group. The metadata fields dropdown would not populate. Also when toggling the metadata on the same Group Samples page no metadata would show from the Samples even though they contained it.
This PR adds in a new method `metadata_fields` to Namespace model with override in Group model. The override in the Group model will query the Shared Groups and Shared Projects to include their metadata fields in the result of the method.
1. Create a new …
=> Fix: Metadata Fields retrieval for Shared Groups and Shared Projects [DFCT0010073]

app/services/samples/metadata/file_import_service.rb, app/views/projects/samples/metadata/file_imports/_dialog.html.erb, config/locales/en.yml, config/locales/fr.yml, test/fixtures/files/metadata/valid.tsv, test/services/samples/metadata/file_import_service_test.rb
Adds tab-delimited csv files (.tsv) to supported file types for metadata importing.
1. In the web interface, go to a projects samples page and click the `Import Metadata` button
2. See that the Upload Sample Metadata pop up indicates that TSV files are an option
3. Click `Browse...` to open a file picker, and see that `*.tsv` files are supported
4. Select a TSV file (example: `test/fixtures/files/metadata/valid.tsv`) and see that the `Sample ID Column` drop down selector shows the parsed column headers.
5. If your TSV file matches the samples you should be able to import the metadata from the file.
This checklist …
=> [ENHC0010029] Add TSV support for Metadata imports

app/graphql/resolvers/is_puid_resolver.rb, app/graphql/schema.graphql, app/graphql/types/query_type.rb, lib/irida/persistent_unique_id.rb, test/graphql/is_puid_query_test.rb
This PR adds in a new query named `isPuid` which returns `True` if the `id` given is in `puid` format. The query determines this from the `id` argument given.
1. Launch server and login as your preferred user
2. Navigate to `GraphiQL` endpoint (e.g. `http://localhost:3000/graphiql`)
3. Try the `isPuid` query using sample id
```
{
isPuid(id: "INXT_SAM_245HANDHG5")
}
```
4. Try the `isPuid` query using sample id
```
{
isPuid(id: "INXT_SAM_245HANDHG865")
}
```
5. Try querying an id for either a `Sample`, `Attachment`, `Group`, or `Namespace::ProjectNamespace`
This …
=> GraphQL: Add isPuid query 

docs-site/docs/user/organization/members/group-and-project-members.md, docs-site/docs/user/project/projects/manage-projects.md, docs-site/docs/user/project/projects/projects-intro.md, docs-site/docs/user/project/samples/manage-samples.md, docs-site/docs/user/project/samples/sample-files.md, docs-site/docs/user/project/samples/sample-metadata.md, docs-site/docs/user/project/samples/samples-intro.md
This PR updates the Project and Sample docs. This includes:
- Projects Intro
- View Project History
- Samples intro
- View Samples History
- Download Sample Files
- Sample Metadata
1. Start the docs in a terminal within your `irida-next` repo with:
```
cd docs-site
pnpm build
npm run serve
```
2. Read the documentation and see if it makes sense from a user's perspective.
3. Check that links navigate to the correct pages.
=> Docs: Project and Sample

app/controllers/concerns/share_actions.rb, app/models/namespace_group_link.rb, app/services/group_links/group_link_service.rb, config/locales/en.yml, config/locales/fr.yml, test/controllers/concerns/group_share_actions_concern_test.rb, test/controllers/groups/group_links_controller_test.rb, test/controllers/projects/group_links_controller_test.rb, test/models/namespace_group_link_test.rb, test/services/group_links/group_link_service_test.rb
Fixes #642 
Fixes bug where a group could be shared with itself.
* No longer displays own group as an option to share on the `Groups>Members>Groups>Invite Group` form.
* Adds validation to NamespaceGroupLink such that group_id cannot equal namespace_id
1. Sign in with a non admin user
2. Create a new group
3. Select `Members` on sidebar, then select `Groups` tab, then click `Invite Group`
4. In the `Group to share namespace with` dropdown, see that the current group is not in the list of groups. …
=> [DFCT0010089] Fix groups being able to recursively share to themselves

app/components/nextflow/samplesheet/column_component.rb, app/components/nextflow/samplesheet/dropdown_cell_component.html.erb, app/components/nextflow_component.html.erb, app/controllers/concerns/workflow_execution_actions.rb, app/views/workflow_executions/_params.html.erb, app/views/workflow_executions/_samples.html.erb, app/views/workflow_executions/_samplesheet.html.erb, app/views/workflow_executions/_summary.html.erb, app/views/workflow_executions/show.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/nextflow_samplesheet_component_test.rb, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/attachments.yml, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/policies/workflow_execution_policy_test.rb, test/system/workflow_executions_test.rb
1. Create a new project
2. Add a sample to the project and upload sequence files to the sample.
3. Go back to your new project samples page and select the new sample and launch a pipeline for it.
4. Go to workflow executions and select the new one.
5. Select the tab for `Samplesheet`
6. Files should be displayed as above.
=> Display samples for workflow execution (ENHC0010030)

app/components/list_filter_component.html.erb, app/javascript/controllers/list_filter_controller.js, test/components/viral/system/list_filter_component_test.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
Fixes #647 Addresses issue when using lodash debounce to automatically create tags was confusing to users.  In this update the user must add a coma.  The final name does not need a coma, but will be converted into a tag when the user presses the submit button.
1. Go to any project that has samples.
2. Open the filter by name or puid dialog
3. Start typing sample names, and enter a comma, the name should be converted into a tag.
4. Add another sample name and press enter, dialog should close, count on button should be updated to the correct amount, and table …
=> Sample filtering when manually entering samples results in cursor moving to next sample entry if there is a pause (DFCT0010081)

config/environments/development.rb, config/environments/test.rb, config/routes.rb
This PR updates routes to set default_url_options in all environments (prod was missing).
1. Test that `attachment_url` in `attachment` type still work in graphql.
```
query {
sample(puid: "SAMPLE_PUID") {
attachments {
nodes {
attachmentUrl
}
}
}
}
```
=> Fix: URL Helpers in Prod missing default url options (DFCT0010104)

app/controllers/data_exports_controller.rb, test/controllers/data_exports_controller_test.rb
This PR adds the linelist export logic to the existing `data_exports_controller`. This required updating the `data_export_params` to include `linelist` params and updating the `new` action to use the eventual `linelist export modal`
1. Ensure tests pass locally.
=> [STRY0011998] Linelist Exports: Controller

app/graphql/irida_schema.rb, app/graphql/schema.graphql, app/graphql/types/attachment_type.rb, app/graphql/types/base_type.rb, app/graphql/types/namespace_type.rb, app/graphql/types/project_type.rb, app/graphql/types/sample_type.rb, app/graphql/types/user_type.rb, test/graphql/attachments_query_test.rb, test/graphql/group_query_test.rb, test/graphql/groups_query_test.rb, test/graphql/namespace_query_test.rb, test/graphql/project_query_test.rb, test/graphql/sample_query_test.rb
This PR adds `createdAt` and `updatedAt` to all types in GraphQL API by adding a new `BaseType` which adds these fields. In addition `attachmentsUpdateAt` has been added to Sample type.
This also updates the GraphQL api to have a default page size of 25.
1. Start server and navigate to GraphIQL interface (e.g. http://localhost:3000/graphiql)
2. In Docs view, verify that `Attachment`, `Group`, `Namespace`, `Project`, `User` types have `createdAt` and `updatedAt` fields
3. In Docs view, verify that `Sample` type has `createdAt`, `updatedAt` and …
=> GraphQL: Add timestamps

app/components/nextflow/samplesheet/column_component.rb, app/components/nextflow/samplesheet/sample_name_cell_component.html.erb, app/components/nextflow/samplesheet/sample_name_cell_component.rb, app/components/nextflow/samplesheet_component.rb, test/components/nextflow_samplesheet_component_test.rb, test/fixtures/files/nextflow/samplesheet_schema.json, test/fixtures/files/nextflow/schema_input.json
Updated the `SamplesheetComponent` to include sample names. 
See http://localhost:3000/rails/lookbook/inspect/nextflow_samplesheet/default.
Fixes #670.
1. Add `add-sample-name` to versions within the `pipelines.json` file. (Reference https://github.com/phac-nml/iridanextexample/tree/add-sample-name)
1. Run sapporo-service.
1. Run irida-next.
1. Execute the newly added pipeline `add-sample-name`.
1. Verify the sample name is displayed within the sample sheet. 
=> Workflow Execution: Sample Name Cell Component

app/components/nextflow/samplesheet/column_component.rb, app/components/nextflow/samplesheet/metadata_cell_component.html.erb, app/components/nextflow/samplesheet/metadata_cell_component.rb, app/components/nextflow/samplesheet/text_cell_component.html.erb, app/components/nextflow/samplesheet/text_cell_component.rb, test/components/nextflow_samplesheet_component_test.rb, test/fixtures/files/nextflow/samplesheet_schema_meta.json
If a field does not have a pre-defined value, display a text field (set required if needed) to allow the user to enter a value.
I set it up so it can be easily seen in the LookBook:
1. Go to: http://localhost:3000/rails/lookbook/inspect/nextflow_samplesheet/default?schema_file=samplesheet_schema_meta.json
2. The `PFGE_PATTERN` column has no pre-defined data and is required. 
3. Ensure that the text field is displayed and when inspecting the field, the `required` attribute should be set. …
=> Enhancement: Enforce sample sheet required fields

app/components/viral/dialog_component.html.erb, app/components/viral/flash_component.html.erb, app/javascript/controllers/form/hidden_inputs_controller.js, app/javascript/controllers/infinite_scroll_controller.js, app/javascript/controllers/selection_controller.js, app/models/project.rb, app/models/sample.rb, app/services/samples/transfer_service.rb, app/views/data_exports/_new_linelist_export_dialog.html.erb, app/views/data_exports/_new_sample_export_dialog.html.erb, app/views/projects/samples/clones/_dialog.html.erb, app/views/projects/samples/clones/create.turbo_stream.erb, app/views/projects/samples/deletions/_new_deletion_dialog.html.erb, app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb, app/views/projects/samples/index.html.erb, app/views/projects/samples/transfers/_dialog.html.erb, app/views/projects/samples/transfers/create.turbo_stream.erb, config/cable.yml, test/jobs/workflow_execution_cancelation_job_test.rb, test/jobs/workflow_execution_cleanup_job_test.rb, test/jobs/workflow_execution_status_job_test.rb, test/jobs/workflow_execution_submission_job_test.rb
This PR is a follow up to #679.
* Added in action cable config and updated the Projects Table so that it is now refreshed when a Sample is created, updated, or deleted.
* Moved hidden input handling from `infinite-scroll` controller into a new `form--hidden-inputs` controller.
* Updated `clone` and `transfer` samples response to reload the page
* Added `data-turbo-permanent` to `dialog` and `flash` so that if the page is refreshed they persist.
2. Navigate to Project Samples page for Project of choice
3. Perform actions on the table that require …
=> Samples table enhancements followup

app/jobs/data_exports/create_job.rb, test/jobs/data_exports/create_job_test.rb
This PR adds the `Project PUID` to linelist exports created from `projects`. Previously, the `Project PUID` was only included for linelist exports from `groups`
1. Navigate to a project with samples that have metadata
2. Create a linelist export.
3. Download the export after it's ready. Verify the `Project PUID` is included.
4. Repeat with the format you did not use above.
5. Repeat the above, exporting from `Groups`. Verify the exports are as expected (sample id, name, project puid and metadata fields).
=> Linelist Export: Include Project PUID to project.type exports

app/validators/attachment_checksum_validator.rb, test/graphql/attach_files_to_sample_test.rb, test/models/attachment_test.rb, test/system/data_exports_test.rb
This PR changes the Attachment checksum validation. Previously, samples could not have two attachments with the same checksum attached. With the new validation, samples can have attachments with the same checksum attached, as long as they have different filenames
Attachments with same checksum but different filenames:
Old Validation:
[Screencast from 2024-08-13 03:53:17 PM.webm](https://github.com/user-attachments/assets/076e033a-00e3-47c2-8cac-0eb23e303aac)
New Validation:
[Screencast from 2024-08-13 03:51:56 PM.webm](https://github.com/user-attachments/assets/9377163f-3a41-4154-a013-660e3e19c052)
1. Create two files that are a copy of one another (same checksum) except with different filenames
2. Navigate to any sample files page
3. Upload the above files. They should upload normally. …
=> Enhancement: Attachment Checksum Validation

app/components/samples/table_component.html.erb, app/components/workflow_executions/table_component.html.erb
This PR is a follow-up to to [PR694](https://github.com/phac-nml/irida-next/pull/694), and adds a workaround to the `Last Updated` column. Before this PR, after table morphing, the `Last Updated` `time_ago` would switch back to UTC time and not using the `local_time_ago`.
1. Start a Workflow Execution
2. Ensure `Last Updated` updates periodically and stays as a `time_ago` reading rather than switching to a UTC timestamp.
3. Create a sample in a project
4. Ensure `Last Updated` updates periodically and stays as a `time_ago` reading rather than switching to a UTC timestamp.
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, …
=> Fix: local_time_ago on sample and workflow execution table_components

app/graphql/irida_schema.rb, app/graphql/mutations/attach_files_to_sample.rb, app/graphql/mutations/base_mutation.rb, app/graphql/mutations/create_direct_upload.rb, app/graphql/mutations/create_sample.rb, app/graphql/mutations/update_sample_metadata.rb, app/graphql/schema.graphql, app/graphql/types/user_error_type.rb, app/services/attachments/create_service.rb, app/services/samples/metadata/update_service.rb, config/routes.rb, db/migrate/20240730161412_metadata_keys_downcase.rb, docs-site/docs/configuration/options.md, test/graphql/attach_files_to_sample_test.rb, test/graphql/create_direct_upload_test.rb, test/graphql/create_sample_mutation_test.rb, test/graphql/irida_schema_test.rb, test/graphql/update_sample_metadata_test.rb, test/services/samples/metadata/fields/update_service_test.rb, test/services/samples/metadata/file_import_service_test.rb, test/services/samples/metadata/update_service_test.rb, test/system/projects/samples_test.rb
Fixes #667 
1. Fixes the port number not being included when direct upload links are created
2. Fixes error when a non positive number is given to createDirectUpload mutation
3. Fixes strings not being parsed into hashes when used as metadata
4. Added new metadata field list `unchanged:` for updating fields that already match values
5. Fixes multiple 500 errors related to graphql query not finding sample id/puid, project id/puid
6. Fixes 500 error when trying to add a blob to a sample where the blob has no file.
7. Changed metadata update service to downcase all keys (fields)
8. Added migration to downcase existing metadata keys …
=> fix graphql error messages

app/controllers/projects/samples/metadata/file_imports_controller.rb, app/policies/group_policy.rb, app/policies/namespaces/project_namespace_policy.rb, app/services/samples/metadata/file_import_service.rb, app/views/projects/samples/metadata/file_imports/create.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/policies/group_policy_test.rb, test/policies/namespaces/project_namespace_policy_test.rb, test/services/samples/metadata/file_import_service_test.rb
The `Samples::Metadata::FileImportService` has been updated to accept a namespace instead of a project, because users want the ability to import from the Group Samples Page.
The existing project sample metadata import should work as usual.
Fixes #696.
N/A
- Test via running the service tests:
1. Run tests within `test/services/samples/metadata/file_import_service_test.rb`
- Test via console:
1. Create a new csv file and copy the following into it:
```
SAMPLE ID,AGE,FOOD,GENDER,NEW
INXT_SAM_AYIJB6262K,43,Pork Belly Buns,Female,TRUE
INXT_SAM_AYIJB6266D,49,Fish and Chips,Female,TRUE
INXT_SAM_AYIJB627B5,6,Vegetable Soup,Female,TRUE
INXT_SAM_AYIJB627FZ,59,Pizza,Female,TRUE
INXT_SAM_AYIJB627KC,24,Chilli con Carne,Male,TRUE
INXT_SAM_AYIJB627N5,47,Teriyaki Chicken Donburi,Female,TRUE …
```
=> File import service enhancements

app/components/nextflow_component.html.erb, app/javascript/controllers/nextflow/samplesheet_controller.js, app/views/projects/automated_workflow_executions/update.turbo_stream.erb
When selecting a metadata column in the samplesheet for a pipeline, the dialog would close after retrieving the metadata.
This bug was accidentally introduced when fixing editing automated workflow executions where we wanted the dialog to close on update.
Update action for automated workflow execution has been updated to close the dialog after update instead of using turbo hook.
=> Fix: Metadata selection in nextflow samplesheet

app/controllers/data_exports_controller.rb, app/jobs/data_exports/create_job.rb, app/models/data_export.rb, app/policies/group_policy.rb, app/policies/namespaces/project_namespace_policy.rb, app/policies/project_policy.rb, app/policies/workflow_execution_policy.rb, app/services/data_exports/create_service.rb, app/views/data_exports/_new_analysis_export_dialog.html.erb, app/views/groups/samples/_table.html.erb, app/views/groups/samples/index.html.erb, app/views/projects/samples/_table.html.erb, app/views/projects/samples/index.html.erb, app/views/projects/workflow_executions/show.html.erb, app/views/workflow_executions/show.html.erb, config/locales/en.yml, config/locales/fr.yml, test/controllers/data_exports_controller_test.rb, test/fixtures/data_exports.yml, test/jobs/data_exports/create_job_test.rb, test/models/data_export_test.rb, test/policies/project_policy_test.rb, test/services/data_exports/create_service_test.rb
This PR adds new logic to accept multiple workflow execution IDs for any analysis export
1. Set up the ability to run workflow executions locally as described in [PR 507](https://github.com/phac-nml/irida-next/pull/507)
2. Run a couple workflow executions
3. Once completed, export it with:
```
user = USER YOU MADE WORKFLOW EXECUTION WITH
params_1 = {'export_type' => 'analysis', 'export_parameters' => {'ids' => [FIRST_WORKFLOW_EXECUTION_ID, SECOND_WORKFLOW_EXECUTION_ID], 'analysis_type' => 'user'}, 'email_notification' => true, 'name' => 'test export'}
DataExports::CreateService.new(user, params_1).execute
```
4. After 30s, download the export either through the UI or with (replace `localhost` …
=> Analysis Exports: Backend - Accept multiple workflow IDs

db/migrate/20240822144703_modify_personal_access_token_logidze_trigger_v02.rb, db/schema.rb, db/triggers/logidze_on_personal_access_tokens_v02.sql
This PR aims to fix a performance degradation when using a read vs a read_write token by removing the logidze entries for `last_used_at` for personal access tokens.
=> Personal Access Token: remove logidze last_used_at entries

app/controllers/concerns/file_import_actions.rb, app/controllers/groups/samples/metadata/file_imports_controller.rb, app/controllers/projects/samples/metadata/file_imports_controller.rb, config/locales/en.yml, config/locales/fr.yml, config/routes/group.rb, test/controllers/groups/samples/metadata/file_import_controller_test.rb
The new group file import controller that calls the updated `Samples::Metadata::FileImportService`.
The existing project sample metadata import should work as usual.
This is an extension of https://github.com/phac-nml/irida-next/pull/704.
N/A
Verify the tests within `test/controllers/groups/samples/metadata/file_import_controller_test.rb` &  `test/controllers/projects/samples/metadata/file_import_controller_test.rb` pass.
=> File import controller enhancements

app/models/concerns/has_puid.rb, app/services/samples/clone_service.rb, lib/base32.rb, lib/irida/persistent_unique_id.rb
Updates PUID resolution from 1024 to 12228 per second.
Updates HasPuid to override `save!` method to rescue from unique constraint violation for PUID, and regenerate and then re save until no conflicts.
1. Comment out lines 10-15 in `app/models/concerns/has_puid.rb`
2. Launch server with `bin/dev`
3. Clone 1 sample from one project to another.
* Observe the following in the log output:
```
↳ app/models/concerns/has_puid.rb:18:in `save!'
TRANSACTION (0.1ms)  ROLLBACK
```
* Observe that clone succeeds …
=> PUID: Uniqueness Conflict Recovery and Resolution Increase

app/components/layout_component.html.erb, app/components/samples/table_component.rb, app/controllers/groups/application_controller.rb, app/controllers/groups/samples_controller.rb, app/controllers/projects/application_controller.rb, app/controllers/projects/samples_controller.rb, app/controllers/projects/workflow_executions_controller.rb, app/views/layouts/groups.html.erb, app/views/layouts/projects.html.erb, app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb, app/views/projects/samples/attachments/_attachment.html.erb
Previously both the groups and projects layouts specified that the LayoutComponent was always fixed, now controllers which use either layout can specify if the layout should be fixed or not (e.g. be able to take the full width).
With this change, both the Group and Project Samples index use non fixed layout and Project Workflow Executions uses non fixed layout.
Additionally `data-turbo-prefetch="false"` has been added to LayoutComponent, so now hovering over a link will not preload it anywhere within the application.
2. Go to Project Samples …
=> Groups/Projects layout: Add controller option for fixed layout

app/controllers/data_exports_controller.rb, app/models/data_export.rb, app/views/data_exports/show.html.erb, app/views/data_exports/show.turbo_stream.erb, test/system/data_exports_test.rb
This PR enhances the Data Exports' `show` page to automatically refresh once the export status changes from `processing` to `ready`.
[Screencast from 2024-08-22 12:36:08 PM.webm](https://github.com/user-attachments/assets/e8a2ead9-e092-4411-b36b-d2ff665eee41)
1. Create a sample export
2. Once redirected onto the `show page`, stay on the page for 30s until the export is ready. The page should automatically refresh and the following should change:
- Status changes from `processing` to `ready`
- `Download` button is enabled
- Expiry date is available
- `Preview` tab is added
=> Enhancement: Export Show

app/graphql/resolvers/projects_resolver.rb, app/graphql/resolvers/samples_resolver.rb, app/graphql/schema.graphql, app/graphql/types/project_type.rb, app/policies/graphql_policy.rb, app/policies/project_policy.rb, app/policies/sample_policy.rb, test/graphql/create_sample_mutation_test.rb, test/graphql/projects_query_test.rb, test/graphql/update_sample_metadata_test.rb, test/policies/project_policy_test.rb
This PR adds in an optional argument to `projects` query named `groupId`, this can be used to limit the results to `projects` only accessible by members with access to the `Group` specified by `groupId`. This includes direct, indirect (projects from subgroups), and linked projects (projects shared with group or subgroup, or contained within groups and their subgroups that are shared with this group or groups subgroups).
2. Create a Group hierarchy that has subgroups with projects, and has projects shared to the group or any of the subgroups, …
=> GraphQL: Projects query add group_id arg

app/controllers/data_exports_controller.rb, app/models/data_export.rb, app/services/data_exports/create_service.rb, app/views/data_exports/destroy.turbo_stream.erb, app/views/data_exports/index.html.erb, app/views/data_exports/show.html.erb, test/controllers/data_exports_controller_test.rb, test/jobs/data_exports/create_job_test.rb, test/models/data_export_test.rb
This PR adds enhancements to the Data Exports `index` page, where the page will automatically refresh when export statuses change from `processing` to `ready`.
[Screencast from 2024-08-22 12:38:18 PM.webm](https://github.com/user-attachments/assets/a724667b-cfa9-4ea9-8bd4-924cb985840b)
1. Through the UI, create an export
2. After redirection to the `show` page, navigate to the `index` page.
3. After 30s, the page should refresh on its own and the export status should now be `ready` with the available `download` link.
Other tests:
4. Logic for data export deletion was changed. Delete exports from both the `index` and `show` page. Ensure on the `index` page that the table updates upon deletion with the expected success flash message. On the `show` page, ensure you are redirected back to the …
=> Enhancement: Data Export Index

app/components/viral/select2_component.html.erb, app/javascript/controllers/viral/select2_controller.js, app/views/groups/group_links/_invite_group_modal.html.erb, app/views/groups/members/_create_modal.html.erb, app/views/projects/group_links/_invite_group_modal.html.erb, app/views/projects/members/_create_modal.html.erb, app/views/projects/samples/clones/_dialog.html.erb, app/views/projects/samples/transfers/_dialog.html.erb, test/components/previews/viral_select2_component_preview/default.html.erb, test/components/viral/select2_component_test.rb
In preparation for adding the `Select2` component to project and group transfers, which requires `Select2` to enable/disable its submit buttons, this PR ties previous `Select2` implementations to their associated `submit` buttons.
In addition, if a user made a selection, but then changed the input, as long as the input contained something, the user could still submit. This could lead to accidental/unexpected submission by the user. Now, if you user makes a selection, then changes the input in anyway, the `submit` button will enter the `disabled` state and require the user to make another selection.
[Screencast from 2024-09-05 03:23:50 PM.webm](https://github.com/user-attachments/assets/a2efc61c-45b8-49af-9025-ddd24c35bd56)
1. Navigate to a project samples table, select samples, and click …
=> Enhancement: Select2 component

app/graphql/resolvers/project_samples_resolver.rb, app/graphql/resolvers/samples_resolver.rb, app/graphql/schema.graphql, app/graphql/types/project_type.rb, app/graphql/types/sample_order_input_type.rb, app/graphql/types/sample_type.rb, test/graphql/project_samples_query_test.rb, test/graphql/samples_query_ransack_test.rb
Adds in ordering to samples query, and adds in filtering and ordering to project samples query.
1. Create a new Group
2. Create a new Project under the new group
3. Create 2 samples in the project.
4. Upload pair end `fastq.gz` attachments to one of the samples
5. Execute the following query to get the Groups ID for querying the samples.
```graphql
query groupId {
group(puid: puid: "GROUP PUID") {
id
}
}
```
6. Execute the following query to only retrieve the sample with `fastq.gz` files from the project:
```graphql
query fastqSamples {
project(puid: "PROJECT …
```
=> GraphQL: Samples filtering and ordering

app/components/nextflow/samplesheet/column_component.rb, app/components/nextflow/samplesheet_component.rb
Do not display non-fastq files in the fastq select.
1. Create a new project (or just use an existing one)
2. Create a new sample and upload a set of fastq files
3. Create another new sample and upload some non-fastq files
4. Go back to the project and open the dialog to launch a `phac-nml/iridanextexample` pipeline with the two new samples
5. Only the sample with the fastq samples should have visible files (as seen in the above image). …
=> ColumnComponent: Exclude non-fastq files if no fastq are present

app/graphql/resolvers/projects_resolver.rb, app/graphql/schema.graphql, app/graphql/types/project_filter_type.rb, app/graphql/types/project_order_input_type.rb, app/models/project.rb, test/graphql/projects_query_ransack_test.rb, test/graphql/samples_query_ransack_test.rb
Adds ransack filtering and ordering to the graphql projects query
1. Sign in with user1
2. go to GraphiQL 
3. Test filtering
```graphql
query get_projects_filter{
projects(filter: { name_cont:"2023"  }
nodes{
puid
name
createdAt
updatedAt
}
}
}
```
4. test ordering
```graphql
query get_projects_order_by{
projects(orderBy:{field:updated_at, direction:desc}){
nodes{
puid
name
createdAt
updatedAt
}
}
}
```
5. verify that queries with group id still work as intended
```graphql
query get_groups{
groups{
nodes{
name
id  
}
}
}
query get_projects_by_group{
projects( …
```
=> Graphql - Add ransack filtering and ordering to projects

app/graphql/resolvers/project_metadata_summary_resolver.rb, app/graphql/schema.graphql, app/graphql/types/project_type.rb, app/models/project.rb, test/graphql/projects_query_ransack_test.rb
Adds the `metadata_summary` field to graphql projects
1. Sign in and go to GraphiQL
2. Test the new field
```graphql
query get_projects_metadata{
projects{
nodes{
puid
name
metadataSummary
}
}
}
```
3. Test with arguments
```graphql
query get_projects_metadata{
projects{
nodes{
puid
name
metadataSummary(keys: ["age","gender"])
}
}
}
```
=> Graphql - Add metadata_summary field to Projects

app/graphql/resolvers/groups_resolver.rb, app/graphql/schema.graphql, app/graphql/types/attachment_order_input_type.rb, app/graphql/types/group_filter_type.rb, app/graphql/types/group_order_input_type.rb, app/graphql/types/project_order_input_type.rb, app/graphql/types/sample_order_input_type.rb, app/models/group.rb, test/graphql/attachments_query_test.rb, test/graphql/groups_query_ransack_test.rb, test/graphql/projects_query_ransack_test.rb, test/graphql/samples_query_ransack_test.rb
Adds ransack filtering and ordering to the graphql  groups query
Added `name` to order by for projects, samples, and groups
Added `filename` to order by for attachments
Improved tests for order by 
1. Sign in with user1
2. go to GraphiQL
3. test filtering
```graphql
query get_groups{
groups(
filter:{name_cont:"pyogenes"}
){
nodes{
name
id
puid
updatedAt
createdAt
}
}
}
```
4. test ordering
```graphql
query get_groups{
groups(
orderBy:{field:created_at, direction:desc}
){
nodes{
name
id
puid
updatedAt
createdAt
}
}
}
```
This checklist encourages us to confirm …
=> Graphql - Add ransack filtering and ordering to groups 

app/models/member.rb
This PR fixes project attachment permissions to allow project bots to create and destroy attachment. This issue is related to the implementation of [PR754](https://github.com/phac-nml/irida-next/pull/754)
1. Ensure tests pass locally.
=> Fix: Project Attachment Permissions for Bots

app/graphql/resolvers/project_attachments_resolver.rb, app/graphql/resolvers/project_sample_resolver.rb, app/graphql/resolvers/project_samples_resolver.rb, app/graphql/resolvers/projects_resolver.rb, app/graphql/resolvers/sample_attachments_resolver.rb, app/graphql/resolvers/samples_resolver.rb, app/graphql/types/attachment_type.rb, app/graphql/types/project_type.rb, app/graphql/types/sample_type.rb, test/controllers/projects/samples/attachments_controller_test.rb, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/data_exports.yml, test/graphql/attachments_query_test.rb, test/jobs/data_exports/create_job_test.rb, test/models/attachment_test.rb, test/services/attachments/create_service_test.rb, test/system/projects/samples_test.rb, test/system/workflow_executions_test.rb
This PR utilizes scoped context to mark in resolvers that the items are already authorized.
https://graphql-ruby.org/queries/executing_queries.html#scoped-context
It also uses the scoped context to set project in project samples resolver, so that if those samples want to retrieve project info we don't need to perform a second query or authorization.
1. Querying Projects:
```graphql
query myProjects {
projects(first: 100) {
nodes {
id
name
updatedAt
puid
}
pageInfo {
endCursor
hasNextPage
}
}
}
```
before:
after:
2. Querying Project Samples:
```graphql
query projectSamples{
project(fullPath: …
```
=> GraphQL: Use scoped context to skip queries and authorization

app/components/attachments/table_component.html.erb, app/components/attachments/table_component.rb, app/controllers/groups/attachments_controller.rb, app/views/groups/attachments/_form.html.erb, app/views/groups/attachments/_new_attachment_modal.html.erb, app/views/groups/attachments/_table.html.erb, app/views/groups/attachments/create.turbo_stream.erb, app/views/groups/attachments/index.html.erb, app/views/layouts/groups.html.erb, app/views/projects/attachments/_form.html.erb, app/views/projects/attachments/_table.html.erb, app/views/projects/attachments/index.html.erb, config/database.yml, config/locales/en.yml, config/locales/fr.yml, config/routes/group.rb, test/controllers/groups/attachments_controller_test.rb, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/attachments.yml, test/graphql/attachments_query_test.rb, test/system/groups/attachments_test.rb
This PR adds the attachments UI (for index listing and uploading) to groups
To follow:
Destroy will be added after [project attachments destroy](https://github.com/phac-nml/irida-next/pull/762) is merged.
Possible streamlining between group/project attachments (controller concerns etc.).
1. Navigate to a group
3. Click "Files" on the sidebar
4. Verify `No Files` state
5. Verify the upload works by uploading a bunch of files, preferably with different formats and types
6. Verify per page selection, pagination, and sorting/filtering works as expected
7. Click on a filename and ensure it downloads
Other tests:
8. Verify project `guests` cannot see the `Files` sidebar link in groups
9. Verify project `analysts` cannot see the `Upload Files` button on the groups attachments index page
10. …
=> Group Attachments: Index and Upload

app/components/attachments/table_component.html.erb, app/components/attachments/table_component.rb, app/controllers/groups/attachments_controller.rb, app/controllers/projects/attachments_controller.rb, app/views/groups/attachments/_table.html.erb, app/views/groups/attachments/index.html.erb, app/views/projects/attachments/_table.html.erb, app/views/projects/attachments/index.html.erb, test/system/groups/attachments_test.rb, test/system/projects/attachments_test.rb
This PR alters the `namespace.attachments` query in `index` to exclude paired-end (PE) reverse attachments. We are doing this because we render the PE attachments together within a single table row, but ransack will count both attachments, so 5 PE attachments would take up 10 'slots' within the attachments table, which is not intuitive with the limit selection.
In addition, when using ransack filter, the list of attachments will render each attachment individually (ie: PE attachments will be separated).
Currently on main (note limit: 10, but only 6 entries on the table):
Now:
Filtering PE:
In both project and group attachments:
1. Upload multiple paired-end files
2. Verify that each paired-end entry counts as a single attachment.
3. Test the new filter by filtering by something …
=> Namespace attachments: Index attachment query change

app/components/data_exports/table_component.html.erb, app/components/data_exports/table_component.rb, app/controllers/data_exports_controller.rb, app/views/data_exports/_table.html.erb, app/views/data_exports/index.html.erb, test/system/data_exports_test.rb
Displaying separate messages within the data export table to show empty state and no items found.
1. Navigate to the data exports page.
2. Search for a data export that does not exist.
3. Verify the `No items found` message is displayed.
4. Delete all the data exports within the table.
5. Verify the `No Data Exports` message is displayed.
=> Data exports table empty fix

app/components/activities/list_item_component.rb, app/services/workflow_executions/completion_service.rb, app/views/groups/activity.turbo_stream.erb, app/views/projects/activity.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, db/migrate/20240925155747_remove_group_activities_with_workflow_keys.rb, db/schema.rb, test/fixtures/files/blob_outputs/normal4/analysis1.txt, test/fixtures/files/blob_outputs/normal4/analysis2.txt, test/fixtures/files/blob_outputs/normal4/analysis3.txt, test/fixtures/files/blob_outputs/normal4/iridanext.output.json, test/fixtures/files/blob_outputs/normal4/summary.txt, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/services/workflow_executions/completion_service_test.rb
Fixes loading the activity page after a user submits a workflow that was launched from the samples page with the option `Update samples with analysis results` set to true.
For now, we are only displaying workflow execution completion activities if they were launched by an automation bot.
Also, fixed the `Load more` button on the activities page.
Fixes #784.
**Before:**
**After:**
**To recreate the issue:**
1. Comment out line 158 within `/app/services/workflow_executions/completion_service.rb`.
2. Launch a workflow execution from the group samples page with the option `Update samples with analysis results` set to true.
3. After completion, verify the group activities page does not load.
**To test the migration script:**
1. Run the latest migration called …
=> Fix workflow execution completion activities

app/components/attachments/dialogs/delete_attachment_component.html.erb, app/components/attachments/table_component.html.erb, app/components/attachments/table_component.rb, app/controllers/concerns/attachment_actions.rb, app/controllers/groups/attachments_controller.rb, app/views/groups/attachments/_table.html.erb, app/views/groups/attachments/index.html.erb, app/views/projects/attachments/_table.html.erb, app/views/projects/attachments/index.html.erb, config/locales/en.yml, config/locales/fr.yml, test/system/groups/attachments_test.rb, test/system/projects/attachments_test.rb
This PR adds the empty search state for group and project attachment pages.
In addition,  a small fix to the delete attachments dialog where it previously had "...delete attachment from group" for both groups and project. It now shows group/project dependent on where the attachment is being deleted.
Empty Search:
No files initially:
Delete attachment from project:
Delete attachment from group:
In both project and groups:
1. In a project/group with no files, ensure the "No Files" header and description are present
2. In a project/group with files, filter to where there are no files, ensure the "No Items Found" header and description are present
3. In a project/group, check the delete confirmation dialog and ensure "... from project/group" is shown for the correct type.
This checklist …
=> Namespace Attachments: Empty Search State

config/initializers/ransack.rb, db/migrate/20241003125314_update_metadata_indexes.rb, db/schema.rb, test/graphql/samples_query_ransack_test.rb
Removes the existing case sensitive GIN index for metadata on attachments and samples, and replaces it with a lowercase GIN index. This lower case index allows for case insensitive  searching, by first downcasing metadata column before searching (note: this requires that the query be downcased prior to searching, which is automatically done via ransack predicates).
1. Run db migrations to replace indexes
2. Follow testing instructions in #768 but use varying cases and ensure that searches work regardless of case.
This checklist encourages us to confirm any …
=> Metadata: Lower case index to support case insensitive searching

db/seeds.rb
This PR prevents `turbo_broadcasts` from occurring during seeding as they are unnecessary and slow down the seeding process.
Seed logs with broadcasts:
Seed logs without broadcasts (as expected):
1. Seed your database from main with `./scripts/clean_dev.sh` to see what the logs looks like when `turbo_broadcasts` are enabled (feel free to stop seeding after a few seconds as you'll get the idea very quickly)
2. Now Seed your database from this branch, ensure no `broadcasts` occur.
3. Ensure broadcasts still work on the website. This would include:
- `Last Updated` updates on the project listing index, sample listing index, and sample attachments.
- Running an export and watching the data exports listing table status update from `processing` to `ready`
- Running a workflow execution and …
=> Seeds: Prevent Turbo Broadcasts

Gemfile, Gemfile.lock, app/components/samples/table_component.html.erb, app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, app/models/sample.rb, app/views/groups/samples/index.html.erb, app/views/projects/samples/index.html.erb, lib/irida/search_syntax/ransack.rb, lib/irida/search_syntax/ransack_transformer.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR adds in support for searching the samples table by metadata field and value presence through the existing search box only when metadata has been toggled to be displayed.
Samples can be searched for by metadata using the following format `FIELD_NAME:FIELD_VALUE`, where the case does not matter for `field_name` or `field_value`.
Note: only string values can be searched for, a separate PR will ensure that we only store string values for metadata (#808 )
1. Run `bin/bundle` to install the gems required by this branch
2. Go to Project Samples page toggle …
=> Samples Table: Search by metadata field and value presence

app/components/attachments/dialogs/new_attachment_component.html.erb, test/system/groups/attachments_test.rb, test/system/projects/attachments_test.rb, test/system/projects/samples_test.rb
Fixes #790 
1. Upload a large file to a namespace
2. Verify that the upload button changes to "Uploading" and is disabled during upload.
3. Upload a large file to a group
4. Verify that the upload button changes to "Uploading" and is disabled during upload.
=> Fix upload dialog upload button for groups/project not disabling when uploading

app/services/samples/metadata/file_import_service.rb, test/fixtures/files/metadata/contains_empty_columns.csv, test/fixtures/files/metadata/contains_empty_header.csv, test/services/samples/metadata/file_import_service_test.rb, test/system/projects/samples_test.rb
A server error was thrown when importing files with empty headers. Empty headers are now ignored.
Fixes DFCT0010289.
Before:
After:
1. Navigate to a group samples page that the logged in user has access to update.
2. Hit the `Import Metadata` button.
3. Select a file that has empty headers.
4. Select the `Sample ID Column`.
5. Hit the `Import Metadata` button.
6. Verify the sample metadata was updated.
=> File import: Empty column fix

docs-site/docs/user/project/samples/sample-metadata.md, test/system/projects/samples_test.rb
This PR updates the metadata import documentation to include the new tsv file format and new `Import metadata` button on the groups page.
N/A
1. Build the docs
```
cd docs-site
pnpm update
pnpm build
npm run serve
```
2. Open a browser and navigate to [sample metadata](http://localhost:4000/irida-next/docs/user/project/samples/sample-metadata).
3. Read and verify the docs are accurate.
=> Docs: Update Metadata Import

Gemfile, Gemfile.lock
Removes `solargraph` gem to allow using latest version of `shopify.ruby-lsp` vscode extension.
See https://github.com/Shopify/ruby-lsp/issues/2282
Reference for ruby-lsp here https://shopify.github.io/ruby-lsp/rails-add-on.html
1. Go to extensions in vscode
2. Search for `ruby-lsp`
3. Install the latest version and enable auto updates
4. View an erb file after ruby-lsp is loaded and see that no errors are present
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and …
=> Developer Experience: Remove solargraph

app/components/project_dashboard/information_component.html.erb, app/controllers/groups_controller.rb, app/controllers/projects_controller.rb, app/models/member.rb, app/policies/group_policy.rb, app/policies/project_policy.rb, app/views/layouts/groups.html.erb
This PR fixes incorrect breadcrumbs for project and group activity page, fixes a bug with the settings menu opening, updates the project details page to show the count of members without automation bots, and updates the view_history policy methods to allow members of shared groups with access level >= MAINTAINER to view history items for a group and/or project.
=> Activity page fixes

test/components/previews/activity_component_preview.rb, test/components/previews/activity_component_preview/default.html.erb
Fixing the broken  activity component preview. 
Before:
After:
1. Navigate to `http://localhost:3000/rails/lookbook/inspect/activity/default`.
2. Verify the activity component preview loads.
=> Fix Activity Component Preview

app/controllers/dashboard/groups_controller.rb, app/controllers/groups_controller.rb, app/views/groups/subgroups/_index.html.erb, config/database.yml, test/system/dashboard/groups_test.rb, test/system/groups_test.rb
This PR fixes a bug where the expected flat list when filtering for groups (on dashboard and subgroups/projects) was not rendering properly.
Before:
Now:
On both dashboard groups and groups subgroups and projects
1. Use the search bar to filter down the list (filter with an overlapping name a group(s) and their subgroup(s)). 
2. Verify any groups that would have subgroups no longer has the dropdown to view its subgroups within, and that any subgroups that fit the filter are now listed.
=> Fix: Render flat list for groups when filtering

app/components/namespace_tree/namespace_tree_component.html.erb, app/components/namespace_tree/namespace_tree_component.rb, app/components/namespace_tree/row/row_contents_component.html.erb, app/components/namespace_tree/row/row_contents_component.rb, app/components/namespace_tree/row/without_children_component.html.erb, app/components/namespace_tree/row/without_children_component.rb, app/components/namespace_tree/row_component.rb, app/components/namespace_tree_container_component.rb, app/controllers/groups_controller.rb, app/views/groups/shared_namespaces/_index.html.erb, app/views/groups/show.html.erb, app/views/groups/subgroups/_index.html.erb, app/views/groups/subgroups/index.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/system/dashboard/groups_test.rb, test/system/groups_test.rb
This PR adds filtering to groups' shared groups and projects.
By name:
By PUID:
Search including projects:
1. Navigate to a groups' shared groups and projects tab (Bacillus has seeded shared groups)
2. Use the filter and filter by name and puid. Ensure filtering works as expected
=> Shared Groups: Filter

app/components/samples/table_component.html.erb, app/components/samples/table_component.rb, app/components/sort_component.html.erb, app/components/sort_component.rb, app/controllers/concerns/storable.rb, app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, app/models/sample/query.rb, app/views/groups/samples/_table.html.erb, app/views/groups/samples/index.html.erb, app/views/groups/samples/select.turbo_stream.erb, app/views/projects/samples/_table.html.erb, app/views/projects/samples/index.html.erb, app/views/projects/samples/select.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR refactors the Samples table to use ActiveModel to create a better search form for the Samples table, following this [guide](https://thoughtbot.com/blog/rails-search-form-tutorial).
This PR removes initial implementation of metadata searching as that will be reimplemented using SearchKick.
This is a prerequisite for changing to SearchKick.
2. Interact with Project and Groups Samples tables and ensure everything works as expected. The system tests should catch all cases. …
=> Feat: Sample::Query form object

.github/workflows/ruby.yml, Gemfile, Gemfile.lock, README.md, app/components/samples/table_component.html.erb, app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, app/models/sample.rb, app/models/sample/query.rb, app/services/samples/destroy_service.rb, config/initializers/pagy.rb, db/migrate/20241212164410_index_existing_samples.rb, db/schema.rb, db/seeds.rb, test/controllers/groups/samples_controller_test.rb, test/controllers/projects/samples_controller_test.rb, test/services/groups/destroy_service_test.rb, test/system/dashboard/groups_test.rb, test/system/dashboard/projects_test.rb, test/system/data_exports_test.rb, test/system/groups/samples_test.rb, test/system/groups_test.rb, test/system/projects/samples_test.rb, test/system/workflow_executions/submissions_test.rb, test/test_helper.rb
In preparation for searching samples via complex metadata criteria, this PR adds in Searchkick as a dependency which uses OpenSearch (An open source ElasticSearch alternative) to index our Samples including metadata which allows complex querying. This PR just updates the Sample model to include indexing and updates the existing Project and Group Samples table to use SearchKick to perform the existing searches.
1. Follow SearchKick/OpenSearch section in `README.md` to setup opensearch
Verify migration to index existing Samples
1. On `main` branch reset the …
=> Feat: Sample Searching using SearchKick (Part One)

app/models/sample.rb
Add in mappings section to SearchKick config for Samples which fixes issues with mapping types for metadata fields.
=> Fix searchkick mappings for metadata

app/models/sample.rb, db/seeds.rb
Update `string_template` template to exclude `metadata`.
Update `metadata_non_dates` template to use `keyword` instead of `text` so that string comparison where conditions can be used.
Update `db/seeds.rb` to disable Searchkick callbacks when adding data.
1. Reset the database.
2. Open a rails console and verify that the following searches produce results.
```
Sample.search("*", where: { "metadata.earliest_date": { lte: 1.day.ago } }).first
```
```
Sample.search("*", where: { "metadata.food": { like: "%Tofu%" } }).first
```
```
Sample.search("*", where: { …
```
=> Searchkick: Fix Sample metadata indexing part 2

test/services/samples/clone_service_test.rb, test/services/samples/create_service_test.rb, test/services/samples/destroy_service_test.rb, test/services/samples/transfer_service_test.rb
Updated service tests for samples services that update samples_count, to make it easier to read and ensure that count if updating correctly.
=> Tests: Simplify Samples services samples_count validations

app/javascript/controllers/inline_edit_controller.js, app/views/shared/samples/metadata/fields/_editing_field_cell.html.erb
Only update the metadata field if the enter or tab key is pressed.  Previously the field was save whenever the input was blurred
N/A
1. Login as user5 and go to a project or group that is owned and go to the samples page
2. Toggle on the metadata
3. Click on a metadata field and try to update the value pressing enter or tab
4. Click on a metadata field and begin to edit and then click away or press escape, the original value should return …
=>  Fix: Inline metadata edit, only update if enter or tab key pressed

app/models/metadata_template.rb, app/models/workflow_execution.rb, config/schemas/metadata_template_metadata.json, db/migrate/20250106153442_create_metadata_templates.rb, db/migrate/20250107194839_add_logidze_to_metadata_templates.rb, db/schema.rb, db/triggers/logidze_on_metadata_templates_v01.sql, test/fixtures/metadata_templates.yml, test/models/metadata_template_test.rb
Created the database model (and tests) for representing a Metadata Template
NONE
NONE
=> TASK: Create database model for representing a Metadata Template

app/controllers/concerns/workflow_execution_actions.rb, app/controllers/projects/workflow_executions_controller.rb, app/controllers/workflow_executions_controller.rb, app/policies/workflow_execution_policy.rb, app/services/workflow_executions/update_service.rb, config/locales/en.yml, config/locales/fr.yml, config/routes/project.rb, config/routes/workflow_executions.rb, test/controllers/projects/workflow_executions_controller_test.rb, test/controllers/workflow_executions_controller_test.rb, test/services/workflow_executions/update_service_test.rb
This PR updates/adds to the back-end (policy, services, controller) to allow the submitter of a personal workflow execution to update the name of a workflow execution post launch, as well as, allows a user with access level `ANALYST` or higher to update the name of an automated workflow execution post launch.
1. Verify that the tests pass
=> Back-end: Edit workflow execution name post launch

app/controllers/console_controller.rb, app/views/console/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/groups.html.erb, app/views/layouts/profiles.html.erb, app/views/layouts/projects.html.erb, config/environments/development.rb, config/routes/development.rb, docs-site/docs/configuration/options.md
Enables the built in rails web console when launching in development mode
* can see web pages change from db commits reflected live without needing to use another console or refresh the page.
* can run any code to trigger rdbg breakpoints without needing a corresponding web interaction
Functionality: 
* can only be visible when running in development mode
* by default, only shows on the `/console` endpoint
* changing `config.enable_web_console` to `true` in `config/environments/development.rb` will enable the console on every page
This checklist encourages us to confirm any changes have been analyzed to reduce risks in …
=> Quality of Life: Enable web console as a development option

Gemfile, Gemfile.lock, config/cable.yml
ActionCable postgresql adapter is limited to payloads up to 8000 bytes, this PR adds in a gem which allows larger payloads.
1. Run `bin/bundle` to install the gem
2. Run `bin/dev`
3. Create a Project with 90 samples in it.
4. Copy the Samples to an empty project.
5. Then attempt to copy the Samples again to the previously empty project.
6. On `main` this would result in a `ERROR:  payload string too long` message showing up in the good job logs, on this PR no error message occurs and the dialog is updated to show that it could not copy the samples.
This …
=> actioncable-enhanced-postgresql-adapter

app/components/viral/button_component.html.erb, app/javascript/controllers/inline_edit_controller.js, app/views/shared/samples/metadata/fields/_editing_field_cell.html.erb, config/locales/en.yml, config/locales/fr.yml, embedded_gems/pathogen/app/components/pathogen/button.html.erb, test/system/projects/samples_test.rb
On the samples page, a confirmation dialogue will open when a metadata field is being edited and the user clicks away from a **changed** value.  The user is presented with 2 options:
1. `Save`: Save the updated value and revert the cell to the un-editing state, displaying the new value.
2. `Discard`: Discard the updated value and revert the cell to the original value and render the unediting state.
1. Login as a user with privileges on a project (e.g. user5)
2. Go to a project the user owns, and then to the project samples page.
3. Toggle on metadata fields
4. …
=> Enhancement: Metadata edit confirmation dialog

app/components/spinner_component.html.erb, app/components/spinner_component.rb, app/controllers/concerns/file_import_actions.rb, app/jobs/samples/metadata_import_job.rb, app/services/samples/metadata/file_import_service.rb, app/views/groups/samples/metadata/file_imports/create.turbo_stream.erb, app/views/projects/samples/clones/create.turbo_stream.erb, app/views/projects/samples/metadata/file_imports/create.turbo_stream.erb, app/views/projects/samples/transfers/create.turbo_stream.erb, app/views/shared/samples/metadata/file_imports/_dialog.html.erb, app/views/shared/samples/metadata/file_imports/_errors.html.erb, app/views/shared/samples/metadata/file_imports/_success.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/previews/spinner_component_preview.rb, test/components/previews/spinner_component_preview/default.html.erb, test/components/spinner_component_test.rb, test/controllers/groups/samples/metadata/file_import_controller_test.rb, test/controllers/projects/samples/metadata/file_import_controller_test.rb, test/services/samples/metadata/file_import_service_test.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
Updates `FileImportActions` to enqueue a new `Samples::MetadataImportJob` which calls the existing `Samples::Metadata::FileImportService` to perform the queueing and the new job uses Turbo broadcasts to update the UI with success or errors.
1. Run the tests and ensure they pass
2. Ensure that samples metadata import works as expected. Verify that the error and success messages are displayed 
=> Async Metadata Import

app/models/sample/query.rb, test/fixtures/groups.yml, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/samples.yml, test/models/group_test.rb, test/system/groups/samples_test.rb
This is a fix for when a metadata field has a name with periods in it, no search results are returned.
1. Create a sample that has metadata with a period in the field name. 
1. Navigate to the samples page.
1. Click the `Advanced Search` button.
1. Select the search criteria using the metadata field name.
1. Click the `Apply Filter` button. 
1. Verify the table shows the sample. 
=> Fix for advanced search for metadata fields

test/system/dashboard/projects_test.rb, test/system/groups/samples_test.rb, test/system/projects/bots_test.rb, test/system/projects/samples_test.rb
This PR fixes a bunch of flaky tests.
=> Fix flaky tests

app/components/advanced_search_component.html.erb
Fixes dark mode for advanced search button when a search is active. 
Before:
After:
1. Navigate to a group or project samples page in dark mode. 
2. Filter samples via advanced search.
3. Verify the style of the `Advanced search` button.
=> Fix for advanced search button dark mode

app/components/advanced_search/value.html.erb, app/components/advanced_search_component.html.erb, app/javascript/controllers/advanced_search_controller.js, app/models/sample/query.rb, app/validators/advanced_search_group_validator.rb, app/views/groups/samples/_table_filter.html.erb, app/views/projects/samples/_table_filter.html.erb, test/components/previews/advanced_search_component_preview.rb, test/system/groups/samples_test.rb
The PR adds the ability to search for metadata fields that exists and not exists.
Exists:
Not exists:
1. Navigate to a group or project samples page.
1. Click the Advanced Search button. 
1. Verify the Advanced Search dialog opened.
1. Select a field and `exists` or `not_exists` operator to filter by.
1. Click the Apply Filter button.
1. Verify the table displays the correct search results.
=> Advanced Search: Adding new 'exists' and 'not_exists' operators

app/javascript/controllers/viral/dialog_controller.js, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
Previously the Dialog Component would set `openValue` to false on `disconnect` (fired on page navigation), which resulted in a weird rendering issue if you opened a dialog then clicked the `back` button and then clicked the `forward` button. The dialog would render but it would be incorrectly.
Now when you click back and then forward, while a dialog is open it will no longer be open on forward navigation.
=> Fix: Dialog Component now closes on disconnect

app/models/sample.rb
Due to the dynamic nature of metadata I have updated the total field limit from 1000 to 10000 for Samples. Since a metadata field that is not a data field is indexed 2 different ways it counts as 2 fields to the limit. With this change we allow support for up to ~4990 unique non date metadata fields to be indexed.
1. Navigate to http://localhost:9200/_list/indices to find the index starting with `samples_development`
2. Check `http://localhost:9200/INDEX_NAME/_settings` for `total_fields` which should not show up
3.  Run `bin/rails db:reset` and then repeat …
=> Searchkick: Increase total field limit to 10000 for Samples

app/models/sample/query.rb, test/fixtures/groups.yml, test/fixtures/members.yml, test/fixtures/namespaces/project_namespaces.yml, test/fixtures/projects.yml, test/fixtures/routes.yml, test/fixtures/samples.yml, test/fixtures/users.yml, test/system/projects/samples_test.rb
Fixed searching float values. 
1. Navigate to a sample page that you have access to modify.
1. Add a new metadata field with a value that contains a decimal.
1. Navigate to the samples table page of the recently modified sample. 
1. Click the Advanced Search button. 
1. Verify the Advanced Search dialog opened.
1. Select the new field, a between operator and value to filter by.
1. Click the Apply Filter button.
1. Verify the table displays the correct search results.
=> Fix for filtering floats via advanced search 

app/models/sample/query.rb
This PR implements native advanced search using AREL. To toggle this and skip Searchkick for advanced search you need to set `RANSACK_ONLY_SEARCH=true` in your env before running rails commands
Note: The plan with this PR is to deploy changed to DEV and have QA team compare results and functionality with TEST that will still use Searchkick. Once QA team signs off, a follow up PR with happen to refactor code to be more readable and to remove Searchkick references.
1. Launch server with the following command `RANSACK_ONLY_SEARCH=true bin/dev`
2. Navigate to a …
=> Native Advanced Search

app/models/sample/query.rb
Number regex was previously only matching positive numbers with at least 2 digits, this pr updates the regex to match numbers that are single digits as well as numbers that are prefix with `-` indicating that they are negative.
Date regex was previously only matching `YYYY-MM-DD`, this PR updates the regex to match partial dates as well (e.g. `YYYY`, `YYYY-MM`, or `YYYY-MM-DD`)
1. Run server with `RANSACK_ONLY_SEARCH=true bin/dev` or `env RANSACK_ONLY_SEARCH=true bin/dev` (if using zsh or fish)
2. Create a Project
3. In the Project create a sample and add a …
=> Fix: Number and Date regex in native advanced search

app/components/nextflow_component.html.erb, app/javascript/controllers/nextflow/samplesheet_controller.js
This PR adds/fixes a couple things that differ between local and QA environments:
- The samplesheet submission will now check `status == '200'` rather than `statusText == 'OK'`
- A loading overlay will be present while the sample table is being loaded in. This is to avoid weird rendering for large sample requests.
1. Verify you can still submit a workflow with the correct parameters.
=> Nextflow Samplesheet: Bug Fixes (submission and table load)

app/components/metadata_templates/table_component.html.erb, app/components/metadata_templates/table_component.rb, app/controllers/concerns/metadata_template_actions.rb, app/controllers/groups/metadata_templates_controller.rb, app/controllers/projects/metadata_templates_controller.rb, app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js, app/views/groups/metadata_templates/edit.turbo_stream.erb, app/views/groups/metadata_templates/update.turbo_stream.erb, app/views/projects/metadata_templates/edit.turbo_stream.erb, app/views/projects/metadata_templates/update.turbo_stream.erb, app/views/shared/metadata_templates/_edit_template_dialog.html.erb, app/views/shared/metadata_templates/_update.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/fixtures/metadata_templates.yml, test/system/groups/metadata_templates_test.rb, test/system/projects/metadata_templates_test.rb, test/system/projects/samples_test.rb
This PR adds in the UI to edit metadata templates for projects and groups.
**Edit template dialog only enables the submit button when fields are added to the selected list and the name has a required attribute..however if a user tries to bypass these via inspect element the errors are caught and displayed in an alert:**
1. Login as `admin@email.com`
2. Follow the instructions in https://github.com/phac-nml/irida-next/pull/923 to create a template
3. From the metadata templates listing, click `Edit` for the template
4. Verify that the `available` list doesn't …
=> UI: Edit Metadata Template 

app/models/sample/query.rb
Updates the `!=` and `not_in` operators to include nil values in results.
1. Run server with native searching enabled `RANSACK_ONLY_SEARCH=true bin/dev` or `env RANSACK_ONLY_SEARCH=true bin/dev`
2. Create a Project
3. Create a 2 Samples in the Project
4. Add a `age` field with value `80` to one of the samples
5. Filter by `metadata.age != 80` confirm that the sample without a value for age is present
6. Filter by `metadata.age not_in 80` confirm that the sample with a value for age is present
This checklist encourages us to confirm any changes have been analyzed …
=> Native Advanced Search: Include nil values in results for != and not_in operators

app/components/advanced_search_component.html.erb, app/components/viral/dialog/header_component.html.erb, app/components/viral/dialog/header_component.rb, app/components/viral/dialog_component.rb, app/helpers/class_name_helper.rb, app/javascript/controllers/advanced_search_controller.js, app/views/groups/samples/_table_filter.html.erb, app/views/projects/samples/_table_filter.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/advanced_search_component_test.rb, test/components/previews/advanced_search_component_preview.rb, test/components/viral/system/data_table_component_test.rb, test/helpers/class_name_helper_test.rb, test/system/projects/samples_test.rb, test/system/workflow_executions/submissions_test.rb
This PR adds the ability to close the Advanced Search dialog. Which closes the dialog immediately if the filters have already been applied, or prompts the user to confirm that they want to close if filters have been modified and have not yet been applied.
Before:
After:
After clicking close, when filters have been modified and not yet applied:
1. Launch the server and sign in with your user of choice
2. Navigate to a Project of your choice
3. Click on the Samples context menu item
4. Click on `Advanced Search`
5. Click the `X` close button on the dialog. …
=> Add close button to Advanced Search dialog

app/controllers/workflow_executions/submissions_controller.rb, test/controllers/workflow_executions/submission_controller_test.rb
This PR fixes a bug where metadata fields weren't rendering on nextflow samplesheet
1. In `config/pipelines/pipelines.json`, add the `fastmatch` pipeline:
```
{
"url": "https://github.com/phac-nml/fastmatchirida",
"name": "phac-nml/fastmatchirida",
"description": "IRIDA Next Fast Match Pipeline",
"versions": [
{
"name": "0.1.0"
}
]
}
```
2. Restart your server
3. Navigate to any project or group with samples that have metadata and select some samples.
4. Start a fastmatch workflow
5. On the metadata tabs, verify the project/group's metadata fields appear in the dropdowns.
6. Select one of the metadata fields, and verify the samples' metadata value is automatically populated
This checklist …
=> Fix: Nextflow Metadata Fields

app/components/nextflow_component.html.erb, app/controllers/workflow_executions_controller.rb, app/javascript/controllers/nextflow/samplesheet_controller.js, app/models/samples_workflow_execution.rb, app/models/workflow_execution.rb, app/validators/workflow_execution_samplesheet_params_validator.rb, app/views/workflow_executions/create.turbo_stream.erb, config/application.rb, config/locales/en.yml, config/locales/fr.yml, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/attachments.yml, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/graphql/workflow_executions_query_test.rb, test/models/samples_workflow_executions_test.rb, test/models/workflow_execution_test.rb, test/services/workflow_executions/create_service_test.rb, test/system/workflow_executions_test.rb
This updates the WorkflowExecution model to validate that the workflow exists as specified by `metadata['workflow_name']` and `metadata['workflow_version']`, additionally this refactors and reenables the SamplesWorkflowExecution `samplesheet_params` validation.
These validation errors should really only be producible by using the submitWorkflowExecution mutation from the graphql API.
Submissions through the UI should not be able to produce these errors as we automatically set most of the params, or restrict input to valid items (e.g. attachments specific to the sample and regex).
Submitting a workflow execution via graphql with missing …
=> Workflow Executions: Workflow and Samplesheet validation

app/components/viral/sortable_list/list_component.html.erb, app/components/viral/sortable_list/list_item_component.html.erb, app/components/viral/sortable_list/list_item_component.rb, app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js, app/views/data_exports/_new_linelist_export_dialog.html.erb
Currently, if a metadata template has fields that do not exist within the metadata fields on a project that field was ignored.  Now you can export that field
"favourite sport" was added to the template, but does not exist in the project.
=> Fix: Allow template fields that are not within the sample metadata to be exported

app/components/activities/list_item_component.html.erb, app/components/activities/list_item_component.rb, app/components/activities/member_activity_component.html.erb, app/models/concerns/track_activity.rb, app/models/group.rb, app/models/namespaces/project_namespace.rb, app/services/members/create_service.rb, app/services/members/destroy_service.rb, app/services/members/update_service.rb, config/locales/en.yml, config/locales/fr.yml, db/migrate/20250219001422_add_user_email_to_member_activities.rb, db/migrate/20250219172718_move_member_activities_to_namespace.rb, db/schema.rb, test/components/activity_component_test.rb, test/components/members/member_activity_component_test.rb, test/fixtures/activities.yml
This PR refactors the members activities to now be attached to the namespace rather than of type `Member`. This will prevent member activity loss if a member is permanently deleted
Create/update/destroy members for a group and project Ensure the correct activity is listed for each and links to the members page are only clickable within the activity item if the user hasn't been removed
Try this out on main with an existing db and then switch over to this branch and run the migrations. Ensure the activities still display correctly …
=> Refactor member activities

.github/workflows/trigger-azure-devops.yml
- Creates a new Github Action that on new pushes to `main`, triggers an Azure DevOps pipeline.
- This will allow us to use our existing Azure DevOps build pipeline to automatically build IRIDA Next docker containers for NML use.
- The pipeline will only run if the repository owner is `phac-nml`
- The following secrets were added:
```
DEVOPS_PAT
PIPELINE_NAME
PROJECT_URL
```
=> Create Github action to trigger an Azure DevOps pipeline on new pushes to main

db/migrate/20250219001422_add_user_email_to_member_activities.rb
1. checkout irida next from a git hash before the migration, build db
```bash
git checkout 6facd06a29c38cdb80012367dcf7dbc07a250a5d
./scripts/clean_dev.sh
```
2. run irida next
3. create a new user "myuser"
4. sign out
5. sign in with admin
6. create a new group/project
7. add "myuser" to group/project
8. sign out of admin
9. sign in with "myuser"
10. delete "myuser" from edit profile page
11. sign in with admin
12. check that user "myuser" is no longer a member of group/project
13. checkout this PR branch and migrate
```bash
git checkout …
```
=> HOTFIX update member activity migration to handle deleted users

app/models/samples_workflow_execution.rb, app/services/workflow_executions/completion_service.rb, test/fixtures/samples_workflow_executions.yml, test/fixtures/workflow_executions.yml, test/services/workflow_executions/completion_service_test.rb
Currently a WorkflowExecution can get stuck on `completing` if a User deletes one of  Sample used in the analysis after it has been `prepared` and before it enters `completing` state.
2. Create a new Project
3. Create a new Sample in the newly created sample
4. Upload pairend fastq files to the sample
5. Launch an `phac-nml/iridanextexample` pipeline with the newly created sample
* Select `Update samples with analysis results`
6. After Workflow Execution changes to `prepared`
7. Navigate back to Project and delete the newly created sample
8. …
=> Fix: Workflow Executions stuck on completing when sample is deleted during execution

app/javascript/application.js
`Turbo.setConfirmMethod(confirmMethod)` is set to be deprecated in the next release of Turbo.  This updates it to the new method of `Turbo.config.forms.confirm = confirmMethod`
Login as users and go to a project that is owned.
Try to delete a sample from the project samples page.
Confirmation dialog should load as expected
Ensure tests pass.
=> Fix: Replaces deprecated Turbo confirm method

app/components/nextflow/samplesheet/header_component.html.erb, app/components/nextflow/samplesheet/header_component.rb
This updates the Nextflow Samplesheet HeaderComponent to render with a minimum width that ensures displays of most common metadata field params (e.g. metadata_X)
This also fixes the option generator for the metadata fields to not include metadata params from other metadata columns (see screenshots below).
Before:
After:
1. Create `development.json` inside of `config/pipelines.json` if it does not exist
2. Add the SNVPhyl pipeline to `development.json` if it doesn't already exist inside
```json
{
"url": "https://github.com/phac-nml/snvphylnfc",
"name": …
```
=> Fix: Rendering of Metadata Field selection in Nextflow Samplesheet

app/policies/group_policy.rb, app/policies/project_policy.rb, test/fixtures/routes.yml, test/system/groups_test.rb, test/system/projects_test.rb
This PR updates the logic so that a user with access level `uploader` gets an access denied message (instead of an error message) when attempting to do an action (e.g. access a project or group that they are a member of)
1. Create a project and add a user with access level `uploader`
2. Logout and login as this user, and try to access the project. You should get an access denied error page
3. Repeat 1 and 2 for a group
4. Verify the tests pass
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, …
=> Fix: Uploader UI access error

app/services/samples/metadata/update_service.rb, app/services/workflow_executions/completion_service.rb, test/services/samples/metadata/update_service_test.rb
Metadata fields should update & lock after a pipeline runs, even if the value does not change.
STRY0017322
N/A
1. Select a sample. Preferably with no metadata.
2. Run a pipeline with `Update samples with analysis results` selected.
3. Verify the results metadata have been added to the sample.
4. Repeat step 2.
5. Verify the results metadata have been updated within the sample.
=> Workflow execution: Update and lock metadata

app/services/automated_workflow_executions/launch_service.rb, app/views/projects/workflow_executions/_samplesheet.html.erb, app/views/projects/workflow_executions/show.html.erb
Prior to this PR, any automated pipeline would only launch with `sample`, `fastq_1`, and `fastq_2` as entries in the samplesheet. With this PR, if a workflow has the column named `sample_name` in the samplesheet we will add that as a field.
Additionally this PR adds the `samplesheet` tab to Project Workflow Executions table, which makes it easier to verify that the field is present.
1. Add a pipeline to your `config/pipelines/development.json` that has `sample_name` in the samplesheet schema (E.g. mikrokondo)
```json
{
"url": …
```
=> Automated workflow execution launch service set sample name in samplesheet params if required

app/components/samples/editable_cell.html.erb, app/components/samples/table_component.html.erb, app/components/samples/table_component.rb, app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, app/javascript/controllers/inline_edit_controller.js, app/javascript/controllers/projects/samples/metadata/editable_cell_controller.js, app/views/groups/samples/_table.html.erb, app/views/projects/samples/_table.html.erb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR updates the samples table component to display editable metadata cell using an abilities check (set once) rather than checking permission for each cell, and updates samples controllers to include the namespace parent for each sample to cut down on queries
The metadata editable cells have also been refactored so fewer DOM elements are loaded into the table.
**On main:**
1. Create a project, and 100 samples with ~20 pieces of metadata each
2. Visit the project samples page, and change to displaying 100 samples and showing all metadata fields
3. Inspect …
=> Samples table speedup

app/components/viral/sortable_list/list_component.html.erb, app/components/viral/sortable_list/list_item_component.html.erb, app/components/viral/sortable_lists_component.html.erb, app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js, config/locales/en.yml, config/locales/fr.yml, test/system/data_exports_test.rb
This PR adds accessibility to the sortable lists component, enabling keyboard commands to be usable with the lists.
[Screencast from 2025-03-24 04:19:37 PM.webm](https://github.com/user-attachments/assets/676a93ef-b742-425f-9c5b-132ddc81dbdd)
1. Navigate to any dialog with the sortable lists (like creating a linelist export).
2. Tab into the metadata list, and use the keyboard to move the items around.
3. Up/Down to navigate up and down the list, Left/Right to navigate between lists, and Space/Enter to select/de-select an item.
=> Sortable Lists Accessibility Improvements

app/models/concerns/file_selector.rb
This PR fixes a bug where when a user uploads multiple sets of PE files to a sample in a single upload, the nextflow samplesheet didn't properly select a pair. This sometimes happens as the PE files getting attached to the sample out of order. eg if you upload 2 sets of PE files (pe1 and pe2), they could be attached to the sample in order of [pe1-fwd, pe2-fwd, pe2-rev, pe1-rev]. The samplesheet then pulls the most recent fwd and rev attachments, resulting in pe2-fwd/pe1-rev being default selected.
Now when building the files hash in `concerns/file_selector`, we go through `single` and `forward` attachments, and when a `forward` attachment is encountered, we retrieve its `.associated_attachment` to ensure pairs are listed at the same index.
[Screencast from 2025-04-02 10:57:03 …
=> Bug: Samplesheet Default PE file selection

app/views/groups/workflow_executions/_attachment.html.erb, app/views/groups/workflow_executions/_attachment_actions.html.erb, app/views/groups/workflow_executions/_files.html.erb, app/views/projects/workflow_executions/_attachment.html.erb, app/views/projects/workflow_executions/_attachment_actions.html.erb, app/views/projects/workflow_executions/_files.html.erb, config/locales/en.yml, config/locales/fr.yml, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/attachments.yml, test/system/groups/workflow_executions_test.rb, test/system/projects/workflow_executions_test.rb
Updated workflow executions for project & groups to enable preview of pipeline result files, like it is currently enabled for user workflow executions.
Workflow execution files that are shared with a project::
Workflow execution files that are shared with a group:
1. Setup a pipeline that produces output files that can be previewed.
1. Follow the instructions from [PR895](https://github.com/phac-nml/irida-next/pull/895), to test workflow executions shared with a project.
1. Follow the instructions from [PR948](https://github.com/phac-nml/irida-next/pull/948), to test workflow executions shared with a group.
1. Navigate to the workflow execution and click the `Files` tab.
1. Verify there is a new `Actions` column. Click the `Preview` link.
1. Verify the pipeline output files can be …
=> Add file preview to workflow execution files for project & groups

app/components/nextflow/samplesheet_component.html.erb, app/javascript/controllers/nextflow/samplesheet_controller.js, app/views/workflow_executions/file_selector/_file_selector_dialog.html.erb, test/system/workflow_executions/submissions_test.rb
This PR is for [STRY0017589](https://publichealthprod.service-now.com/rm_story.do?sys_id=a4b0d3f13b2c6a10d0d23a0eb3e45aee) to improve the nextflow dialog.
File cell focus was fixed in [PR1008](https://github.com/phac-nml/irida-next/pull/1008).
In this PR, the actual file selector modal has been improved:
- Submit button now displays focus indicator
- Filenames are now labels for their associated radio button, and clickable to select.
1. Navigate to a project.
2. Select a sample and add extra PE files to it.
3. Launch the `iridanextexample` workflow with this sample
4. Click a file cell for this sample.
5. In the file selector dialog, verify:
- Tab through and make sure the submit button highlights when focused.
- Clicking the filename selects that file. …
=> Nextflow: Improve File Selector Accessbility

app/components/viral/data_table_component.html.erb, app/javascript/controllers/projects/samples/complete_controller.js, app/javascript/controllers/spreadsheet_import_controller.js, app/jobs/samples/batch_sample_import_job.rb, app/services/samples/batch_file_import_service.rb, app/views/groups/samples/index.html.erb, app/views/groups/samples/spreadsheet_imports/create.turbo_stream.erb, app/views/groups/samples/spreadsheet_imports/new.turbo_stream.erb, app/views/projects/samples/index.html.erb, app/views/projects/samples/spreadsheet_imports/create.turbo_stream.erb, app/views/projects/samples/spreadsheet_imports/new.turbo_stream.erb, app/views/shared/samples/spreadsheet_imports/_dialog.html.erb, app/views/shared/samples/spreadsheet_imports/_errors.html.erb, app/views/shared/samples/spreadsheet_imports/_success.html.erb, config/locales/en.yml, config/locales/fr.yml, db/seeds.rb, test/fixtures/files/batch_sample_import/project/invalid_duplicate_header.csv, test/services/samples/group_batch_sample_import_service_test.rb, test/services/samples/project_batch_sample_import_service_test.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
* Adds "Import samples" button to Project Samples and Group Samples pages.
* Adds form for importing samples, similar to the Import metadata form
* includes form field filtering to prevent duplicate headers being selected
* Connect turbo streams for progress bars, errors, success, etc
* Features are behind `Flipper.enable(:batch_sample_spreadsheet_import)`
Note: Metadata importing alongside sample importing will be in a separate PR
1. Start irida next, sign in, navigate to a project where you have permissions to create samples.
2. Click the [Import samples] …
=> Batch Sample Import Form WebUI

app/components/data_exports/table_component.html.erb, app/components/nextflow_component.html.erb, app/components/spinner_component.html.erb, app/components/spinner_component.rb, app/javascript/controllers/nextflow/samplesheet_controller.js, test/components/spinner_component_test.rb, test/system/groups/metadata_templates_test.rb, test/system/groups/samples_test.rb, test/system/projects/metadata_templates_test.rb, test/system/projects/samples_test.rb, test/system/workflow_executions/submissions_test.rb
This PR refactors the spinner component to receive an optional ID rather than setting a default ID. This required fixing as there are instances in the DOM where multiple spinner components are present, with overlapping IDs
1. Verify tests pass locally
=> Refactor Spinner Component ID

app/assets/icons/heroicons/ellipsis_horizontal.svg, app/assets/tailwind/application.css, app/components/layout_component.html.erb, app/components/viral/breadcrumb_component.html.erb, app/components/viral/dropdown/item_component.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/viral/breadcrumb_component_test.rb
Added a hover & collapsible (on zoom) state to breadcrumbs.  
STRY0017584
Without Zoom:
With Zoom:
1. Navigate to any page with breadcrumbs.
2. Verify the links are underlined on hover.
3. Zoom in 400%.
4. Verify the breadcrumb parent items collapse into a `...` icon button with dropdown.
=> Accessibility: Add hover to breadcrumbs

app/views/projects/samples/metadata/_form.html.erb
This fixes the styling of the input fields in the `Add Metadata` dialog that started to look funky after removing majority of focus overrides from the app.
Before:
After:
=> Fix: Samples Add Metadata Dialog styling

app/assets/tailwind/application.css, app/components/nextflow/samplesheet/header_component.html.erb, app/components/nextflow/samplesheet_component.html.erb
Prior to this PR, focus outline was not visible for file selector link or metadata input field in firefox. Now focus is indicating correctly.
2. Navigate to a Project of your choice that you can run an analysis on
3. Select a pipeline with both file inputs and metadata inputs
4. Tab through the page and ensure that focus is visible
=> Fix: Samplesheet File selector and Metadata input box focus

app/components/advanced_search/condition.html.erb, app/components/advanced_search/condition.rb, app/components/advanced_search/group.html.erb, app/components/advanced_search/group.rb, app/components/advanced_search_component.html.erb, app/components/advanced_search_component.rb, app/controllers/concerns/metadata.rb, app/views/groups/samples/_table_filter.html.erb, app/views/projects/samples/_table_filter.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/advanced_search_component_test.rb, test/components/previews/advanced_search_component_preview.rb, test/components/previews/advanced_search_component_preview/default.html.erb, test/controllers/concerns/metadata_concern_test.rb, test/system/groups/bots_test.rb, test/system/projects/bots_test.rb, test/system/projects/samples_test.rb
- The metadata keys should not be prefixed with `metadata.*`.
- There should be a new metadata section within the fields dropdown that lists all the metadata fields.
- The sample fields within the fields dropdown should be localized.
- The operator dropdown should be localized.
STRY0017732
Light mode:
Dark mode:
Please see https://github.com/phac-nml/irida-next/pull/887 for instructions on how to test the advanced search feature. 
=> Advanced search: Add sections to field dropdown

app/services/samples/create_service.rb, app/services/samples/destroy_service.rb, db/migrate/20250416191422_recalculate_group_samples_count.rb, db/schema.rb, test/controllers/projects/samples_controller_test.rb, test/services/samples/create_service_test.rb
A bug was found where if an error occurred during sample creation, the associated group sample count would still increment.
Test the issue on `main` first
1. Create a group then create a project under that group
2. Create a new sample, then create another sample with the same name. You should get a same name error and the second sample should not be created
3. Navigate back to project samples to verify only your first sample exists
4. Navigate to the groups dashboard. Your group should have a samples_count of 2
Test the fix on this branch
5. Repeat the above with a new group/project/samples. On the group's dashboard, the samples_count should only be 1.
This checklist encourages us to confirm …
=> Bug: Create sample error increasing samples count

app/controllers/concerns/workflow_execution_actions.rb, app/controllers/workflow_executions_controller.rb, app/views/workflow_executions/_edit_dialog.html.erb, app/views/workflow_executions/_summary.html.erb, config/locales/en.yml, config/locales/fr.yml, test/controllers/workflow_executions_controller_test.rb, test/system/workflow_executions_test.rb
Added the ability to share/unshare pipeline results post run.
STRY0017632 & STRY0017633
Please see https://github.com/phac-nml/irida-next/pull/948 & https://github.com/phac-nml/irida-next/pull/895 for  instructions on how to share pipeline results with group & project members.
To share/unshare pipeline results post run:
1. Select `Workflow Executions` from the `Go To` side menu .
2. Click on the ID of the workflow execution which was just launched.
3. Verify if the results are shared within the `Summary` section.
4. Click on the `Edit` button on the top right.
5. Check or uncheck share results.
6. Click Submit.
=> Share & unshare pipeline results post run

app/javascript/controllers/metadata_template_dd_controller.js, app/views/shared/samples/_metadata_template_dropdown.html.erb, app/views/shared/samples/_metadata_template_item.html.erb, app/views/shared/samples/_metadata_templates_list.html.erb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
Fixes issue where the metadata template dropdown was inaccessible and did not close when the button was pressed a second time.
- Replaced the metadata template dropdown with a proper flowbite dropdown
- Replace the radio buttons with actual buttons, a checkmark shows the selected value
1. Go to a project samples page
2. If there are no templates create on in the project settings
3. Try toggling all types of templates (all fields, no fields, and random templates) …
=> Updated sample metadata template dropdown to act like a normal dropdown

app/controllers/groups/samples_controller.rb, app/controllers/projects/samples_controller.rb, config/initializers/pagy.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR updates pagy to redirect to the first page if a `Pagy::OverflowError` is encountered for the project and group samples tables.
[Screencast from 2025-04-24 15-36-24.webm](https://github.com/user-attachments/assets/306b0e2f-92c2-4888-b050-f7ff57b57ad7)
[Screencast from 2025-04-24 15-34-47.webm](https://github.com/user-attachments/assets/66b051de-6968-4c93-a799-f4467948cd5d)
**On Main:**
1) Go to a group which has > 20 samples
2) From the first page of the group samples table, copy a sample PUID
3) Go to another page in the samples table
4) In the search …
=> Fix: Pagy OverflowError

app/javascript/controllers/spreadsheet_import_controller.js, app/views/shared/samples/spreadsheet_imports/_dialog.html.erb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR fixes a rebase issue from `main`
Re-test using the instructions from [PR1031](https://github.com/phac-nml/irida-next/pull/1031)
Also fixed when a file is selected then de-selected, select options are properly disabled and display the blank/default values. This seems to be specifically with Chrome as Firefox when cancelling file selection, will keep the previously selected file.
=> Fix: Batch Sample Import Rebase

.vscode/settings.json, app/components/nextflow/samplesheet_component.html.erb, app/components/pagination_component.html.erb, app/components/viral/pagy/limit_component.html.erb, app/components/viral/pagy/pagination_component.html.erb, app/components/viral/pagy/pagination_component.rb, config/locales/en.yml, config/locales/fr.yml, test/components/pagination_component_test.rb, test/components/viral/pagy_full_component_preview_test.rb, test/components/viral/pagy_pagination_component_preview_test.rb, test/system/dashboard/projects_test.rb, test/system/groups/members_test.rb, test/system/groups/metadata_templates_test.rb, test/system/projects/members_test.rb, test/system/projects/metadata_templates_test.rb, test/system/workflow_executions_test.rb
Addresses [STRY0017760](https://publichealthprod.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3D70e6c613337ce21061dd45659d5c7bc7)
- Updated `limit_component.html.erb` to include ARIA labels for dropdown items, improving screen reader support.
- Enhanced `pagination_component.html.erb` with specific ARIA labels for pagination controls, ensuring better navigation for users with disabilities.
- Modified `en.yml` and `fr.yml` to add new translations for ARIA labels, providing a localized experience for users. …
=> Enhance accessibility for pagy components with ARIA labels

app/services/base_spreadsheet_import_service.rb, config/locales/en.yml, config/locales/fr.yml, test/fixtures/files/metadata/malformed.csv, test/services/samples/metadata/file_import_service_test.rb
It appears that a user tried importing a file with a combination of different line endings, causing the file to be malformed.
The accepted EOL characters:
- Windows uses carriage return and line feed ("\r\n") 
- Macintosh uses just carriage return ("\r")
- Unix uses just line feed ("\n")
This PR displays an error message when the imported file is malformed.
STRY0016977
1. Navigate to a samples page that the logged in user has access to update.
2. From the `Sample Actions` dropdown, under the `Import` section, hit the `Import Metadata` button.
3. Select a file that has a combination of different line endings. (Verify with Notepad++ or `cat -e`)
4. Select the `Sample ID Column`.
5. Hit the `Import Metadata` button.
6. Verify the sample metadata updated successfully.
=> Fix for importing malformed files

app/controllers/groups/samples_controller.rb, app/views/groups/samples/index.html.erb, test/system/groups/samples_test.rb
This PR changes a couple items on the group samples page:
- Hides `Sample Actions` dropdown if the group has no projects associated with it (because the user can't import samples or use any other action)
- Renders the sample table (ie: empty state message).
- Renders the select/de-select samples and filter/search actions based on if projects are present. This is due to `Advanced Search` requiring at least 1 project present to pass validation
1. Create a new group, a subgroup (subgroup 1) within the group, and then another subgroup (subgroup 2) within subgroup 1.
2. Create a project in the top level Group
3. Navigate to a group with at least a project that you have maintainer/owner access, and …
=> Fix: Group Samples Index

app/components/viral/avatar_component.rb
When multiple web servers are running, the avatar colour can change as the `.hash` method on a string does not produce reproducible results. This updates it to use md5 which will generate reproducible results.
1. Checkout this branch
2. Run `bin/rails db:reset`
3. Start server
4. Login as `user1@email.com`
5. Navigate to http://localhost:3000/rails/lookbook/inspect/viral_avatar/default and confirm colour matches screenshot
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and …
=> Fix: Avatar colour consistency

app/components/activities/dialogs/activity_list_dialog_component.rb, app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb, app/components/activities/dialogs/activity_table_listing_dialog_component.rb, app/components/activities/groups/sample_activity_component.html.erb, app/components/activities/groups/sample_activity_component.rb, app/components/activities/list_item_component.rb, app/components/activities/projects/sample_activity_component.html.erb, app/components/activities/projects/sample_activity_component.rb, app/controllers/activities_controller.rb, app/javascript/controllers/activities/extended_details_controller.js, app/models/concerns/track_activity.rb, app/services/samples/batch_file_import_service.rb, config/locales/en.yml, config/locales/fr.yml, test/components/activities/dialogs/activity_list_dialog_component_test.rb, test/components/activities/dialogs/activity_table_listing_dialog_component_test.rb, test/components/projects/sample_activity_component_test.rb, test/fixtures/activity_extended_details.yml, test/fixtures/extended_details.yml, test/fixtures/files/batch_sample_import/group/valid_with_multiple_project_puids.csv, test/fixtures/public_activity/activities.yml, test/services/samples/group_batch_sample_import_service_test.rb, test/services/samples/project_batch_sample_import_service_test.rb
This PR extends the activities created from performing sample imports
Project Import:
Group Import:
1. Navigate to a project that you can import samples
2. Upload `test/fixtures/files/batch_sample_import/project/valid.csv`
3. Import the samples, and verify the activity displays as expected
4. Create a group with two projects
5. Open `test/fixtures/files/batch_sample_import/group/valid.csv` and replace the project puids with each project (so each project has 1 sample assigned)
6. On the group samples page, import the above csv
7. Verify the group activities lists the two samples with the correct associated project
8. Navigate to each of the 2 project's activity pages, and verify each activity contains only the sample corresponding to that project based on the csv
This checklist encourages …
=> Batch Sample Import: Extend Activities

app/components/namespace_tree/row/row_contents_component.html.erb, app/components/namespace_tree/row/row_contents_component.rb, app/controllers/concerns/workflow_execution_actions.rb, app/helpers/namespace_helper.rb, app/helpers/namespace_path_helper.rb, app/views/workflow_executions/_summary.html.erb, config/locales/en.yml, config/locales/fr.yml, test/system/workflow_executions_test.rb
After #1036, it was requested that we display the name of the group/project that the workflow was run from.
STRY0017999
1. Run a workflow execution. 
1. Click on the ID of the workflow execution which was just launched.
1. Verify the Group/Project is displayed on the summary page.
=> Workflow Executions: Display namespace on summary page

app/components/samples/table_component.html.erb, app/components/samples/table_component.rb, config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml, test/components/samples/table_component_test.rb
Fix for sorting the project column of the group samples table.
Fixes #833.
https://github.com/user-attachments/assets/4e325bdd-16db-4735-a738-712182a2ff1b
1. Navigate to a group samples page.
2. Verify the sort works on the `Project` column.
=> Fix for sorting samples table by project column

app/jobs/data_exports/create_job.rb, config/locales/en.yml, config/locales/fr.yml, docs-site/docs/user/project/samples/sample-metadata.md, test/jobs/data_exports/create_job_test.rb, test/system/groups/samples_test.rb
This PR updates the samples table listing `Sample ID` column to `Sample PUID` and updates the metadata import and advanced search dialogs to use `Sample PUID` so that there is consistent referencing. This address [STRY0017530](https://publichealthprod.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3D19ef87af3b1c62105c163064c3e45ad3)
1. Verify the samples advanced search lists the sample puid
2. Verify the sample attachments table header displays PUID
3. Verify data exports -> spreadsheet export headers include `Sample PUID` and `Project …
=> Consistent reference for Sample ID

app/views/projects/samples/deletions/_new_deletion_dialog.html.erb, app/views/projects/samples/show.html.erb, config/locales/en.yml, config/locales/fr.yml, test/system/dashboard/projects_test.rb, test/system/projects/samples_test.rb
Fixes sample selection after a sample is deleted from a show page.
Fixes #652.
https://github.com/user-attachments/assets/ddc0f8f0-c9eb-4f9c-8e41-24f7081eb88e
1. Create some samples within a project.
2. Select all samples.
3. Click a sample show page link.
4. Click the `Remove` button.
5. Verify a confirmation dialog appears.
6. Click the `Confirm` button.
7. Verify the page redirected to the samples page and the selected count within the table footer is updated.
=> Delete sample selection fix

app/services/automated_workflow_executions/launch_service.rb, test/services/automated_workflow_executions/launch_service_test.rb
Updated automated workflow executions launch service to set workflow execution name to `USER_SUPPLIED NAME SAMPLE_NAME (SAMPLE_PUID)`. This addresses [STRY0017741](https://publichealthprod.service-now.com/rm_story.do?sys_id=1b2a86923b34aa105c163064c3e45a9d)
1. Setup 2 automated workflow executions for a project, one with a name set and another without
2. Create a new sample in the project and upload a paired-end dataset to the sample
3. Go to the project `Workflow Executions`
4. Verify the name for one of the workflow executions is …
=> Automated Workflow Execution: Update name to include sample name

app/components/layout/sidebar_component.html.erb, app/components/layout_component.html.erb, app/javascript/controllers/layout_controller.js
This PR updates the expand logic for the sidebar to also focus to the IRIDA Next logo after expanding the sidebar (via keyboard). In addition now when tabbing outside of the sidebar it is automatically collapses (if the user expanded the sidebar while viewing the application at high enough zoom to cause sidebar to collapse automatically). In addition, I added a tab target at the bottom of the html, so that if a user reverse tabs from the IRIDA Next logo, through their web browser tabbable areas back into the website it will also collapse the sidebar.
[Peek 2025-05-30 08-07.webm](https://github.com/user-attachments/assets/2b70a5c1-3522-4 …
=> Fix: Sidebar overlay focus transfer on expand via keyboard

app/controllers/data_exports_controller.rb, app/controllers/groups/attachments_controller.rb, app/controllers/groups/bots_controller.rb, app/controllers/groups/history_controller.rb, app/controllers/groups/members_controller.rb, app/controllers/groups/metadata_templates_controller.rb, app/controllers/groups/samples_controller.rb, app/controllers/groups/workflow_executions_controller.rb, app/controllers/groups_controller.rb, app/controllers/profiles/accounts_controller.rb, app/controllers/profiles/passwords_controller.rb, app/controllers/profiles/personal_access_tokens_controller.rb, app/controllers/profiles/preferences_controller.rb, app/controllers/profiles_controller.rb, app/controllers/projects/attachments_controller.rb, app/controllers/projects/automated_workflow_executions_controller.rb, app/controllers/projects/bots_controller.rb, app/controllers/projects/history_controller.rb, app/controllers/projects/members_controller.rb, app/controllers/projects/metadata_templates_controller.rb, app/controllers/projects/samples_controller.rb, app/controllers/projects/workflow_executions_controller.rb, app/controllers/projects_controller.rb, app/controllers/workflow_executions_controller.rb, config/locales/en.yml, config/locales/fr.yml
This PR addresses browser page titles to be more descriptive (removing path/url and replacing with name). [STRY0018198](https://publichealthprod.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3Dcc8be6f947f1e250f24c0c21516d43ed)
1. Visit every page, and ensure the browser titles in the tab make sense
=> Accessibility: Browser title update

app/components/data_exports/table_component.rb, app/components/groups/table_component.rb, app/components/members/table_component.rb, app/components/metadata_templates/table_component.rb, app/components/viral/data_table_component.rb, app/views/dashboard/projects/index.html.erb, app/views/groups/activity.html.erb, app/views/groups/members/index.html.erb, app/views/projects/activity.html.erb, app/views/projects/members/index.html.erb, app/views/projects/samples/attachments/_table.html.erb, app/views/projects/samples/metadata/_table.html.erb, app/views/projects/samples/show.html.erb
This PR removes `data-turbo-temporary` from main content of pages so that navigating forward (e.g. clicking a link in the breadcrumbs) and then navigating backward (using browser back button), doesn't result in a blank page which then has content on refresh.
2. Navigate to project of choice
3. Click on `Members` sidebar menu item
4. Click on `Groups` tab
5. Hit back button (observe that Members table loads)
6. Click on `Groups` tab
7. Click on `Samples` sidebar menu item
8. Hit back button (observe that Groups table loads)
9. Repeat these same …
=> Fix: Back button behaviour

app/components/attachments/table_component.html.erb
A fix for the Attachments::TableComponent rendering an extra table cell in the table body when no row actions are permitted. This was accidentally introduced in #1109.
BEFORE:
AFTER:
1. Open a rails console and enable the feature flag by running the following command.
```
Flipper.disable(:attachments_preview)
```
2. Open a browser and verify the feature is enabled by navigating to http://localhost:3000/rails/flipper/features.
3. Navigate to a workflow execution files page.
4. Verify there is no extra cell in the table body.
=> Fix Attachments::TableComponent

app/assets/tailwind/application.css, app/controllers/groups_controller.rb, app/models/concerns/routable.rb, app/services/groups/create_service.rb, app/validators/namespace_path_validator.rb, app/views/groups/_form_fields.html.erb, app/views/groups/new.html.erb, app/views/groups/new_subgroup.html.erb, app/views/shared/form/_field_errors.html.erb, config/locales/en.yml, config/locales/fr.yml, lib/irida/path_regex.rb, test/graphql/create_group_mutation_test.rb, test/graphql/create_project_mutation_test.rb, test/system/groups_test.rb
Hints and error messages on Group/Subgroup form have been updated to use `aria-describedby` to link to ids of elements containing hints and error messages.
Form inputs now set `aria-invalid` when errors have been encountered.
Updated `routable` to not add error from `route.path` to `namespace` when error of type already exists on the `namespace.path`.
[Peek 2025-06-19 10-05.webm](https://github.com/user-attachments/assets/8def2493-d713-4688-87cf-a8e77e1c9333)
1. Launch the server, and login as your preferred user
2. Open the create menu at the top of the sidebar …
=> Fix: Group creation form description and error message accessibility

app/components/ransack/sort_dropdown_component.html.erb, app/components/viral/dropdown/item_component.html.erb, app/components/viral/dropdown/item_component.rb, app/components/viral/dropdown_component.html.erb, app/components/viral/dropdown_component.rb, app/helpers/sorting_helper.rb, app/javascript/controllers/viral/dropdown_controller.js, app/views/dashboard/groups/index.html.erb, config/locales/en.yml, config/locales/fr.yml, test/helpers/sorting_helper_test.rb, test/system/dashboard/groups_test.rb, test/system/dashboard/projects_test.rb
The [disclosure pattern](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/
) is implemented on the dropdown component. 
STRY0018228 (ART-8931) & STRY0018191 (ART-8909) & STRY0018214 (ART-8932)
1. Navigate to the groups and/or projects dashboard page.
2. Try these [keyboard interactions](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation-hybrid/#kbd_label) on the sorting dropdown.
3. Verify the screen reader announces `Sorted by` before each dropdown option.
4. Verify the screen reader announces which dropdown option is currently selected.
Note: When testing with NVDA, tab to the dropdown, then use `Insert`+`Space` keys to change from browse mode to form mode to use arrow keys.
This checklist encourages us to confirm any …
=> Sorted dropdown menu state fix

app/components/layout/breadcrumb_component.html.erb, app/javascript/controllers/breadcrumb_controller.js, test/components/layout/breadcrumb_component_test.rb
This PR fixes broken breadcrumb links that was introduced in #1128. This reverts URL generation to use `URI.join` with `root_url` so that links actually point to the correct endpoint.
This was broken in alot of places but an easy place to verify is to navigate directly to a sample and then click the `Samples` link in the breadcrumb.
=> Fix: Broken Breadcrumb links

docs-site/package.json, docs-site/pnpm-lock.yaml, docs-site/src/css/custom.css, docs-site/src/theme/DocSidebar/Desktop/Content/index.tsx, docs-site/src/theme/DocSidebar/Desktop/Content/styles.module.css, docs-site/src/theme/NavbarItem/DropdownNavbarItem/Desktop/index.tsx
This PR fixes interaction and focus issues in our docs site.
* The language selection dropdown is now accessible via keyboard with or without a screenreader enabled
* Sidebar expand/collapse buttons now retain visible focus while interacting with them via keyboard while using a screenreader
* Sidebar menu items retain focus on keyboard interaction
* e.g. changing what page of docs to view will keep focus on that item in the sidebar instead of sending to top of page
1. Change to docs site directory: `cd docs-site`
2. Update dependencies: `pnpm install …
=> A11y: Docs site focus fixes

.devcontainer/compose.yaml, .github/workflows/ruby.yml, .github/workflows/sapporo.yml, test/integration/integration_sapporo_test.rb
This PR updates the sapporo config to pass `IRIDA_NEXT_PATH` env variable which due to a commit in phac-nml/sapporo-service (https://github.com/phac-nml/sapporo-service/commit/0fc5d97751ee073cc1cb69a52f7a69293254c720) it will chown the outputs to match the UID and GID of the IRIDA_NEXT_PATH folder.
1. Checkout this branch
2. Execute `Ctrl-Shift-P` in vscode
3. Type in `Rebuild Container` and hit enter
4. After rebuild run the following test `bin/rails test test/integration/integration_sapporo_test.rb`
5. Verify that both tests pass
This checklist encourages us …
=> Devcontainer: Update sapporo config to fix permission issues

app/assets/tailwind/application.css, app/components/history_component.html.erb, app/components/history_version_component.html.erb, test/components/history_version_component_test.rb, test/system/groups/history_test.rb, test/system/projects/history_test.rb, test/system/projects/samples/history_test.rb
This PR updates the history_version_component dialog to use spans within a div instead of using `datalist` tags as dl tags cannot have elements other than `dd` and `dt` as direct children. Also updated was the timeline bullet to meet `3:1` constrast ratio with its surrounding color, and minimum width/height for the buttons which launch the history version component dialog. Addresses the following:
- [STRY0018436](https://publichealthprod.service-now.com/rm_story.do?sys_id=d8111c0947966250f24c0c21516d4338)
- [STRY0018435](https://publichealthprod.service-now.com/rm_story.do?sys_id=bae0140947966250f24c0c21516d439b)
- [STRY0018433](https://publichealthprod.service-now.com/rm_story.do?sys_id=44c0dc8547966250f24c0c21516d43d2)
- …
=> History components accessibility fixes

app/assets/tailwind/application.css
Webkit and firefox browser search inputs have a clear input button that is not keyboard accessible.  This PR uses CSS to hide the button.
Addresses issue [STRY0018339](https://publichealthprod.service-now.com/rm_story.do?sys_id=987fa10a474e6610f24c0c21516d4363)
Go to the project samples page and try to search by name or PUID.  The clear button should not be displayed
=> Hide clear button on search inputs

app/assets/tailwind/application.css, app/components/viral/form/help_text_component.html.erb, app/components/viral/form/help_text_component.rb, app/components/viral/page_header_component.html.erb, app/services/projects/create_service.rb, app/views/groups/_form_fields.html.erb, app/views/projects/_project_namespace_fields.html.erb, app/views/projects/new.html.erb, app/views/shared/form/_required_field_legend.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/viral/form/datepicker_component_test.rb, test/components/viral/form/file_input_component_test.rb, test/components/viral/form/help_text_component_test.rb, test/system/groups/bots_test.rb, test/system/groups/metadata_templates_test.rb, test/system/groups/workflow_executions_test.rb, test/system/projects/automated_workflow_executions_test.rb, test/system/projects/bots_test.rb, test/system/projects/metadata_templates_test.rb, test/system/projects/samples_test.rb, test/system/projects/workflow_executions_test.rb
Hints and error messages on Create project form have been updated to use aria-describedby to link to ids of elements containing hints and error messages. Addresses the following:
- [STRY0018225](https://publichealthprod.service-now.com/rm_story.do?sys_id=a38c33db4739aa50f24c0c21516d43dc)
- [STRY0018229](https://publichealthprod.service-now.com/rm_story.do?sys_id=894d33db4739aa50f24c0c21516d435a)
- [STRY0018234](https://publichealthprod.service-now.com/rm_story.do?sys_id=a9dd7f1f4739aa50f24c0c21516d4350)
- [STRY0018252](https://publichealthprod.service-now.com/rm_story.do?sys_id=841fd1bb47f12e50f24c0c21516d43b6)
- [STRY0018251](https://publichealthprod.service-now.com/rm_story.do?sys_id=f7ce11bb47f12e50f24c0c21516d4310)
- …
=> Fix: Project creation form description and error message accessibility

app/assets/tailwind/application.css, app/controllers/passwords_controller.rb, app/controllers/profiles/passwords_controller.rb, app/controllers/registrations_controller.rb, app/controllers/sessions_controller.rb, app/javascript/controllers/email_input_controller.js, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_form.html.erb, app/views/profiles/passwords/_form.html.erb, app/views/shared/form/_required_field_legend.html.erb, config/locales/devise.en.yml, config/locales/devise.fr.yml, config/locales/en.yml, config/locales/fr.yml
This PR fixes contrast issues on devise pages, adds unique browser page titles, and adds visual cues for required fields for forms. The styling of the change password page was also updated to match the other devise views. Addresses the following:
- [STRY0018479](https://publichealthprod.service-now.com/rm_story.do?sys_id=eaaa8da6335e621061dd45659d5c7b3f)
- [STRY0018480](https://publichealthprod.service-now.com/rm_story.do?sys_id=59ea01e6335e621061dd45659d5c7bf9)
- [STRY0018482](https://publichealthprod.service-now.com/rm_story.do?sys_id=245bc5e6335e621061dd45659d5c7b23
)
- [STRY0018483](https://publichealthprod.service-now.com/rm_story.do?sys_id=aa6bc5a6335e621061dd45659d5c7b47)
- …
=> Devise: Views accessibility

app/assets/tailwind/application.css, app/views/groups/_edit_advanced_path.html.erb, app/views/groups/_edit_advanced_transfer_form.html.erb, app/views/groups/_edit_name_and_description_form.html.erb, app/views/groups/_form_fields.html.erb, app/views/groups/new.html.erb, app/views/groups/new_subgroup.html.erb, test/system/groups_test.rb
This PR updates the forms on the group edit page to display visual cues for required fields and linked error messages to input fields. **PR is not linked to any user stories but is a part of general accessibility issues addressed on forms within the application**
1. Create a group
2. Go into the group settings (General)
3.  Verify that visual cues are present on the forms except for the delete
4. Remove the …
=>  Fix: Group edit forms accessibility

app/components/attachments/table_component.html.erb, app/components/bots/table_component.html.erb, app/components/personal_access_tokens/table_component.html.erb, app/components/workflow_executions/table_component.html.erb, app/views/groups/members/_current_user_is_member.html.erb, app/views/groups/members/_current_user_is_not_member.html.erb, app/views/projects/automated_workflow_executions/_table.html.erb, app/views/projects/members/_current_user_is_member.html.erb, app/views/projects/members/_current_user_is_not_member.html.erb, config/locales/en.yml, config/locales/fr.yml, test/system/projects/automated_workflow_executions_test.rb, test/system/projects/workflow_executions_test.rb, test/system/workflow_executions_test.rb
This PR adds `aria-label` to each action link contained with a table to better convey purpose to screen reader users, and distinguish links from each other.
e.g.
2. Go to each table that has action(s) column and ensure that each link has an `aria-label` set that includes the name in the row.
=> A11y: Action link aria label

app/controllers/concerns/share_actions.rb, app/services/group_links/group_link_service.rb, app/views/groups/group_links/_invite_group_modal.html.erb, app/views/groups/group_links/create.turbo_stream.erb, app/views/projects/group_links/_invite_group_modal.html.erb, app/views/projects/group_links/create.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml, test/services/group_links/group_link_service_test.rb
This PR adds in visual indicators for required fields and error display with informative error messages when fields are left blank.
1. Try to share a namespace with a group (Members -> Invite Group) to a project and group but leave the access level blank
2. Verify that error messages are displayed and linked to the inputs via aria-describedby
3. The `Share` button is disabled if the group isn't selected. From the chrome inspect, remove the disabled attribute on the button and click the button
4. Verify that error messages are displayed and linked to the inputs …
=> Fix: Invite Group create modal forms accessibility

app/javascript/controllers/viral/dialog_controller.js, test/components/viral/dialog_component_test.rb, test/system/groups/samples_test.rb, test/system/projects/samples_test.rb
This PR updates the dialog_controller.js to refocus the trigger on close, or refocus the trigger on subsequent disconnect and connect if the dialog was previously open (e.g. advanced search submit or clear).
Note: Dialogs without a trigger defined, e.g. click a button that does turbo request to retrieve dialog will not refocus. This behaviour will have to be updated later by refactoring those server rendered dialogs in a separate PR.
[Peek 2025-08-19 09-41.webm](https://github.com/user-attachments/assets/fa77d879-3735-4874-a041-ef877c0b47de) …
=> A11y: Dialog trigger refocus on close or disconnect/connect if open

app/views/layouts/devise.html.erb
Fixed devise view reflow where the language selection button when focused and viewed at 400% zoom caused an overlap with the IRIDA Next icon
Addresses: 
[STRY0018490](https://publichealthprod.service-now.com/rm_story.do?sys_id=2f5b552e339e621061dd45659d5c7b15)
**100% previous**
**400% previous**
**100% current**
**400% current**
1. Verify the language selection button/dropdown when `Francais` is selected and keyboard focused does not overlap with the IRIDA Next icon when the viewport is set to 1280x1024 and zoomed to 400%
This checklist encourages us to confirm …
=> Accessibility: Devise layout language selection overlap

app/assets/tailwind/application.css, app/components/activities/dialogs/activity_list_dialog_component.html.erb, app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb, app/components/viral/dialog_component.html.erb, app/components/viral/dialog_component.rb, app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb, app/views/groups/group_links/_invite_group_modal.html.erb, app/views/groups/members/_create_modal.html.erb, app/views/groups/workflow_executions/_edit_dialog.html.erb, app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb, app/views/projects/group_links/_invite_group_modal.html.erb, app/views/projects/members/_create_modal.html.erb, app/views/projects/workflow_executions/_edit_dialog.html.erb, app/views/workflow_executions/_edit_dialog.html.erb
This PR updates the styling for the Dialog component to reflow when zooming in. That involves switching from dialog section scroll to entire dialog being scrollable when viewport is `<48rem`. In addition, dialog size classes have been updated to only apply their max width when viewport is `>=48rem`.
2. Login then click on an button that launches a dialog
3. In viewport of 1280 x 1024 zoom in to 250%
4. Confirm that modal takes up full screen width and whole modal scrolls instead of just the section
5. Optionally confirm with the lookbook …
=> A11y: Dialog component reflow

app/assets/tailwind/application.css, app/components/viral/dialog_component.html.erb, app/components/viral/dialog_component.rb, test/system/dashboard/projects_test.rb, test/system/groups/group_links_test.rb, test/system/groups/samples_test.rb, test/system/projects/bots_test.rb, test/system/projects/samples_test.rb
This PR is a followup to #1195 and refactors the component to allow select2 and datepicker to overflow properly.
Before:
[Screencast from 2025-08-22 09-11-16.webm](https://github.com/user-attachments/assets/1ecccea1-7597-456b-a73e-426d93d45128)
After:
[Screencast from 2025-08-22 09-12-10.webm](https://github.com/user-attachments/assets/9656e255-f5a7-46ef-9cae-090d4130bc80)
2. Open browser with viewport 1280 x 1024
3. Navigate to Group Members page of your choice
4. Click on `Invite group` to launch modal
5. Try `Group` dropdown and …
=> A11y: Dialog reflow followup

app/views/groups/_edit_advanced_path.html.erb, app/views/projects/_change_path.html.erb
This PR fixes reflow issues on the project/group edit pages which caused content to overflow resulting in both a horizontal and vertical scroll. Addresses:
[STRY0018426](https://publichealthprod.service-now.com/rm_story.do?sys_id=b3fdc44547966250f24c0c21516d43ea)
**Edit Group**
**100%**
**400%**
**Edit Project**
**100%**
**400%**
1. Set browser to 1280x1024
2. Visit the general settings page for a project
3. Zoom in slowly up to 400% and ensure there is no loss of content
4. Repeat for editing a group …
=> Fix: Project/Group edit reflow

app/components/nextflow_component.html.erb, app/components/viral/form/prefixed/boolean_component.html.erb, app/components/viral/form/prefixed/boolean_component.rb, app/helpers/nextflow_helper.rb, app/javascript/controllers/selection_controller.js, app/views/workflow_executions/file_selector/_file_selector_dialog.html.erb, config/locales/en.yml, config/locales/fr.yml, test/components/previews/viral_form_prefixed_boolean_component_preview/default.html.erb, test/components/previews/viral_form_prefixed_boolean_component_preview/with_false_value.html.erb, test/components/previews/viral_form_prefixed_boolean_component_preview/with_icon.html.erb, test/components/viral/form/prefixed/boolean_component_test.rb
Fixes the srceenreader not announcing the group label for a group of radio buttons.
[STY0018336](https://publichealthprod.service-now.com/rm_story.do?sys_id=703f6dc6474e6610f24c0c21516d43da)
Before:
After:
1. Start a screenreader and open a browser.
1. Launch a workflow within irida-next or view a preview within [lookbook](http://localhost:3000/rails/lookbook/inspect/viral_form_prefixed_boolean).
1. Tab through a boolean component.
1. Verify the group label is announced.
=> Boolean component accessibility

app/views/profiles/_form.html.erb
This PR updates the profile main settings form to display visual cues for required fields and linked error messages to input fields. 
1. Try editing the user profile -> main settings (leaving some blank etc)
2. Verify error messages are displayed and are linked to the input(s) via aria-describedby
=> Accessibility: Profile main settings

app/components/treegrid_component.rb, app/helpers/namespace_row_helper.rb, app/views/dashboard/groups/group.turbo_stream.erb, app/views/dashboard/groups/index.html.erb, app/views/dashboard/projects/index.html.erb, app/views/groups/_shared_namespaces.html.erb, app/views/groups/_subgroups_and_projects.html.erb, app/views/groups/subgroups/subgroup.turbo_stream.erb, config/locales/en.yml, config/locales/fr.yml
This PR updates the treegrid row component aria labels to read out the name, puid, role, and any additional attributes on the row. Addresses:
[STRY0018213](https://publichealthprod.service-now.com/rm_story.do?sys_id=c44b928b47bd2a50f24c0c21516d439f)
1. Launch NVDA
2. Create a group `Group A`, `Group B` and project `Project 1`
3. Verify the screenreader reads out all the data for a row on the projects/groups dashboard when the row is focused
4. Share a `Group A` with `Group B`
5. Visit `Group B`
6. Verify the screenreader reads out all the data for a row on the …
=> Updated aria labels for treegrid row component

app/jobs/data_exports/create_job.rb, config/locales/en.yml, config/locales/fr.yml, test/jobs/data_exports/create_job_test.rb
Fixes #1154 
DataExports::CreateJob now correctly raises errors when data export cannot be saved, and when underlying libraries (such as Tempfile) throw errors that cannot be recovered from.
=> Added exception handling to DataExports CreateJob

app/components/spinner_component.html.erb
Fixes [STRY0018335](https://publichealthprod.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3Dc92f250a474e6610f24c0c21516d4357%26sysparm_view%3Dscrum%26sysparm_record_target%3Drm_story%26sysparm_record_row%3D2%26sysparm_record_rows%3D10%26sysparm_record_list%3Dassignment_group%253D9efb9efb47765a50f24c0c21516d4374%255Eshort_descriptionSTARTSWITHART-%255Estate%253D2%255EORDERBYpriority%26sysparm_view%3Dscrum)
Our spinner component was not announcing the message within. This was due to the spinner component generally being 'injected' into the DOM, which has some weird/unexpected behaviour where `role=status` does not get announced (https://github.com/nvaccess/nvda/issues/14591 https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/). The same …
=> Spinner Component: Change role to alert

app/components/samples/editable_cell.html.erb, app/components/samples/editable_cell.rb, app/controllers/samples/metadata_controller.rb, app/javascript/controllers/editable_cell_controller.js, app/services/samples/metadata/fields/update_service.rb
This PR updates the editable cell to properly reconnect on page size changes, page navigation, metadata display toggling. In addition cell is refocused on update automatically, and user now has the ability to clear the value (prior they were given an error message).
1. Navigate to a Group Samples page
2. Toggle metadata display
3. Ensure metadata cells are interact-able
4. Change the page size
5. Ensure that metadata cells are interact-able
6. Change to a metadata template
7. Ensure that metadata cells are interact-table
8. Navigate to a different page
9. Ensure …
=> Fix: Editable Cell focus, connection, and clearing

app/views/projects/samples/attachments/_table.html.erb
Fixes reflow of samples attachments page
[STRY0018412](https://publichealthprod.service-now.com/nav_to.do?uri=rm_story.do?sys_id=053640c947566250f24c0c21516d4339%26sysparm_view=scrum)
Before:
Now:
[Screencast from 2025-09-05 02:12:55 PM.webm](https://github.com/user-attachments/assets/4662e913-3c1b-4520-8ac5-bf7bb24a82fc)
1. Navigate to a sample with files (or upload files), and test the reflow at 400% zoom
=> Samples Attachments Reflow

app/views/shared/samples/_metadata_template_dropdown.html.erb, app/views/shared/samples/_metadata_template_item.html.erb, app/views/shared/samples/_metadata_templates_list.html.erb, config/locales/en.yml, config/locales/fr.yml
This PR updates accessibility for metadata template dropdown. Menu items in the dropdown are now announced with whether they are checked or not. Addresses:
[STRY0018345](https://publichealthprod.service-now.com/rm_story.do?sys_id=de103d0a474e6610f24c0c21516d434c)
=> Accessibility: Metadata template dropdown

app/components/metadata_templates/table_component.html.erb, app/controllers/concerns/metadata_template_actions.rb, app/views/shared/metadata_templates/_create.turbo_stream.erb, app/views/shared/metadata_templates/_edit_template_dialog.html.erb, app/views/shared/metadata_templates/_form.html.erb, app/views/shared/metadata_templates/_new_template_dialog.html.erb, config/locales/en.yml, config/locales/fr.yml, test/system/groups/metadata_templates_test.rb, test/system/projects/metadata_templates_test.rb, test/test_helpers/axe_helpers.rb
Associating the metadata template name & description error messages with form fields.
Name & description error messages:
Fields error message:
1. Navigate to a project and/or group that the logged in user has at least maintainer access.
2. Click `Settings` -> `Metadata Templates` within the main menu.
3. Try creating and updating metadata templates.
5. Verify the correct error messages are displayed after an invalid form entry.
=> Metadata template form accessibility

app/views/projects/samples/attachments/deletions/_modal.html.erb, app/views/projects/samples/metadata/deletions/_modal.html.erb, app/views/projects/workflow_executions/_edit_dialog.html.erb, app/views/workflow_executions/_edit_dialog.html.erb
This PR fixes:
- Removes horizontal scrolling of the dialog within the delete sample files and metadata dialogs, moving the scroll to the table
- Edit workflow buttons
Delete sample files:
Delete metadata:
Edit Workflow button reflow:
1. Navigate to a sample and delete its files, and verify the table has a horizontal scrollbar and the dialog does not.
2. Delete a sample's metadata (make sure you have metadata with a long name or value), and verify the table has a horizontal scrollbar and the dialog does not
3. Edit a workflow execution and verify the buttons reflow properly at 400%
=> Fix: Scrolling on delete sample metadata/file dialogs and Edit Workflow buttons

app/javascript/controllers/email_input_controller.js, app/views/devise/passwords/new.html.erb
1. Currently, the password reset error message has a contrast rating of 3.83, which is below the criteria for AA.  After this update, it will match other error styles and have a 5.1 rating, which is AA.
2. Clean up `email_input_controller`.  Proper handling of form submission, handles blur and updates email address validation.
**Before**
**After**
=> Clean up dark mode error visibility for reset password

app/components/search_component.html.erb, app/components/search_field_component.html.erb, app/views/groups/samples/_table_filter.html.erb, app/views/projects/samples/_table_filter.html.erb
This PR enhances the search field component accessibility so that screenreaders will also read out the label for the search field
1. Verify that screenreader reads out the label of the search field when focused
=> Accessibility: Search Field Component

app/components/advanced_search/condition.html.erb, app/components/advanced_search/value.html.erb, app/components/advanced_search_component.html.erb, app/components/list_input_component.html.erb, app/components/list_input_component.rb
Updates the AdvancedSearch component to use visible labels for condition form fields, updates remove button hover state to match sample add metadata form. Also updated remove condition button to use `title` instead of `aria-label` so that sighted keyboard users can also see it.
note: screenshots were taken with delay so that mouse could stay hovered on the remove condition button.
Before:
After:
=> Update AdvancedSearch component to have visible labels
