phac-nml/irida-next

- Gemfile
- Gemfile.lock
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/locales/en.yml
- test/components/previews/tooltip_component_preview.rb
- test/components/viral/system/tooltip_component_test.rb
- test/system/profile_test.rb
Updated devise to v4.9.2 and fixed accompanying views:
- session/new
- passwords/new
- registrations/new
- shared devise links
Fixes #73
> Internal: Update devise to 4.9.2

- .github/PULL_REQUEST_TEMPLATE/default.md
- docs-site/docs/development/development_processes/_category_.json
- docs-site/docs/development/development_processes/code_review.md
- docs-site/docs/development/development_processes/index.md
- docs-site/docs/development/development_processes/pull_request_workflow.md
- docs-site/docs/development/front_end/_category_.json
This PR adds in documentation for our development process and additionally adds in a pull request template. The purpose of this is to clarify the process for all team members, and to set out written expectations. These documents were heavily inspired by GitLab.
Since these are changes to the documentation you can review the updated site with the following steps:
1. `cd docs-site && pnpm run start`
2. Navigate to `http://localhost:4000/irida-next/docs/development/development_processes`
3. Review the two pages linked under that section.
This checklist encourages …
> Development Process Documentation

- .github/pull_request_template.md
- Moves the existing template down into the `.github` directory, and renamed to `pull_request_template.md`
- Added a link the the PR acceptance checklist so that developers could easily review it when making their PR
N/A
Unfortunately cannot validate locally
[This checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.
> chore: Default PR template and added link to PR acceptance checklist

- app/controllers/concerns/membership_actions.rb
- app/models/member.rb
- app/services/members/destroy_service.rb
- app/views/groups/members/_current_user_is_member.html.erb
- app/views/groups/members/_current_user_is_not_member.html.erb
- app/views/groups/members/index.html.erb
- app/views/projects/members/_current_user_is_member.html.erb
- app/views/projects/members/_current_user_is_not_member.html.erb
- app/views/projects/members/index.html.erb
- config/locales/en.yml
- test/models/members/group_member_test.rb
- test/policies/project_policy_test.rb
- test/services/members/destroy_service_test.rb
- test/system/groups/members_test.rb
- test/system/projects/members_test.rb
This PR adds functionality for a member to be able to leave a group or project on their own without needing an owner or maintainer to remove them.
Due to a bad rebase and force update of commits PR #114 ended up with 0 commits and was closed. Opened this PR to replace it.
Resolves #95 and #96 
**Logged in as user that is removing themselves from the group:**
**Removing a member that is not the current logged in user**
1. Login as `admin@example.com`
2. Go the the `Bacillus` group and view it's members
3. Click the ellipsis for the `admin@example.com` user and …
> Member leave group

- app/assets/stylesheets/application.tailwind.css
- app/components/viral/avatar_component.html.erb
- app/components/viral/avatar_component.rb
- app/components/viral/page_header_component.html.erb
- app/components/viral/page_header_component.rb
- app/helpers/view_helper.rb
- app/views/groups/index.html.erb
- app/views/groups/show.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
- test/components/previews/viral_avatar_component_preview.rb
- test/components/previews/viral_avatar_component_preview/default.html.erb
- test/components/previews/viral_avatar_component_preview/large.html.erb
- test/components/previews/viral_avatar_component_preview/small.html.erb
- test/components/previews/viral_avatar_component_preview/with_link.html.erb
- test/components/previews/viral_page_header_component_preview.rb
- test/components/previews/viral_page_header_component_preview/with_avatar.html.erb
- test/components/previews/viral_page_header_component_preview/with_icon.html.erb
- test/components/viral/avatar_component_test.rb
- test/components/viral/page_header_component_test.rb
- Create a Viral Avatar component that accepts an `initial`, `colour_string` (used to generate the avatar colour), and `size` (`:small`, `:medium`, `:large` - default is `:medium` if nothing is passed)
- Updated project and group listing pages with an avatar on each row (similar to GitLab)
- Update project and group show pages with an avatar in the page header
**Light**
**Dark**
**Light**
**Dark**
1, Three sizes of avatars can be previewed through [Lookbook](http://localhost:3000/rails/lookbook/inspect/viral_avatar/default)
1. Run IRIA-next locally, with fresh …
> Avatar for project and groups listing and show pages

- app/graphql/irida_schema.rb
- app/graphql/resolvers/project_resolver.rb
- app/graphql/resolvers/projects_resolver.rb
- app/graphql/schema.graphql
- app/graphql/types/group_type.rb
- app/graphql/types/namespace.rb
- app/graphql/types/node_type.rb
- app/graphql/types/project_type.rb
- app/graphql/types/query_type.rb
- app/models/project.rb
- test/graphql/group_query_test.rb
- test/graphql/node_query_test.rb
- test/graphql/nodes_query_test.rb
- test/graphql/project_query_test.rb
- test/graphql/projects_query_test.rb
This PR adds a Project type to the GraphQL api which implements the Relay Node interface. 
1. Login as `admin@email.com`
1. Open the graphiql interface `http://localhost:3000/graphiql`
1. Query for a Project that you can access.
* ```graphql
{
project(fullPath: "bacillus/bacillus-anthracis/outbreak-2022") {
id
name
path
}
}
```
1. See that you get a valid result
1. Query for a Project that you cannot access.
* ```graphql
{
project(fullPath: "borrelia/borrelia-burgdorferi/outbreak-2022") {
id
name
path
}
}
```
1. See that you get an authorization error
This …
> GraphQL: Project Type

- Gemfile
- Gemfile.lock
- app/controllers/projects/samples/attachments_controller.rb
- app/controllers/projects/samples_controller.rb
- app/models/attachment.rb
- app/views/projects/samples/attachments/_form.html.erb
- test/models/attachment_test.rb
Adds in active-storage-validations gem, and updates Attachment model to validate that the `file` is attached (i.e. ensure that file is associated with the attachment).
1. Navigate to a Sample and attempt to upload file without selecting a file.
2. Ensure that a error shows up in the form indicating that file can't be blank.
> Attachments: File presence validation

- app/models/member.rb
- test/fixtures/members.yml
- test/fixtures/users.yml
- test/system/projects/members_test.rb
Fixed bug preventing removal of user from a project under a user namespace. 
1. Login as any user
2. Create a project under the user's namespace
3. Add a few members to the project
4. Try removing a user. Verify that the user has been removed
the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.
> Project member under user namespace removal

- app/controllers/concerns/membership_actions.rb
- app/models/member.rb
- app/views/groups/members/_current_user_is_member.html.erb
- app/views/groups/members/_member.html.erb
- app/views/groups/members/destroy.turbo_stream.erb
- app/views/groups/members/index.html.erb
- app/views/groups/members/index.turbo_stream.erb
- app/views/projects/members/_current_user_is_member.html.erb
- app/views/projects/members/_member.html.erb
- app/views/projects/members/destroy.turbo_stream.erb
- app/views/projects/members/index.html.erb
- app/views/projects/members/index.turbo_stream.erb
- config/locales/en.yml
- test/controllers/concerns/groups_membership_actions_concern_test.rb
- test/controllers/concerns/projects_membership_actions_concern_test.rb
- test/controllers/groups/members_controller_test.rb
- test/controllers/projects/members_controller_test.rb
- test/system/projects/members_test.rb
This PR updates group/project members destroy to work via turbo_stream.
1. Login as any user
2. Add a member as a direct member to a subgroup where the user is also a member of an ancestor
3. Now remove this user from the subgroup
4. Verify that the member's ancestor inheritance is displayed
5. Verify in the network tab of the browser dev tools that the request/ was sent via turbo_stream
6. Verify page is not reloaded but rather the user's inherited membership is appended to the table …
> Member destroy turbostream

- app/components/viral/form/help_text_component.html.erb
- app/components/viral/form/help_text_component.rb
- app/helpers/view_helper.rb
- app/views/shared/form/_field_errors.html.erb
- test/components/previews/viral_form_help_text_component_preview.rb
- test/components/previews/viral_form_help_text_component_preview/default.html.erb
- test/components/previews/viral_form_help_text_component_preview/error.html.erb
- test/components/previews/viral_form_help_text_component_preview/success.html.erb
- test/components/viral/form/help_text_component_test.rb
- Created a component to render consistent form help/error/success messages
- Fixes error message on samples file upload and create new sample
1. Create a sample with an existing sample name, error message should be displayed properly
2. On a file, click upload a file, an click `Upload file` without actually selecting a file.  Error message should be displayed properly
> Fix field errors

- config/initializers/faraday.rb
Configure `Faraday.default_adapter` as OAuth authentication e.g. AzureActiveDirectoryv2 was failing as it was trying to use the default_adapter but it is no longer set in newer version of Faraday.
> Faraday fix

- app/views/groups/members/_member_listing.html.erb
- app/views/groups/members/index.html.erb
- app/views/groups/members/index.turbo_stream.erb
- app/views/projects/members/_member_listing.html.erb
- app/views/projects/members/index.html.erb
- app/views/projects/members/index.turbo_stream.erb
Fixes members system tests that were failing on main due to incorrect usage of turbo stream updates that was causing DOM ID duplication, also fixes html dom structure issues in members index pages.
1. Navigate to Groups members page
2. Ensure that table listing, pagination, creating, and deleting operations work and render correctly
3. Repeat tests on Projects members page
> Fix Members Partials DOM ID duplication

- app/views/groups/group_links/_pagination.html.erb
- app/views/groups/group_links/create.turbo_stream.erb
- app/views/groups/group_links/index.turbo_stream.erb
- app/views/groups/members/_pagination.html.erb
- app/views/groups/members/create.turbo_stream.erb
- app/views/groups/members/destroy.turbo_stream.erb
- app/views/groups/members/index.turbo_stream.erb
- app/views/projects/group_links/_pagination.html.erb
- app/views/projects/group_links/index.turbo_stream.erb
- app/views/projects/members/_pagination.html.erb
- app/views/projects/members/destroy.turbo_stream.erb
- app/views/projects/members/index.turbo_stream.erb
This PR moves pagination into a partial for group/project members and group_links.
1. Verify the pagination is working as expected for `Group -> Members and Group Links`
2. Verify the pagination is working as expected for `Project -> Members and Group Links`
> Moved pagination into a partial for members and group_links

- app/controllers/projects/samples/attachments_controller.rb
- app/javascript/application.js
- app/services/attachments/create_service.rb
- app/views/projects/samples/attachments/_form.html.erb
- app/views/projects/samples/attachments/_new_attachment_modal.html.erb
- app/views/projects/samples/attachments/create.turbo_stream.erb
- config/application.rb
- config/importmap.rb
- config/locales/en.yml
- config/routes.rb
- test/controllers/projects/samples/attachments_controller_test.rb
- test/system/projects/samples_test.rb
This PR changes the upload process to use direct upload (see https://blog.commutatus.com/understanding-rails-activestorage-direct-uploads-a4aeca7eccf). This also adds in a `Attachments::CreateService` which takes in a list of `files` so that multiple `Attachments` can be created in one go. Add in this service allows a user to upload multiple files at once instead of having to submit a single file per upload.
1. Login as your user of choice, and create a personal project
2. Create a Sample in the project you just created
3. Navigate to the Sample
4. Click `Upload …
> Attachments: Direct multiple upload

- config/locales/en.yml
- test/system/groups/members_test.rb
- test/system/projects/members_test.rb
This PR fixes up the flaky members_test for both groups and projects by asserting table is visible before checking for records.
1. Run the tests 5+ times locally
2. Verify there were no test failures for any of the members_test
> Fix flaky members tests

- app/components/layout/sidebar/item_component.html.erb
- app/components/layout/sidebar/item_component.rb
- app/controllers/dashboard/groups_controller.rb
- app/controllers/dashboard/projects_controller.rb
- app/controllers/groups/members_controller.rb
- app/controllers/groups/samples_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/profiles/accounts_controller.rb
- app/controllers/profiles/application_controller.rb
- app/controllers/profiles/passwords_controller.rb
- app/controllers/profiles/personal_access_tokens_controller.rb
- app/controllers/profiles/preferences_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/projects/members_controller.rb
- app/controllers/projects/samples_controller.rb
- app/controllers/projects_controller.rb
- app/views/layouts/application.html.erb
- app/views/layouts/groups.html.erb
- app/views/layouts/profiles.html.erb
- app/views/layouts/projects.html.erb
- test/components/layout_component_test.rb
Some pages, like the new sample page, did not highlight the correct navigation menu item. This change sets the selected navigation menu item name within the controller. 
Fixes #154.
Navigate to every page and make sure the correct item within the navigation menu is selected.
> Allow controller to indicate selected navigation menu item

- app/assets/stylesheets/application.tailwind.css
- app/javascript/controllers/attachment_upload_controller.js
- app/views/projects/samples/attachments/_form.html.erb
- config/locales/en.yml
This PR shows the upload progress of sample attachments. Previously, the user would not have any feedback on whether their files were uploading. With these changes, the files will now be shown uploading with a progress bar and percentage.
[Screencast from 2023-10-16 11:43:26 AM.webm](https://github.com/phac-nml/irida-next/assets/82407232/a4f71123-d9b6-4800-bb1e-bf914cb7ba84)
Upload sample attachments and view the attachment's progress.
> Add upload progress for sample attachment upload

- app/javascript/controllers/attachment_upload_controller.js
Fixes a display error during upload server errors, currently throwing errors to the console.
Fixed with:
- When adding multiple classes to an element it is essential to add them as individual tokens.
- When setting a zero value in CSS you do not need to add the units
> Fixed adding classes on attachment upload error

- app/components/viral/empty_state_component.html.erb
- test/components/viral/empty_component_test.rb
Fixes flaky test which sometimes fails with HTML semantically incorrect tag hierarchy due to the title being an h3 tag.
Updated it to be a p tag which should not cause problems.  Styling stays the same.
N/A
N/A
> chore: Change h3 to p to fix semantics in empty state component

- app/controllers/projects/samples/application_controller.rb
- app/controllers/projects/samples/attachments/concatenations_controller.rb
- app/controllers/projects/samples/attachments_controller.rb
- app/services/attachments/concatenation_service.rb
- config/routes/project.rb
- test/controllers/projects/samples/attachments/concatenations_controller_test.rb
- test/fixtures/active_storage/attachments.yml
- test/fixtures/active_storage/blobs.yml
- test/fixtures/attachments.yml
- test/models/attachment_test.rb
- test/system/projects/samples_test.rb
This PR adds in a controller to support concatenating Samples Attachments into a new Attachment.
Resolves #239 
> Attachments: Concatenations Controller

- config/locales/fr.yml
Two translations were missed during the merging of the language-selection and attachment-listings branches.
Select the French language, and ensure you can navigate to the samples' attachment listing page (the translations missing were the new format and type table headers).
> Add translations missed during merge of previous two branches

- app/controllers/projects/samples/transfers_controller.rb
- app/views/projects/samples/transfers/_transfer_modal.html.erb
- test/controllers/projects/samples/transfers_controller_test.rb
- test/system/projects/samples_test.rb
This PR updates the Project::Samples::TransfersController to only respond_to tubro_stream requests and use namespaced params under `transfer` key.
> Samples Transfers Controller Update

- app/assets/stylesheets/application.tailwind.css
- app/components/viral/card/header_component.html.erb
- app/controllers/projects/samples/attachments/concatenations_controller.rb
- app/controllers/projects/samples/attachments_controller.rb
- app/controllers/projects/samples_controller.rb
- app/javascript/controllers/projects/samples/attachments/concatenations_controller.js
- app/javascript/controllers/selection_controller.js
- app/services/attachments/concatenation_service.rb
- app/views/projects/samples/attachments/_attachment.html.erb
- app/views/projects/samples/attachments/_new_attachment_modal.html.erb
- app/views/projects/samples/attachments/_table.html.erb
- app/views/projects/samples/attachments/concatenations/_modal.html.erb
- app/views/projects/samples/attachments/concatenations/create.turbo_stream.erb
- app/views/projects/samples/attachments/concatenations/new.turbo_stream.erb
- app/views/projects/samples/attachments/create.turbo_stream.erb
- app/views/projects/samples/show.html.erb
- config/locales/en.yml
- config/routes/project.rb
- test/controllers/projects/samples/attachments/concatenations_controller_test.rb
- test/controllers/projects/samples/attachments_controller_test.rb
- test/services/attachments/concatenation_service_test.rb
- test/system/projects/samples_test.rb
- test/test_helpers/axe_helpers.rb
A user can select two or more files of the same type and concatenate them together.
Fixes #286.
A. Keeping the original files.
1. Navigate to sample.
2. Upload two or more files of the same type.
3. Check the files to be concatenated.
4. Click the `Concatenate Files` button.
5. Fill in a base name.
6. Click the `Concatenate` button.
7. Verify the original & concatenated file.
B. Removing the original files.
1. Navigate to sample.
2. Upload two or more files of the same type.
3. Check the files to be concatenated.
4. Click the `Concatenate Files` button.
5. Fill in a base name.
6. Check `Delete originals`.
7. Click the `Concatenate` button.
8. Verify the original & concatenated file. …
> Attachments Concatenation UI

- app/controllers/groups/samples_controller.rb
- app/policies/sample_policy.rb
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespace_group_links.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/samples.yml
- test/fixtures/users.yml
- test/graphql/projects_query_test.rb
- test/policies/project_policy_test.rb
- test/policies/sample_policy_test.rb
- test/services/samples/update_service_test.rb
- test/system/dashboard/projects_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
This PR updated group samples view to display samples that the user has access to through namespace group links. This was accomplished by adding a sample policy which returns samples for projects within a group as well as samples from projects within namespace group links.
1. Login as admin@email.com
2. Visit the group page for `Bacillus` (or any other group which has namespaces linked to it)
3. Go through the samples and you should see samples from projects that you have access to through namespace group links
4. Create 3 groups, `Group A`, `Group B`, and …
> Update: Group samples view

- .gitattributes
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Procfile.dev
- app/jobs/attachments_cleanup_job.rb
- app/models/jobs_record.rb
- config/application.rb
- config/database.yml
- config/initializers/good_job.rb
- db/jobs_migrate/20231208184638_create_good_jobs.rb
- db/jobs_schema.rb
- scripts/clean_dev.sh
- test/jobs/attachments_cleanup_job_test.rb
Fixes #203
Adds new gem `good_job`
Adds new database `jobs`
Adds new abstract record `JobsRecord` for database `jobs`
Adds db migration for good_job active job records on new db `jobs`
Adds daily cron task to run `AttachmentsCleanupJob` via good_job
Changed `AttachmentsCleanupJob` to use kwargs for good_job compatibility
The PR includes a daily job. We can modify the cron timing such that it runs every minute so we can see the jobs are being scheduled correctly.
In `config/application.rb` change line 67
```ruby
cron: '0 0 1 * * *', # Daily, 1 AM
cron: '1 * * * * …
```
> Active jobs Backend

- db/migrate/20231110010253_create_workflow_executions.rb
- db/migrate/20231110010313_create_samples_workflow_executions.rb
- db/schema.rb
- db/seeds.rb
Ran into issue on local machine when creating a WorkflowExecution in the seeds file causing an issue with the name of the migration.  After renaming the migrations seeding the database was able to finish successfully.
> Workflow Execution DB Fix

- app/controllers/groups_controller.rb
- app/models/member.rb
- app/policies/namespace_policy.rb
- app/policies/project_policy.rb
- test/controllers/concerns/group_share_actions_concern_test.rb
- test/controllers/concerns/project_share_actions_concern_test.rb
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespace_group_links.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/users.yml
- test/models/group_test.rb
- test/policies/namespace_policy_test.rb
- test/policies/project_policy_test.rb
- test/system/dashboard/projects_test.rb
- test/system/groups/members_test.rb
- test/system/groups_test.rb
- test/system/projects/members_test.rb
This PR updates the `manageable` scopes for the project and namespace policies which will now return project namespaces and groups which the user has `modify` access to. A bug in the base project `relation` scope was fixed so that the correct linked projects are returned.
1) Create 2 new users (newuser1@email.com and newuser2@email.com)
2) Login as newuser1@email.com
3) Create a new group `Group A`, a project `Group A Project 1` under `Group A`, a subgroup `Group A Subgroup 1` under `Group A`, and a project `Group A Subgroup 1 Project 1`  under `Group A Subgroup …
> Update: Policy manageable scopes

- app/models/workflow_execution.rb
This PR adds `tags` to `as_wes_params` response so that execution via WES api succeeds, as this is a required argument for our implementation. Currently this is just set to `createdBy` with a value of `:FIRST_NAME :LAST_NAME`.
> Update WorkflowExecution as_wes_params to set tags

- app/components/nextflow_component.html.erb
- app/controllers/workflow_executions_controller.rb
- test/controllers/workflow_executions_controller_test.rb
Redirect the user to the pipelines listing page after pipeline submission.
Launch a workflow and will be redirected to the workflow executions listing page.
> Redirect after successful workflow submission

- app/services/workflow_executions/preparation_service.rb
- test/services/workflow_executions/preparation_service_test.rb
Fixes `--input` and `--outdir` params to use service path which was previously missing.
Adds `--validate-params false` as default params due to https://github.com/nextflow-io/nf-validation/issues/130
> Workflow Executions: Preparation Service updates

- app/policies/project_policy.rb
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespace_group_links.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/users.yml
- test/policies/project_policy_test.rb
This PR updates the project policy scopes (base and manageable scopes) to return projects which are directly shared with a group.
1) Create a new user
2) Login as `admin@email.com` and create 2 groups `Group A` and `Group B`
3) Add the new user as a member to `Group A` as a `MAINTAINER`
4) In Group B make a few subgroups with each subgroup being a parent of the next
5) Create a project in the most descendant subgroup
6) In this project go to the `Members` page and click the `Groups` tab
7) Invite `Group A` as a `MAINTAINER`
8) Logout and login as the user …
> Fix: List shared projects on dashboard

- app/controllers/groups/samples_controller.rb
- app/models/concerns/routable.rb
- app/models/project.rb
- app/views/groups/samples/_pagination.html.erb
- app/views/groups/samples/_table.html.erb
- app/views/groups/samples/index.html.erb
- app/views/groups/samples/index.turbo_stream.erb
- config/locales/en.yml
- test/models/group_test.rb
- test/models/namespaces/project_namespace_test.rb
- test/models/namespaces/user_namespace_test.rb
- test/system/groups/samples_test.rb
Made the following changes to the group samples table:
- Updated `Project` column to include the group hierarchy using only the first letter with a popover that displays the full path on hover
- Added `Created` column
- Added `Last Updated` column
- Added sorting by name or date
- Added search/filter by name
*Metadata not included.*
Fixes #266.
1. Navigate to a group.
2. View samples.
3. Verify filtering and sorting works.
> Update Group Samples Table

- Gemfile
Move `graphiql-rails` gem from `development` only to be included in all env.
> graphiql-rails gem env switch

- app/services/workflow_executions/preparation_service.rb
- test/services/workflow_executions/preparation_service_test.rb
Update `--outdir` param to include a trailing slash to help indicate that it is a directory.
> Workflow Executions: --outdir trailing slash

- app/controllers/projects/samples/transfers_controller.rb
- app/models/member.rb
- app/policies/project_policy.rb
- app/services/samples/transfer_service.rb
- config/locales/en.yml
- test/controllers/projects/samples/transfers_controller_test.rb
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/policies/project_policy_test.rb
- test/services/samples/transfer_service_test.rb
- test/system/dashboard/projects_test.rb
- test/system/projects/samples_test.rb
This PR updates the functionality for transferring samples from one project to another to allow users with a `Maintainer` role to transfer samples from one project to another within the same hierarchy with a common ancestor (cannot transfer to shared projects or projects outside of the hierarchy.
For example:
Group A -> Project 1
Group A -> Subgroup 1 -> Project 2
Group A -> Subgroup 2 -> Project 3
Group B -> Project 4
Group B -> Subgroup 1 -> Project 5
Maintainers can transfer samples between projects in Group A and it's subgroups but cannot transfer to any project under Group B or it's subgroups and vice versa
**Selecting the …
> Maintainer Project Sample Transfer

- app/controllers/projects/samples/transfers_controller.rb
- app/policies/project_policy.rb
- app/views/projects/samples/transfers/_transfer_modal.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/samples.yml
- test/fixtures/users.yml
- test/policies/group_policy_test.rb
- test/policies/namespace_policy_test.rb
- test/policies/project_policy_test.rb
- test/system/dashboard/projects_test.rb
- test/system/projects/samples_test.rb
This PR fixes the maintainer sample transfer which would list all projects a user had manageable access to instead of just listing the projects in the hierarchy of the current project. The fix was to pass the correct parameter (project namespace) to the user_has_maintainer_access? method in the member model
1. Login as `admin@email.com`
2. Create a group `Group A` with 2 subgroups
3. Add a project to `Group A` and to each of it's subgroups
4. Add a sample to each project
5. Add the `user1@email.com` as a `Maintainer` to `Group A` -> `Subgroup 1` -> `Project 2` …
> Maintainer sample transfer project listing fix

- app/assets/icons/heroicons/arrow_down.svg
- app/assets/icons/heroicons/arrow_up.svg
- app/components/ransack/sort_component.html.erb
- app/components/ransack/sort_component.rb
- app/components/ransack/sort_dropdown_component.html.erb
- app/controllers/projects/application_controller.rb
- app/controllers/projects/samples/transfers_controller.rb
- app/controllers/projects/samples_controller.rb
- app/helpers/sorting_helper.rb
- app/views/groups/samples/_table.html.erb
- app/views/groups/samples/index.html.erb
- app/views/groups/samples/index.turbo_stream.erb
- app/views/projects/samples/_table.html.erb
- app/views/projects/samples/index.html.erb
- app/views/projects/samples/index.turbo_stream.erb
- config/locales/en.yml
- test/fixtures/samples.yml
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
Added a new view component that uses the ransack object to create sort links in table headers.
**Project Samples**
**Group Samples**
Currently set up on the project samples page.
> Table sort headers

- test/system/groups/samples_test.rb
Fixes issue with bad test on groups samples listing page.
> Fix: Group samples sort testing

- app/models/concerns/has_puid.rb
- app/models/project.rb
- app/models/sample.rb
- config/initializers/persistent_unique_id.rb
- db/migrate/20240122144035_add_puid_to_sample.rb
- db/migrate/20240124170054_add_puid_to_project.rb
- db/schema.rb
- lib/base32.rb
- lib/irida/persistent_unique_id.rb
- test/fixtures/projects.yml
- test/fixtures/samples.yml
- test/lib/base32_test.rb
- test/lib/irida/persistent_unique_id_test.rb
- test/models/project_test.rb
- test/models/sample_test.rb
This PR adds in Persist Unique Identifiers (puid) to Project and Sample models.
1. Run `bin/rails db:migrate` to execute the migrations and ensure that all `Sample` and `Project` received a `puid`.
2. Create a new `Sample`
3. In the rails console verify that `Sample.last` has a puid and is the sample you created
4. Create a new `Project`
5. In the rails console verify that `Project.last` has a puid and is the project you created
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, …
> Persistent unique indentifiers

- app/javascript/controllers/projects/samples/metadata/file_import_controller.js
- app/views/projects/samples/index.html.erb
- app/views/projects/samples/metadata/file_imports/new.turbo_stream.erb
- test/system/projects/samples_test.rb
Fixed issue with import metadata modal hijacking the dialog on project samples page
Go to project samples page
1. Open and close the import metadata modal
2. Select a couple samples and open the transfer samples modal
> Fixed issue with import metadata modal hijacking the dialog on project samples page

- app/components/history_version_component.html.erb
- config/locales/en.yml
- test/components/history_component_test.rb
- test/components/history_version_component_test.rb
This PR fixes an issue with keys that were deleted from a json column not displaying in the version change log.
**Main branch**
**This branch:**
**On the main branch:**
1. Login as a user and create a project with a sample
2. Go into the sample from step 1 and click on the `Metadata` tab
3. Add some metadata to the sample
4. Edit some metadata
5. Click on the `History` tab for the sample
6. You should see `3` versions (1 created sample and 2 sample modified attributes)
7. Open up each version and see that you can see the diff of changes from the previous version …
> Fixed deleted metadata keys not displaying in version log

- app/controllers/projects/samples/clones_controller.rb
- config/routes/project.rb
- test/controllers/projects/samples/clones_controller_test.rb
The new controller that calls the Samples::CloneService.
Fixes #403.
N/A
Verify the tests within `test/controllers/projects/samples/clones_controller_test.rb` pass.
> Clone samples controller

- app/components/viral/page_header_component.html.erb
- app/components/viral/page_header_component.rb
- app/components/viral/pill_component.rb
- app/controllers/groups/samples_controller.rb
- app/controllers/projects/samples_controller.rb
- app/models/sample.rb
- app/views/groups/samples/_table.html.erb
- app/views/groups/samples/index.html.erb
- app/views/projects/samples/_table.html.erb
- app/views/projects/samples/index.html.erb
- app/views/projects/samples/show.html.erb
- app/views/projects/show.html.erb
- config/database.yml
- config/locales/en.yml
- config/locales/fr.yml
- test/components/viral/pill_component_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
This PR adds the PUID to the samples tables (in both projects and groups), as well as a badge on the Project and Sample views containing its PUID.
Project Samples View:
Project Samples View with sorting:
Project Samples View with sorting and filtering:
Group Samples View:
Group Samples View with sorting:
Group Samples View with sorting and filtering:
Sample with new puid badge and breadcrumb:
Project with new puid badge:
1. Navigate to the Projects Samples and Groups Samples views and ensure the PUID for samples are in the table.
2. Ensure you can sort and filter by PUID.
3. Navigate to a sample and project, and ensure you can view the PUID by their respective names.
4. On a sample view, ensure the breadcrumb now contains the accurate PUID, and clicking the PUID breadcrumb links you to …
> Add puid to samples and projects

- .gitignore
- app/controllers/workflow_executions/submissions_controller.rb
- app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
- config/initializers/pipelines.rb
- config/pipelines/pipelines.json
- lib/irida/pipeline.rb
- lib/irida/pipelines.rb
- test/config/pipelines/pipelines.json
- test/lib/irida/pipelines_test.rb
This PR adds in a pipeline configuration which will register the available pipelines that can be launched within IRIDA Next. The pipeline configuration is stored in `config/pipelines/pipeline.json`. For each pipeline and version a `nextflow_schema` and `schema_input` file are retrieved from the github repo for the pipeline and are stored under `private/pipelines/REPO_ORGANIZATION_AND_NAME/VERSION/`. Along with these files a `status.json` file is generated and stored which has the `etag` header values for both files, which is used to determine if a newer schema file needs to be downloaded when the server is started up.
**Version 1.0.2** …
> Workflow: Pipeline configuration

- app/components/viral/form/checkbox_component.html.erb
- app/helpers/nextflow_helper.rb
- config/pipelines/pipelines.json
- test/components/previews/nextflow_component_preview/default.html.erb
Checkboxes were not properly fixed after updating after the paired file selection was introduced.  This was caused by the `form`
1. Lunch a pipeline that requires a checkbox (suggest is https://github.com/phac-nml/snvphylnfc)
2. When launching the pipeline before this fix, the submission dialog would crash, now the dialog should open and the checkbox should be available.
> Workflow Execution: Fixed workflow checkboxes

- app/components/nextflow/samplesheet/sample_cell_component.html.erb
- app/components/nextflow_component.html.erb
- app/components/nextflow_component.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/services/workflow_executions/preparation_service.rb
- app/views/workflow_executions/submissions/new.turbo_stream.erb
- test/components/nextflow_component_test.rb
- test/components/nextflow_samplesheet_component_test.rb
- test/fixtures/workflow_executions.yml
- test/services/workflow_executions/create_service_test.rb
- test/system/workflow_executions/submissions_test.rb
1. Updated `nextflow_component.html.erb` to read and parse the sample sheet schema of the workflow execution 
2. Updated `nextflow_component.rb` to read and parse the workflow schema off the workflow execution
3. Update `preperation_service.rb` and remove the hard-coded header files, now they are read from the workflow sample sheet.
There is no new UI here, just updating how the UI is created.
1. Select samples From a project the current user has permission on and click the workflow execution launch button.
2. Select a workflow and ensure that the sample sheet …
> Workflow Executions: Workflow schema read from workflow

- app/assets/icons/heroicons/document_magnifying_glass.svg
- app/components/viral/dialog/header_component.html.erb
- app/components/viral/dialog/header_component.rb
- app/components/viral/dialog_component.html.erb
- app/components/viral/dialog_component.rb
- app/components/viral/pill_component.html.erb
- app/javascript/controllers/filter_list_controller.js
- app/javascript/controllers/selection_controller.js
- app/javascript/controllers/viral/dialog_controller.js
- app/views/projects/samples/_tagged_filter.html.erb
- app/views/projects/samples/index.html.erb
- config/locales/en.yml
- test/components/previews/viral_dialog_component_preview.rb
- test/components/previews/viral_dialog_component_preview/non_closable.html.erb
- test/components/previews/viral_pill_component_preview.rb
- test/components/previews/viral_pill_component_preview/with_content.html.erb
- test/components/viral/dialog_component_test.rb
- test/components/viral/pill_component_test.rb
- test/components/viral/system/dialog_component_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
**Filter by list button**
**Filter by list dialog**
**Filter by list dialog after past of PUID list**
> Project Samples: Filter by name or puid list

- db/migrate/20240229165646_migrate_to_uuid.rb
Active Storage Attachments were not being correctly migrated when they came from WorkflowExecutions or SamplesWorkflowExecutions.
1. Checkout the commit in main prior to id to uuid migration. `git checkout 5d189cece2ca43a71632533a844974be0e7846a0`
2. Reset the database `./scripts/clean_dev.sh`
3. Run the server and submit a pipeline (Allow the job server to prepare the inputs) (Can verify with `select * from active_storage_attachments where record_type = 'SamplesWorkflowExecution' or record_type = 'WorkflowExecution';`)
4. Checkout this branch
5. Run migrations …
> Fix: ID to UUID migration issues

- app/javascript/controllers/filter_list_controller.js
- db/seeds.rb
- test/system/projects/samples_test.rb
There was an issue that the last key typed was not added when creating a tag.
N/A
1. Go to project  samples page for any project with samples
2. Enter text into the input and wait a second for tag to be created
3. Tag should contain all character entered
4. Once tag made, hit backspace and add some more character
5. Tag should have all characters
> Fix: filter by name removing last character

- docs-site/docs/configuration/pipelines.md
This PR adds in documentation with instructions on how to register pipelines which will be available to launch within IRIDA Next.
> Documentation: Pipeline Configuration

- test/system/workflow_executions/submissions_test.rb
Fixes flaky test caused by non-specific search for buttons within the dialog.
N/A
N/A
> Fix: Flaky pipeline selection test

- app/models/attachment.rb
- app/models/sample.rb
- app/views/groups/samples/_table.html.erb
- app/views/projects/samples/_table.html.erb
- config/locales/en.yml
- db/migrate/20240311152411_add_attachments_updated_at_to_samples.rb
- db/migrate/20240311152411_add_files_updated_at_to_samples.rb
- db/migrate/20240311152839_modify_sample_logidze_trigger_v03.rb
- db/migrate/20240311204201_add_attachments_updated_at_to_workflow_executions.rb
- db/migrate/20240311204219_add_attachments_updated_at_to_samples_workflow_executions.rb
- db/schema.rb
- db/triggers/logidze_on_samples_v03.sql
- test/fixtures/samples.yml
- test/models/sample_test.rb
- test/services/attachments/concatenation_service_test.rb
- test/services/attachments/create_service_test.rb
- test/services/attachments/destroy_service_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
This PR adds a new column to the samples table `attachments_updated_at` which gets updated whenever files are added or removed to/from a sample.
**No attachments**
**Uploaded attachments  - samples table at project level**
**Destroyed attachments - samples table at project level**
**Samples table at group level**
1. Switch to the main branch
2. Reset your database `bin/rails db:drop db:create db:migrate db:seed`
3. Switch to this branch
4. Run `bin/rails db:migrate`
5. Open `rails console` in the terminal
6. Run the query `Sample.first` and make note of the new …
> Sample files updated column

- test/test_helpers/cuprite_setup.rb
This PR updates the `process_timeout` (time to compile assets and launch chrome) within the cuprite setup to help alleviate pending connection errors that were being encountered locally and on the CI server
1. Run the test suite locally multiple times and ensure you do not receive any `Ferrum::PendingConnectionsError` errors
> Testing: Update cuprite helper

- app/models/member.rb
- app/policies/group_policy.rb
- app/views/groups/samples/_table.html.erb
- app/views/groups/samples/index.html.erb
- app/views/projects/samples/index.html.erb
- app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
- config/locales/en.yml
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/samples.yml
- test/policies/group_policy_test.rb
- test/policies/namespace_policy_test.rb
- test/policies/project_policy_test.rb
- test/system/dashboard/projects_test.rb
- test/system/projects/samples_test.rb
- test/system/workflow_executions/submissions_test.rb
Added the ability for a user with at least analyst access to launch pipelines from the group samples table.
Fixes #455.
1. Login to irida-next.
2. Create a new project and a new sample within the new project.
3. Go back to project samples page and select the new sample.
4. Verify clicking the pipeline submission button works the same as on the project samples table.
Repeat with a user less than an analyst and verify the pipeline submission button is disabled.
> Group samples workflow submission

- test/models/namespace_test.rb
- test/system/workflow_executions/submissions_test.rb
- test/test_helpers/cuprite_setup.rb
This PR updates the `timeout` for cuprite to fix the ferrum pending connection errors. Namespace model and workflow execution submission tests were also updated to fix random failures.
1. Run the test suite `bin/rails test:all` repeatedly
2. Verify that you don't get any ferrum pending connection errors, any errors related to the workflow execution submission test, or the namespace model test
> Testing: Cuprite timeout update

- test/system/workflow_executions/submissions_test.rb
This PR updates the submissions_test to look within a turbo_frame before running assertions. **NOTE: The assertions for number of buttons with the expected text have currently been commented out so that our other prs are not held up due to this failure. Only appears to happen randomly and frequently on the ci server and not when testing locally**
> Testing: Update workflow execution submissions test

- app/controllers/data_exports_controller.rb
- app/policies/data_export_policy.rb
- config/routes.rb
- test/controllers/data_exports_controller_test.rb
This PR adds the `data_export_controller`.
1. Ensure tests pass locally
Note: Many expected tests require a template view. These tests will be added as the data export UI gets added
> Data Export - Controller

- app/components/nextflow/samplesheet/row_component.html.erb
- app/components/nextflow/samplesheet/row_component.rb
- app/components/nextflow/samplesheet_component.html.erb
- app/components/nextflow_component.html.erb
Fixed invalid params errors which caused `SamplesWorkflowExecution` to not be created as the switch to `UUID` identifiers meant that the form needed to just use an integer index for creating multiple `SamplesWorkflowExecution` entities. Also removed `workflow_version` param which was unnecessary as that is passed in via `metadata`.
1. Select samples and submit a pipeline
2. Switch to Rails console
3. Run `WorfklowExecution.last.samples_workflow_executions.count` and make sure that matches the number of samples you selected to run the pipeline
This checklist …
> Fix: Nextflow Component Params

- .vscode/launch.json
This PR fixes the vscode-rdbg config so that no errors are raised when running rails server in debug mode.
> Fix: Vscode RDBG Config

- app/controllers/groups/samples_controller.rb
- app/views/groups/samples/_table.html.erb
- app/views/groups/samples/index.html.erb
- app/views/groups/samples/select.turbo_stream.erb
- config/locales/en.yml
- config/routes/group.rb
- test/system/groups/samples_test.rb
Adds the ability to select all the samples within the group samples table.
1. Go to a group that has samples
2. Click the select all checkbox, all samples should be selected
3. Click the select all checkbox again, all samples should be de-selected
4. Check to make sure that the table footer is updated with the correct number of samples
> Group: Samples table select all

- test/fixtures/data_exports.yml
- test/jobs/data_exports/create_job_test.rb
This PR attempts to fix the test `content of export including paired files` as it sometimes fails due to the size of the export.
Ensure tests pass locally
> Fix Paired Files Export Test

- app/controllers/concerns/metadata.rb
- app/controllers/workflow_executions_controller.rb
- app/models/concerns/metadata_sortable.rb
- app/models/sample.rb
- app/models/workflow_execution.rb
- app/views/workflow_executions/_pagination.html.erb
- app/views/workflow_executions/_table.html.erb
- app/views/workflow_executions/_workflow_execution.html.erb
- app/views/workflow_executions/destroy.turbo_stream.erb
- app/views/workflow_executions/index.html.erb
- app/views/workflow_executions/index.turbo_stream.erb
- config/locales/en.yml
- test/fixtures/workflow_executions.yml
- test/system/workflow_executions_test.rb
Made the following changes to the workflow table:
- Added pagination
- Added new Job ID column
- Added sorting to all columns except `actions`
Fixes #470.
1. Login to irida-next
2. Create some new workflows.
3. Navigate to the workflow page.
4. Verify table pagination & sorting work.
> Workflow table pagination

- db/seeds.rb
This PR adds seeding for exports
- In `rails c` run `bin/rails db:drop/create/migrate/seed`
- Ensure the database seeds properly
- Ensure each user except user8 and 9 has two exports, 1 with status = processing and 1 with status = ready. The export with status = ready should also have an export attached.
> Seed Exports

- app/assets/icons/heroicons/arrow_up_on_square_stack.svg
- app/components/layout/sidebar_component.html.erb
- app/controllers/data_exports_controller.rb
- app/views/data_exports/_table.html.erb
- app/views/data_exports/destroy.turbo_stream.erb
- app/views/data_exports/index.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/controllers/data_exports_controller_test.rb
- test/fixtures/data_exports.yml
- test/jobs/data_exports/create_job_test.rb
- test/system/data_exports_test.rb
This PR adds the Data Export listing page. This page will display all the current exports the user has created.
Note: The ID and name of exports will be links that navigate to the data export's respective pages. This will be implemented in a future PR.
Listing page:
Data export in sidebar dropdown:
Download action for exports with `status = ready`
No download action for exports with `status = processing`
Screencast of downloading and deleting export
[Screencast from 2024-03-21 03:27:16 PM.webm](https://github.com/phac-nml/irida-next/assets/82407232/79ab7438-fbbf-44d8-8b47-18e3156ec431)
1. In `rails c` `db:drop/create/migrate/seed`. You will now have data exports on users admin and 1 to 7.
2. Ensure navigation to the exports listing page works for both the sidebar link and the sidebar …
> Data Export - Listing

- app/javascript/controllers/list_filter_controller.js
Update the filter by Sample PUIDs or Names to split on newlines so that a user could copy the contents of a file that has one sample name/puid per line into the search box and have the terms properly split.
Unable to add a test at this time.
1. Go to a Project with Samples
2. Create a text file and copy two sample ids into it separate by newlines
3. Copy the contents of that file and paste it into the search box
4. See that the terms are properly split and search works as expected
This checklist encourages us to confirm any changes have been analyzed to reduce …
> Update Filter By Sample PUIDs or Names to split on newlines

- .dockerignore
Paths in `.dockerignore` were incorrect and meant that docker buildcontext was pulling in more data then necessary.
Build the docker container with the following command:
`docker build -t irida-next:dev -f Dockerfile .`
This should zoom through the copying build context stage with the changes above.
> Fix .dockerignore

- app/helpers/nextflow_helper.rb
- app/services/workflow_executions/create_service.rb
- test/controllers/workflow_executions_controller_test.rb
- test/services/workflow_executions/create_service_test.rb
Updates the WorkflowExecutions::CreateService to sanitize workflow params. E.g. remove blank values and convert integers and numbers to the correct format
1. Submit a workflow and empty out a value
2. In rails console query for that workflow execution and check that the param is not present
```
irb(main):001> WorkflowExecution.last.workflow_params
WorkflowExecution Load (0.8ms)  SELECT "workflow_executions"."metadata", "workflow_executions"."workflow_params", "workflow_executions"."workflow_type", "workflow_executions"."workflow_type_version", …
```
> Workflow Executions: Sanitize Workflow Params

- app/models/concerns/has_user_type.rb
- app/models/member.rb
- app/models/namespace_bot.rb
- app/models/namespaces/project_namespace.rb
- app/models/user.rb
- app/policies/namespaces/project_namespace_policy.rb
- app/services/bots/create_service.rb
- app/services/bots/destroy_service.rb
- config/locales/en.yml
- db/migrate/20240229165646_migrate_to_uuid.rb
- db/migrate/20240408201453_add_user_type_to_users.rb
- db/migrate/20240408204851_create_namespace_bots.rb
- db/schema.rb
- db/triggers/logidze_on_namespace_bots_v01.sql
- test/fixtures/members.yml
- test/fixtures/namespace_bots.yml
- test/fixtures/personal_access_tokens.yml
- test/fixtures/users.yml
- test/models/namespace_bot_test.rb
- test/services/bots/create_service_test.rb
- test/services/bots/destroy_service_test.rb
This PR adds in the db, model, and service layer for namespace bot accounts.
1. Create a new account for IRIDA next from the UI, login, and create a project
2. Open rails console in the terminal
3. Set the following `user = User.last`, `proj_namespace = Namespaces::ProjectNamespace.last`, `params = {"token_name": "Uploader", "scopes":["read_api", "api"], "access_level":20}`
4. Run `Bots::CreateService.new(user, proj_namespace, params).execute`
5. Verify that a new user was created with a user_type of `1` which is a `project_bot`
6. Verify that the user is linked …
> Bot accounts model service setup

- db/migrate/20240408204851_create_namespace_bots.rb
- db/schema.rb
This PR updates the create namespace_bots migration to use `uuid` for the `id`
1. Verify the migration works
2. In rails console run `NamespaceBot`
3. Verify the `id` is a `uuid`
> Update namespace bot UUID

- app/components/nextflow/samplesheet/metadata_cell_component.html.erb
- app/components/nextflow/samplesheet/metadata_cell_component.rb
- app/components/nextflow/samplesheet/row_component.rb
- app/components/nextflow/samplesheet/sample_cell_component.html.erb
- app/components/nextflow/samplesheet_component.html.erb
- db/seeds.rb
- test/components/nextflow_samplesheet_component_test.rb
- test/fixtures/files/nextflow/samplesheet_schema_meta.json
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/samples.yml
- test/policies/group_policy_test.rb
- test/policies/namespace_policy_test.rb
- test/policies/project_policy_test.rb
- test/system/dashboard/projects_test.rb
- test/system/workflow_executions/submissions_test.rb
- Sample metadata defined within the schema file can now be displayed in Workflow Submission Samples table
- Added horizontal scrolling to the samples table (only for larger tables)
Properly adds metadata to the form parameters:
Add the following lines to `private/pipelines/phac-nml/iridanextexample/1.0.2/schema_input.json` at the end of the properties section:
```json
"insdc_accession": {
"type": "string",
"pattern": "^(SRR|ERR|DRR)\\S+$",
"meta": ["insdc_accession"],
"errorMessage": "Must provide a valid accession"
},
"country": {
"type": "string",
"meta": …
```
> Workflow Submission: Sample Metadata

- app/controllers/concerns/bot_actions.rb
- app/controllers/concerns/membership_actions.rb
- app/controllers/projects/bots_controller.rb
- config/locales/en.yml
- config/routes/project.rb
- db/migrate/20240408204851_create_namespace_bots.rb
- db/schema.rb
- test/controllers/concerns/bot_actions_concern_test.rb
- test/controllers/projects/bots_controller_test.rb
This PR adds in the bot actions concern, and project bots controller which uses the bot actions concern
1. Verify all the tests pass
> Bot accounts controller setup

- test/graphql/attachments_query_test.rb
Fix the previously flaky test `test/graphql/attachments_query_test.rb`
> Fix Flaky Attachments Graphql Test

- app/components/nextflow_component.html.erb
- app/components/nextflow_component.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/models/attachment.rb
- app/views/groups/samples/_table.html.erb
- app/views/projects/samples/_table.html.erb
- lib/irida/pipeline.rb
- test/components/nextflow_component_test.rb
Added in a `workflow_params` method to `lib/irida/pipeline.rb` so that we don't have to read and parse the nextflow schema file in NextflowComponent.
> Workflow Execution: Pipeline workflow_params method

- app/models/data_export.rb
- app/policies/workflow_execution_policy.rb
- app/services/data_exports/create_service.rb
- config/locales/en.yml
- config/locales/fr.yml
- test/services/data_exports/create_service_test.rb
This PR adds exporting workflow execution to the export create service.
1. Ensure tests pass locally
> Data Export: Create Service - Add workflow execution

- app/components/nextflow/samplesheet/dropdown_cell_component.rb
- app/components/nextflow/samplesheet/row_component.rb
- app/components/nextflow/samplesheet_component.rb
- app/components/nextflow_component.html.erb
- app/helpers/nextflow_helper.rb
- lib/irida/pipeline.rb
Fixes issue with section title and description not rendering due to workflow_params refactor.
Fixes samplesheet file cell rendering when file inputs have `meta` tag (were incorrectly being parsed as metadata cells)
Adds in autopopulating of fastq_1 file cell when it is not required and no other file cells are required.
Add `mikrokondo` to `config/pipelines/pipelines.json`
e.g.
```json
{
"url": "https://github.com/phac-nml/mikrokondo",
"name": "phac-nml/mikrokondo",
"description": "Mikrokondo beta",
"versions": [
{
"name": "0.1.0"
}
]
}
```
Launch server and …
> Nextflow component fixes

- Gemfile
- Gemfile.lock
- app/components/nextflow_component.html.erb
- app/helpers/nextflow_helper.rb
- app/models/workflow_execution.rb
- app/services/workflow_executions/cancel_service.rb
- app/services/workflow_executions/create_service.rb
- app/services/workflow_executions/preparation_service.rb
- db/seeds.rb
- lib/integrations/ga4gh_wes_api/v1/api_connection.rb
- lib/integrations/ga4gh_wes_api/v1/api_requester.rb
- lib/integrations/ga4gh_wes_api/v1/client.rb
- lib/irida/pipeline.rb
- scripts/clean_dev.sh
- test/controllers/workflow_executions_controller_test.rb
- test/fixtures/workflow_executions.yml
- test/integration/ga4gh_wes_api_test.rb
- test/services/workflow_executions/create_service_test.rb
- test/services/workflow_executions/preparation_service_test.rb
This updates the GA4GH WES Api connector to use `multipart-form-data` when submitting a request to the `run_workflow` endpoint which is alignment with the WES 1.1.0 spec.
Additionally the PR does the following:
- Updates `as_wes_params` to format the params correctly for use as form data
- Removes `--` and `-` prefixes from `workflow_params` as we are now specifying them as a `json` in nextflow command line (e.g. `nextflow -params-file params.json`)
- Specify workflow version via `worfklow_engine_parameters` (e.g. `{"-r": "dev"}`)
1. Setup my fork of …
> WES: Update run workflow to use multipart form data

- app/policies/project_policy.rb
- test/fixtures/groups.yml
- test/fixtures/members.yml
- test/fixtures/namespace_group_links.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/projects.yml
- test/fixtures/routes.yml
- test/fixtures/samples.yml
- test/fixtures/users.yml
- test/policies/project_policy_test.rb
- test/system/workflow_executions/submissions_test.rb
This PR fixes a bug in the `project_policy` -> `submit_workflow?` method, which was passing in the project record instead of the project's namespace as is expected by the `can_submit_workflow?` and `effective_access_level` within the `member.rb` file. 
Added a project_policy and system test to verify an analyst can submit a workflow through a namespace group link as that's how the issue was discovered.
1. Login as `user2@email.com`
2. Create a group `User2Group`
3. Logout and login as `user1@email.com`
4 Create project under user namespace `Project1`
5. Create …
> FIX: Analyst workflow submission

- app/controllers/concerns/bot_actions.rb
- app/controllers/concerns/bot_personal_access_token_actions.rb
- app/controllers/projects/bots/personal_access_tokens_controller.rb
- app/policies/namespaces/project_namespace_policy.rb
- app/services/bots/create_service.rb
- config/locales/en.yml
- config/routes/project.rb
- test/controllers/concerns/bot_actions_concern_test.rb
- test/controllers/concerns/bot_personal_access_token_actions_concern_test.rb
- test/controllers/projects/bots/personal_access_tokens_controller_test.rb
- test/controllers/projects/bots_controller_test.rb
This PR adds in a controller and concern for bot personal access tokens. This will help support the UI for generating new personal access tokens, as well as listing the access tokens for a bot account
1. Verify that the tests pass
> Bot personal access token controller

- app/controllers/concerns/bot_actions.rb
- app/controllers/groups/bots/personal_access_tokens_controller.rb
- app/controllers/groups/bots_controller.rb
- app/models/concerns/has_user_type.rb
- app/models/group.rb
- app/policies/group_policy.rb
- app/services/bots/create_service.rb
- app/services/bots/destroy_service.rb
- config/locales/en.yml
- config/routes/group.rb
- test/controllers/concerns/bot_actions_concern_test.rb
- test/controllers/concerns/groups_membership_actions_concern_test.rb
- test/controllers/groups/bots_controller_test.rb
- test/fixtures/members.yml
- test/fixtures/namespace_bots.yml
- test/fixtures/personal_access_tokens.yml
- test/fixtures/users.yml
- test/services/bots/create_service_test.rb
- test/services/bots/destroy_service_test.rb
This PR sets up the `bots_controller` and `personal_access_tokens_controller` for groups, as well as, updates the `Group` model to include `has_many` `bots` and `namespace_bots` so we can access the bot user and namespace bot records directly
> Group bot accounts controller

- app/jobs/data_exports/create_job.rb
- app/services/data_exports/create_service.rb
- test/services/data_exports/create_service_test.rb
This PR makes changes to the data export service and job to improve its performance for larger sample numbers.
1. Test export with large number of samples
2. Ensure tests pass
> Data Export - Improve performance

- app/jobs/data_exports/create_job.rb
- app/mailers/application_mailer.rb
- config/environments/development.rb
- config/environments/test.rb
Fix application mailer default from, by using value set in `config/environments/ENVIRONMENT.rb`.
Remove extra project query in `app/jobs/data_exports/create_job.rb`
> Fix: Application Mailer default from

- .vscode/settings.json
- app/services/workflow_executions/create_service.rb
Updates `sanitize_workflow_param` to cast boolean properties as boolean from string, so that correct value is passed in workflow_params.
1. Add a pipeline which has boolean params to config/pipelines/pipelines.json
```json
{
"url": "https://github.com/phac-nml/mikrokondo",
"name": "phac-nml/mikrokondo",
"description": "Mikrokondo beta",
"versions": [
{
"name": "0.1.0"
}
]
}
```
2. Launch server
3. Navigate to a project and select one sample
4. Launch pipeline and select added pipeline from above
5. Submit pipeline
6. In rails console execute the following query …
> Fix Boolean Workflow Params

- app/components/nextflow_component.html.erb
- app/components/nextflow_component.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/controllers/workflow_executions_controller.rb
- app/services/workflow_executions/completion_service.rb
- app/views/workflow_executions/submissions/create.turbo_stream.erb
- config/locales/en.yml
- db/migrate/20240416194657_add_update_samples_to_workflow_executions.rb
- db/schema.rb
- test/fixtures/samples_workflow_executions.yml
- test/fixtures/workflow_executions.yml
- test/services/workflow_executions/completion_service_test.rb
- test/system/workflow_executions/submissions_test.rb
Adds in `update_samples` boolean to `WorkflowExecution` model, which when set to true will update the samples with metadata and files produced by the pipeline.
Updates NextflowComponent to include a `allowed_to_update_samples` boolean which will conditionally display the `update_samples` checkbox.
As a User with `maintainer` or `owner` access for all of the samples
1. Login as your preferred user
2. Go to Projects Dashboard
3. Click on a Project where you have `analyst` role
4. Navigate to Samples page for the Project
5. Select all samples and launch a pipeline …
> Workflow Executions: Update Samples Option

- app/components/nextflow/samplesheet/dropdown_cell_component.html.erb
- app/components/nextflow/samplesheet/metadata_cell_component.html.erb
- app/components/nextflow/samplesheet/metadata_cell_component.rb
- app/components/nextflow/samplesheet/row_component.rb
- app/components/nextflow/samplesheet_component.en.yml
- app/components/nextflow/samplesheet_component.fr.yml
- app/components/nextflow/samplesheet_component.html.erb
- app/components/nextflow/samplesheet_component.rb
- app/components/nextflow_component.html.erb
- app/components/nextflow_component.rb
- app/controllers/workflow_executions/metadata_controller.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/javascript/controllers/nextflow/samplesheet_controller.js
- app/javascript/controllers/sessionstorage_amend_form_controller.js
- app/views/groups/samples/index.html.erb
- app/views/projects/samples/index.html.erb
- app/views/workflow_executions/metadata/fields.turbo_stream.erb
- app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
- app/views/workflow_executions/submissions/create.turbo_stream.erb
- config/environments/development.rb
- config/pipelines/pipelines.json
- config/routes/workflow_executions.rb
- test/components/nextflow_component_test.rb
- test/components/nextflow_samplesheet_component_test.rb
- test/components/previews/nextflow_component_preview/default.html.erb
- test/components/previews/nextflow_samplesheet_component_preview.rb
- test/components/previews/nextflow_samplesheet_component_preview/default.html.erb
- test/fixtures/files/nextflow/samplesheet_schema_meta.json
- test/fixtures/samples.yml
This PR adds the ability for a user to select which metadata field to use for a metadata submission.
- Dropdown added to the sample sheet header for a given field
- Sample cell update with new metadata value once the field is changed.
**Sample Sheet**
**Request payload**
Add the following to `private/pipelines/phac-nml/iridanextexample/1.0.2/schema_input.json` after `reference_assembly`:
```json
"insdc_accession": {
"type": "string",
"pattern": "^(SRR|ERR|DRR)\\S+$",
"meta": ["insdc_accession"],
"errorMessage": "Must provide a valid accession"
},
"country": { …
```
> Workflow Submission: Metadata field selection

- app/controllers/concerns/bot_actions.rb
- app/controllers/concerns/bot_personal_access_token_actions.rb
- app/models/namespace_bot.rb
- app/views/groups/bots/_bot.html.erb
- app/views/groups/bots/_bot_listing.html.erb
- app/views/projects/bots/_bot.html.erb
- app/views/projects/bots/_bot_listing.html.erb
- config/locales/en.yml
- test/controllers/concerns/bot_actions_concern_test.rb
- test/controllers/concerns/bot_personal_access_token_actions_concern_test.rb
- test/controllers/groups/bots_controller_test.rb
- test/controllers/projects/bots/personal_access_tokens_controller_test.rb
- test/controllers/projects/bots_controller_test.rb
This PR updates the bot_actions and bot_personal_access_tokens concerns to find and set the bot account using the namespace_bot id instead of the user id. The UI and testing have also been updated
1. For both projects and groups add a bot account and verify you can delete the bot account
2. Verify tests pass
> Update query to set bot_account

- app/javascript/controllers/transfer_controller.js
- test/system/groups_test.rb
Previously when running this test locally it would fail most of the time. The 1 second sleep fixes this to always pass.
Run the test locally multiple times and verify that it always passes.
> Fix flakey group transfer test

- test/services/workflow_executions/completion_service_test.rb
samples_workflow_executions can populate in any order so sometimes workflow_execution.samples_workflow_executions[0] and workflow_execution.samples_workflow_executions[1] are swapped when the fixtures load them into the db.
> fix flakey completion service tests

- app/models/automated_workflow_execution.rb
- app/models/namespaces/project_namespace.rb
- db/migrate/20240425141711_create_automated_workflow_executions.rb
- db/migrate/20240425163945_add_logidze_to_automated_workflow_executions.rb
- db/schema.rb
- db/triggers/logidze_on_automated_workflow_executions_v01.sql
- test/fixtures/automated_workflow_executions.yml
- test/models/automated_workflow_execution_test.rb
Adds in `AutomatedWorkflowExecution` model which will be used to setup automated pipelines for when Samples have pair end data added to them and a Project has an automated pipeline setup.
Run the tests and verify they pass
> Automated Workflow Executions Model

- app/policies/namespaces/project_namespace_policy.rb
- app/services/automated_workflow_executions/create_service.rb
- app/services/automated_workflow_executions/destroy_service.rb
- app/services/automated_workflow_executions/update_service.rb
- config/locales/en.yml
- test/services/automated_workflow_executions/create_service_test.rb
- test/services/automated_workflow_executions/destroy_service_test.rb
- test/services/automated_workflow_executions/update_service_test.rb
Adds in Create, Update, and Destroy services for AutomatedWorkflowExecution
> Automated Workflow Executions Services

- app/controllers/projects/automated_workflow_executions_controller.rb
- config/routes/project.rb
- test/controllers/projects/automated_workflow_executions_controller_test.rb
This PR adds in the controller for automated workflow executions.
1. Verify the tests pass
> Automated workflow executions controller

- app/components/nextflow/samplesheet/column_component.fr.yml
- app/components/nextflow/samplesheet_component.fr.yml
Added french translation file for column component.
N/A
Log in as a french user and select a pipeline to launch.  Should not crash.
> Workflow Submission: Added french translation file for column component

- app/services/workflow_executions/status_service.rb
This updates state assignment in `WorkflowExecutions::StatusService` to no longer set state to nil when it encounters a state that we explicity don't check for eg. `INITIALIZING`.
> Fix: WorkflowExecutions::StatusService nil state assignment

- app/models/sample.rb
- db/migrate/20240426144141_add_missing_unique_indexes.rb
- db/schema.rb
This PR adds in missing multi field unique indexes. These indexes were previously added but weren't applied as the name attribute was missing.
1. In rails console run `bin/rails db:migrate`
2. In the `db/schema` file verify that the `members`, `namespace_group_links`, and `samples` tables have the multi field unique indexes
> Add missing unique Indexes

- test/models/workflow_execution_test.rb
This PR updates testing the workflow execution model to increase coverage
1. Ensure all tests pass locally
> Workflow Executions: Update Model Tests

- app/components/nextflow_component.html.erb
- app/controllers/workflow_executions_controller.rb
- app/models/workflow_execution.rb
- app/services/automated_workflow_executions/launch_service.rb
- config/schemas/workflow_execution_metadata.json
- db/migrate/20240426160617_add_namespace_ref_to_workflow_execution.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/workflow_executions_controller_test.rb
- test/fixtures/workflow_executions.yml
- test/models/workflow_execution_test.rb
- test/services/workflow_executions/create_service_test.rb
- test/system/workflow_executions_test.rb
Adds a parameter `namespace_id` to the workflow execution params.
1. Login and go to a project that you can execute a workflow from
2. Open developer tools, go to the network tab and select persist logs
3. Select a pipeline and submit
4. In network tab, look at the logs and you should see something similar to: 
Check the rails console after executing a pipeline:
1. Inspect the workflow you just ran: `WorkflowExecution.last`
2. The `namespace_id` should be added to the workflow_execution  …
> Workflow Submission: Add namespace_id to workflow model

- app/components/nextflow_component.html.erb
- app/controllers/projects/automated_workflow_executions_controller.rb
- app/views/layouts/projects.html.erb
- app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
- app/views/projects/automated_workflow_executions/_new_automated_workflow_execution_modal.html.erb
- app/views/projects/automated_workflow_executions/_pipeline_selection_modal.html.erb
- app/views/projects/automated_workflow_executions/_table.html.erb
- app/views/projects/automated_workflow_executions/create.turbo_stream.erb
- app/views/projects/automated_workflow_executions/destroy.turbo_stream.erb
- app/views/projects/automated_workflow_executions/index.html.erb
- app/views/projects/automated_workflow_executions/index.turbo_stream.erb
- app/views/projects/automated_workflow_executions/new.turbo_stream.erb
- config/locales/en.yml
- test/controllers/projects/automated_workflow_executions_controller_test.rb
- test/system/projects/automated_workflow_executions_test.rb
This PR adds in the UI for configuring automated workflow executions for a Project. Currently this includes listing, adding, and deleting of automated workflow executions.
1. Run server
2. Navigate to a Project where you are `Owner` or `Maintainer`
3. Click on `Settings` -> `Automated Workflow Executions`
4. Click on `Add new automated workflow execution`
5. Click on an automatable pipeline (if list is empty ensure that your `config/pipelines/pipelines.json` has at least one pipeline version with `"automatable": true`, refer to default file in repo)
6. Click on …
> Automated Workflow Executions UI

- app/components/nextflow_component.en.yml
- app/components/nextflow_component.fr.yml
- app/components/nextflow_component.html.erb
- app/controllers/projects/automated_workflow_executions_controller.rb
- app/controllers/workflow_executions_controller.rb
- app/models/workflow_execution.rb
- app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
- app/views/projects/automated_workflow_executions/_table.html.erb
- app/views/workflow_executions/_table.html.erb
- app/views/workflow_executions/_workflow_execution.html.erb
- config/locales/en.yml
- config/pipelines/pipelines.json
- db/migrate/20240426160117_add_name_to_workflow_execution.rb
- db/migrate/20240501131412_add_name_to_automated_workflow_execution.rb
- db/schema.rb
- test/components/nextflow_component_test.rb
- test/controllers/projects/automated_workflow_executions_controller_test.rb
- test/fixtures/automated_workflow_executions.yml
- test/models/automated_workflow_execution_test.rb
- test/services/workflow_executions/create_service_test.rb
- test/system/workflow_executions_test.rb
Users can add a custom name to a workflow during the submission process.
**Light Mode**
**Dark Mode**
1. Open the Workflow Submission dialog
2. There should always be a field at the top for a custom name
> Workflow Submission: Add custom name to a workflow execution

- app/models/namespace_bot.rb
- app/models/namespaces/project_namespace.rb
- test/fixtures/namespace_bots.yml
- test/models/attachment_test.rb
- test/models/automated_workflow_execution_test.rb
- test/models/concerns/has_puid_test.rb
- test/models/concerns/has_user_type_test.rb
- test/models/namespace_bot_test.rb
- test/models/namespace_group_link_test.rb
- test/models/namespaces/project_namespace_test.rb
- test/models/namespaces/user_namespace_test.rb
- test/models/project_test.rb
- test/models/route_test.rb
- test/models/sample_test.rb
- test/models/user_test.rb
This PR fills in gaps within the model tests to improve coverage.
1. Ensure tests pass locally
> Update Model Tests

- app/controllers/workflow_executions_controller.rb
- app/views/projects/samples/show.html.erb
- app/views/workflow_executions/_params.html.erb
- app/views/workflow_executions/show.html.erb
- config/locales/en.yml
- test/fixtures/workflow_executions.yml
- test/policies/workflow_execution_policy_test.rb
- test/system/workflow_executions_test.rb
On the workflow execution show page we added a tab to display the parameters used in the execution.
**Light**
**Dark**
**No pipeline parameters**
1. Go to http://localhost:3000/-/workflow_executions and click on a workflow
2. Ensure there is a tab `Parameters`
3. Clicking on the tab should display a rendering of all the parameters that were used.
> Workflow execution  show: Display pipeline parameters

- app/controllers/projects/workflow_executions_controller.rb
- app/policies/namespaces/project_namespace_policy.rb
- config/locales/en.yml
- config/routes/project.rb
- test/controllers/projects/workflow_executions_controller_test.rb
- test/policies/namespaces/project_namespace_policy_test.rb
This PR adds in the workflow executions controller for projects and sets up the route
1. Verify that the tests pass
> Project workflow executions controller

- app/controllers/concerns/membership_actions.rb
- app/controllers/dashboard_controller.rb
- app/views/dashboard/index.html.erb
- app/views/layouts/devise.html.erb
- test/controllers/dashboard_controller_test.rb
- test/fixtures/namespaces/user_namespaces.yml
- test/fixtures/routes.yml
- test/system/projects/members_test.rb
Currently when logging in the user was directed to a strange page that just said "Stranger Danger".  Now when the user logs in they go directly to the projects dashboard page.
None needed.
1. Login and see where you end up.
> Redirect dashboard index to dashboard projects

- app/mailers/pipeline_mailer.rb
- app/models/member.rb
- app/models/workflow_execution.rb
- app/views/mailers/pipeline_mailer/complete_manager_email.html.erb
- app/views/mailers/pipeline_mailer/complete_user_email.html.erb
- app/views/mailers/pipeline_mailer/error_manager_email.html.erb
- app/views/mailers/pipeline_mailer/error_user_email.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/fixtures/members.yml
- test/fixtures/workflow_executions.yml
- test/mailers/pipeline_mailer_test.rb
- test/mailers/previews/pipeline_mailer_preview.rb
- test/models/workflow_execution_test.rb
- test/services/workflow_executions/completion_service_test.rb
- test/services/workflow_executions/status_service_test.rb
Sends user email to human pipeline submitter & sends manager emails if automated pipeline was submitted by bot.
Fixes #575.
Pipeline completed manger email:
Pipeline errored manger email:
1. Install local mock email service, [Mailhog](https://github.com/mailhog/MailHog).
2. After setup, open a terminal and run `~/go/bin/MailHog`.
3. Run irida-next.
4. Login as `user1@email.com`
5. Create a personal project named `test awe`
6. Add a few owners and maintainers to the project.
7. Open a rails console and execute the following to add an automated workflow execution:
```irb
AutomatedWorkflowExecutions::CreateService.new(User.find_by(email: 'user1@email.com'), { namespace: Namespaces::ProjectNamespace.find_by_full_path('user1_at_email.com/test-awe'), metadata: { workflow_name: …
```
> Adding manager email templates to pipeline mailer

- app/components/nextflow_component.html.erb
- app/components/nextflow_component.rb
- app/controllers/projects/automated_workflow_executions_controller.rb
- app/helpers/nextflow_helper.rb
- app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
- app/views/projects/automated_workflow_executions/_edit_dialog.html.erb
- app/views/projects/automated_workflow_executions/_table.html.erb
- app/views/projects/automated_workflow_executions/update.turbo_stream.erb
- config/locales/en.yml
- test/system/projects/automated_workflow_executions_test.rb
Allow an owner to update the parameters used for running a pipeline
Edit Button:
**Light**
**Dark**
1. Created an automated workflow execution within a project
2. Within the table, click on the edit button on the far right for the automated workflow execution that you just created.
3. Updated whichever parameters you want and click `Update` button.
4. The changes should be reflected in the table, or click `Edit` again and the changes you made should be there. …
> Automated Workflow Executions: Update

- app/controllers/concerns/workflow_execution_actions.rb
- app/controllers/projects/workflow_executions_controller.rb
- app/controllers/workflow_executions_controller.rb
- app/models/member.rb
- app/policies/workflow_execution_policy.rb
- app/views/layouts/projects.html.erb
- app/views/projects/workflow_executions/_attachment.html.erb
- app/views/projects/workflow_executions/_files.html.erb
- app/views/projects/workflow_executions/_pagination.html.erb
- app/views/projects/workflow_executions/_params.html.erb
- app/views/projects/workflow_executions/_summary.html.erb
- app/views/projects/workflow_executions/_table.html.erb
- app/views/projects/workflow_executions/_workflow_execution.html.erb
- app/views/projects/workflow_executions/cancel.turbo_stream.erb
- app/views/projects/workflow_executions/destroy.turbo_stream.erb
- app/views/projects/workflow_executions/index.html.erb
- app/views/projects/workflow_executions/index.turbo_stream.erb
- app/views/projects/workflow_executions/show.html.erb
- config/locales/en.yml
- test/controllers/projects/workflow_executions_controller_test.rb
- test/controllers/workflow_executions_controller_test.rb
- test/fixtures/samples_workflow_executions.yml
- test/fixtures/workflow_executions.yml
- test/policies/workflow_execution_policy_test.rb
- test/system/projects/workflow_executions_test.rb
This PR sets up the UI for project workflow executions
1. Login as any user
2. Create a new project
3. Go to the settings for the project and from the expanded menu select `Automated Workflow Executions`
4. Add a new automated workflow execution (this will launch automatically whenever paired-end data is added to a sample in the project)
5. Go to the samples page for the project and create a new sample
6. Upload paired end data to the sample
7. Go to the `Workflow Executions` page for the project
8. You should see the workflow execution has been launched
9. Add …
> Project workflow executions UI

- app/services/samples/metadata/file_import_service.rb
- lib/irida/persistent_unique_id.rb
- test/fixtures/files/metadata/valid_with_puid.csv
- test/services/samples/metadata/file_import_service_test.rb
Updates Samples::Metadata::FileImportService to allow import metadata to Samples by PUID.
Test importing a metadata spreadsheet using Sample PUIDs
> Metadata File Import: Allow Sample PUIDs

- app/components/viral/page_header_component.html.erb
- app/components/viral/page_header_component.rb
- app/helpers/pill_color_helper.rb
- app/views/projects/workflow_executions/_summary.html.erb
- app/views/projects/workflow_executions/_table.html.erb
- app/views/projects/workflow_executions/_workflow_execution.html.erb
- app/views/projects/workflow_executions/show.html.erb
- app/views/workflow_executions/_summary.html.erb
- app/views/workflow_executions/_table.html.erb
- app/views/workflow_executions/_workflow_execution.html.erb
- app/views/workflow_executions/show.html.erb
- config/locales/en.yml
- test/system/projects/workflow_executions_test.rb
- test/system/workflow_executions_test.rb
This PR updates the workflow executions tables to reorder the columns, and the state column has been updated to display badges. The summary page for a workflow execution has also been updated to display the optional name if set
1. Run a workflow execution
2. View the workflow executions table (global) and verify the state column is now the 3rd column and has a viral pill
3. Run an automated workflow execution from a project
4. View the project workflow executions table and verify the state column is now the 3rd column and has a viral pill
5. View the summary …
> Update workflow executions tables

- app/views/groups/members/_member.html.erb
- app/views/groups/members/_member_listing.html.erb
- app/views/groups/samples/_table.html.erb
- app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
- app/views/projects/members/_member.html.erb
- app/views/projects/members/_member_listing.html.erb
- app/views/projects/samples/_table.html.erb
- app/views/projects/samples/attachments/_attachment.html.erb
- app/views/projects/samples/attachments/_table.html.erb
- app/views/projects/workflow_executions/_attachment.html.erb
- app/views/projects/workflow_executions/_files.html.erb
- app/views/workflow_executions/_files.html.erb
- test/system/groups/members_test.rb
- test/system/projects/samples_test.rb
- test/system/projects/workflow_executions_test.rb
- test/system/workflow_executions_test.rb
General cleanup of table styling, including:
- Headers
- Footers
- Links
- Font sizes
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
**Before**
**After**
> Table style cleanup

- app/components/nextflow/samplesheet/column_component.rb
Fix:es Samplesheet Other File Cell rendering when Sample has no Files
> Fix: Samplesheet Other File Cell rendering when Sample has no Files

- app/components/namespace_tree/row/row_contents_component.fr.yml
- app/components/viral/form/select_component.fr.yml
- app/helpers/pill_color_helper.rb
- app/views/data_exports/_data_export.html.erb
- app/views/data_exports/_summary.html.erb
- app/views/groups/members/index.html.erb
- app/views/layouts/application.html.erb
- app/views/profiles/_form.html.erb
- app/views/profiles/passwords/_form.html.erb
- app/views/profiles/personal_access_tokens/_form.html.erb
- app/views/profiles/personal_access_tokens/index.html.erb
- app/views/projects/bots/_bot_modal.html.erb
- app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
- app/views/projects/members/index.html.erb
- app/views/projects/samples/attachments/_form.html.erb
- app/views/projects/samples/metadata/file_imports/_dialog.html.erb
- app/views/shared/alert/list/_danger.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/system/data_exports_test.rb
This PR adds in missing translations
> Add missing translations

- app/components/nextflow_component.html.erb
- app/controllers/concerns/workflow_execution_actions.rb
- app/controllers/projects/automated_workflow_executions_controller.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/helpers/nextflow_helper.rb
- app/services/automated_workflow_executions/launch_service.rb
- app/services/workflow_executions/create_service.rb
- app/services/workflow_executions/preparation_service.rb
- app/views/workflow_executions/_params.html.erb
- config/initializers/pipelines.rb
- lib/irida/pipelines.rb
- test/lib/irida/pipelines_overrides_test.rb
- test/lib/irida/pipelines_schema_test.rb
- test/lib/irida/pipelines_test.rb
> [DFCT0010053] Fix labels when showing parameter summary

- app/helpers/blob_helper.rb
- app/services/workflow_executions/cleanup_service.rb
- app/services/workflow_executions/preparation_service.rb
- db/migrate/20240508171227_add_cleaned_boolean_workflow_execution.rb
- db/schema.rb
- test/fixtures/files/samplesheet.csv
- test/services/workflow_executions/cleanup_service_test.rb
- test/test_helpers/blob_test_helpers.rb
Related to #521
Adds `WorkflowExecutions::CleanupService`
This service deletes all blobs under the `workflow_execution.blob_run_directory`. These are the intermediate and output files made during the workflow executions lifespan. The files we keep are put into new blobs in the completion service, so this cleans up the unneeded files.
Also moves some blob related functions out of services and into blob_helper.rb to simplify code to be reusable in tests.
1. Start IRIDA and run Sapporo
2. run an execution workflow via the web interface
3. wait for the run to be …
> [ENHC0010012] Workflow executions/cleanup Service

- docs-site/docs/user/export/export-types.md
- docs-site/docs/user/export/getting-started.md
- docs-site/docs/user/export/working-with-exports.md
This PR adds the user documentation for data exports
1. Start the docs in a terminal within your `irida-next` repo with:
```
cd docs-site
pnpm build
npm run serve
```
2. Follow the exports documentation and see if it makes sense from a user's perspective.
3. Check that links navigate to the correct pages.
> Docs: Add Data Export User Docs

- docs-site/docs/user/project/samples/manage-samples.md
This PR adds the user documentation for sample cloning.
1. In a terminal, start the docs with the following commands:
```
cd docs-site
pnpm build
npm run serve
```
2. Within a browser, navigate to [http://localhost:4000/irida-next/docs/user/project/samples/manage-samples#clone-samples](http://localhost:4000/irida-next/docs/user/project/samples/manage-samples#clone-samples).
3. Read the `Clone samples` documentation and see if it makes sense from a user's perspective.
> Docs: Clone samples

- .tool-versions
- docs-site/docusaurus.config.js
- docs-site/package.json
- docs-site/pnpm-lock.yaml
1. Update to latest Docusaurus `3.4.0`
2. Updated React `18.2.0`
3. Fixed issues with `prism-react-render` themes in `docusaurus.config.js`
Within `docs-site` directory:
1. `pnpm clear`
2. `pnpm install`
3. `pnpm build`
4. `pnpm start`
> Documentation site dependency update

- docs-site/docs/user/organization/groups/bot-accounts/bot-accounts-intro.md
- docs-site/docs/user/organization/groups/bot-accounts/manage-bot-accounts.md
- docs-site/docs/user/organization/groups/bot-accounts/manage-bot-personal-access-tokens.md
- docs-site/docs/user/organization/groups/bot-accounts/purpose.md
- docs-site/docs/user/organization/groups/bot-accounts/types.md
- docs-site/docs/user/project/projects/bot-accounts/bot-accounts-intro.md
- docs-site/docs/user/project/projects/bot-accounts/manage-bot-accounts.md
- docs-site/docs/user/project/projects/bot-accounts/manage-bot-personal-access-tokens.md
- docs-site/docs/user/project/projects/bot-accounts/purpose.md
- docs-site/docs/user/project/projects/bot-accounts/types.md
- test/system/data_exports_test.rb
This PR adds the user documentation for bot accounts.
1. In a terminal, start the docs with the following commands:
```
cd docs-site
pnpm build
npm run serve
```
2. Within a browser, navigate to [http://localhost:4000/irida-next/docs/user/organization/groups/bot-accounts/introduction](http://localhost:4000/irida-next/docs/user/organization/groups/bot-accounts/introduction) & [http://localhost:4000/irida-next/docs/user/project/projects/bot-accounts/introduction](http://localhost:4000/irida-next/docs/user/project/projects/bot-accounts/introduction).
3. Read all the `Bot accounts` documentation under groups & projects and see if it makes sense from a user's perspective.
This checklist encourages …
> Docs: Bot accounts

- README.md
This PR fixes errors in the README file.
Follow the README documentation to create a fresh setup.
> Fix errors in the README file

- .github/workflows/docs-site.yml
- config/storage.yml
- docs-site/docs/configuration/options.md
- docs-site/docs/configuration/storage.md
This PR adds documentation for configuring storage and some additional options.
1. Start docs with the following
```bash
cd docs-site
pnpm build
npm run serve
```
2. In a browser, view the new docs pages
3. Check that the information makes sense from an IRIDA Next admin perspective.
> Documentation for storage and extra ENV options

- docs-site/docs/user/organization/members/member-permissions.md
This PR updates the permissions table of the user docs
1. Start the docs in a terminal within your `irida-next` repo with:
```
cd docs-site
pnpm build
npm run serve
```
2. Read the documentation and see if it makes sense from a user's perspective.
> Docs: Permissions Table

- app/controllers/concerns/workflow_execution_actions.rb
- app/services/workflow_executions/preparation_service.rb
- app/views/workflow_executions/_samplesheet.html.erb
- lib/irida/pipeline.rb
- test/fixtures/workflow_executions.yml
Fixes issue where anything besides a fastq file was rendered incorrectly.
Launch pipeline requiring input files.  Ensure that once it is launch, on the samplesheet tab, files are rendered properly.
> Fix: Rendering files in samplesheet component (ENHC0010030)

- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- docs-site/docs/configuration/options.md
This PR adds in configuration to the development, production, and test environments which rotates the log files as they get quite large. Currently this is disabled for development and test environments, but for production the config is set to rotate the files daily. Note that rotate here means creates a new log file and archives the previous day's log.
An examples of test log files created locally by enabling log rotation for the test environment
There are a couple of ways to verify this:
1) Enable the configuration for creating a new development log file in the …
> Daily log rotation

- app/components/namespace_tree/row/row_contents_component.html.erb
- app/components/samples/table_component.html.erb
- app/controllers/data_exports_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/projects_controller.rb
- app/views/shared/project/_row.html.erb
- test/controllers/projects_controller_test.rb
- test/system/dashboard/projects_test.rb
- test/system/data_exports_test.rb
- test/system/projects/members_test.rb
- test/system/projects_test.rb
Updated all project details links to project samples links.
Controller redirects, email templates & layout menus are not included.
Fixes #681.
Project Dashboard:
Group Details:
Group Samples Table:
*Note: Updated project column to display puid.*
Data Export Preview:
Verify all project details links are updated to project samples links.
> Update project links

- app/graphql/irida_schema.rb
- app/graphql/schema.graphql
- app/graphql/types/user_type.rb
- test/graphql/node_query_test.rb
- test/graphql/nodes_query_test.rb
Updates node(s) relay queries to support querying for users and attachments.
> GraphQL: Update node(s) query to support User and Attachment Types

- Gemfile
- Gemfile.lock
- db/jobs_migrate/20240814150153_create_good_job_process_lock_ids.rb
- db/jobs_migrate/20240814150154_create_good_job_process_lock_indexes.rb
- db/jobs_migrate/20240814150155_create_good_job_execution_duration.rb
- db/jobs_schema.rb
- test/system/projects/samples_test.rb
- test/system/projects/workflow_executions_test.rb
- test/system/workflow_executions_test.rb
Upgrade GoodJob to version v3.99.1 and run migrations to prepare for GoodJob 4.X upgrade.
1. Run `bundle` to install latest gems
2. Run `bin/rails db:migrate` to perform migrations
3. Launch server
4. Submit a workflow and ensure that it is prepared which means that the jobs are working as expected
> Dependencies: GoodJob v3.99.1

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
Updates GoodJob from 3.99.1 to 4.1.1. 
No other changes required in how we are using GoodJob as we were already prepared for the upgrade from the prior PR.
> Dependencies: GoodJob 4.1.1

- app/jobs/data_exports/create_job.rb
- test/jobs/data_exports/create_job_test.rb
Fixes #695 
Example Output of `manifest.txt`
```txt
Samples Export
2024-08-14
contents:
83c2d856-9924-496d-8628-9b97d01a56ee/
├─ INXT_PRJ_AYINCIYSP6/ (Outbreak 2022)
│  ├─ INXT_SAM_AYINCIYSVZ/ (Yersinia pseudotuberculosis/Outbreak 2022 Sample 2)
│  │  ├─ INXT_ATT_AYINBXGCXT/
│  │  │  ├─ 08-5578-small_S1_L001_R1_001.fastq.gz
│  │  │  └─ 08-5578-small_S1_L001_R2_001.fastq.gz
│  │  └─ INXT_ATT_AYINCIYSXQ/
│  │     └─ reference.fasta
│  └─ INXT_SAM_AYINCIYSZA/ (Yersinia pseudotuberculosis/Outbreak 2022 Sample 3)
│     ├─ INXT_ATT_AYINCIYS24/
│     │  └─ reference.fasta
│     └─ INXT_ATT_AYINBXGC26/
│        ├─ …
```
> Export Service - add simple manifest file, manifest.txt

- .github/workflows/docs-site.yml
- .github/workflows/ruby.yml
- .github/workflows/sapporo.yml
- .octocov.yml
- app/components/samples/table_component.html.erb
- app/components/workflow_executions/table_component.html.erb
- app/javascript/application.js
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
Update Github Actions to latest versions.
Replace `simplecov-report-action` with `octocov-action`.
Fix bug on Samples and WorkflowExecutions table with localtime not updating correctly (remove data-turbo-permanent and not watch for turbo:morph event to then run localtime js)
See that flaky tests pass and that actions run and coverage is reported in PR
> Github Actions: Dependencies update

- app/components/viral/pagy/pagination_component.html.erb
- app/components/viral/pagy/pagination_component.rb
- test/components/previews/viral_pagy_limit_component_preview.rb
- test/components/previews/viral_pagy_pagination_component_preview.rb
- test/components/viral/pagy_limit_component_preview_test.rb
- test/components/viral/pagy_pagination_component_preview_test.rb
- test/system/groups/samples_test.rb
Fixes dark mode issues with pagy pagination component
> Fixed dark mode issues with Pagy Pagination Component

- app/assets/stylesheets/application.tailwind.css
- app/components/samples/table_component.html.erb
- app/components/samples/table_component.rb
- app/views/groups/samples/index.html.erb
- app/views/projects/samples/index.html.erb
- test/system/projects/samples_test.rb
Fixed some contrast issues in dark mode on samples table.
Refactored samples listing to have a scrollable table with fixed header and footer, which shrinks so that page does not take more than viewport. Also customized scrollbar to display properly in safari (style also applies to Chrome, but not firefox).
2. Go to a Group with lots of samples
3. Toggle metadata then change page size to 100
4. Verify that page doesn't scroll, and that the table scrolls horizontally vertically. …
> Samples table fixed header and footer

- app/views/groups/_form_fields.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Adds more client-side validation to the new group form.  Enforces:
1. Min and max length on name and path
2. Characters allowed within the group name
1. Go to http://localhost:3000/-/groups/new
2. Try different ways of creating a group to ensure that the validation is working correctly, incorrect names/paths should not be submitted.
> Enforce min length and characters on client side for group creation

- app/graphql/resolvers/project_samples_resolver.rb
- app/graphql/resolvers/sample_attachments_resolver.rb
- app/graphql/schema.graphql
- app/graphql/types/attachment_filter_input_type.rb
- app/graphql/types/attachment_order_input_type.rb
- app/graphql/types/order_direction_type.rb
- app/graphql/types/project_type.rb
- app/graphql/types/sample_type.rb
- app/models/attachment.rb
- config/initializers/active_storage.rb
- test/fixtures/attachments.yml
- test/graphql/attachments_query_test.rb
Updates the `SamplesAttachmentsResolver` to accept a `filter` and `orderBy` argument, which allows the users to filter the attachments (e.g. filename ends with) and order the results (e.g. created_at desc).
1. Create a new Project with a new Sample
2. Update 2 sets of `fastq.gz` files and one `csv` file to sample.
3. Execute the following query to only retrieve the `fastq.gz` files:
```graphql
query sample) {
sample(puid: "SAMPLE PUID") {
metadata
attachments(
filter: {filename_end: ".fastq.gz"}
) {
nodes {
id
filename
createdAt
updatedAt
metadata
}
}
}
}
```
4. …
> GraphQL: Samples Attachments filtering and ordering

- app/jobs/data_exports/create_job.rb
- test/jobs/data_exports/create_job_test.rb
This PR fixes a bug where if a sample associated with a workflow execution was deleted, and an analysis export was created for said workflow execution, the export would not complete and stay in the `processing` status. This was due to the export logic checking the sample (which would now be deleted/nil) for its `PUID` and `name`.
Now `PUID` is retrieved from the workflow execution's associated `samples_workflow_execution` for the deleted sample, and `name` is replaced with `Deleted Sample` in the manifest. All expected export files still behave as normal.
New `manifest.json`:
New `manifest.txt`:
1. Set up the ability to run workflow executions locally as described in [PR 507](https://github.com/phac-nml/irida-next/pull/507)
2. Run a  workflow executions with a couple viable samples.
3. …
> Bug Fix: Analysis Export with deleted samples

- app/controllers/concerns/workflow_execution_actions.rb
- app/controllers/projects/automated_workflow_executions_controller.rb
- app/controllers/workflow_executions/submissions_controller.rb
- app/jobs/workflow_execution_preparation_job.rb
- app/services/automated_workflow_executions/launch_service.rb
- app/services/workflow_executions/preparation_service.rb
- config/pipelines/pipelines.json
- lib/irida/pipeline.rb
- lib/irida/pipelines.rb
- test/config/pipelines/pipelines.json
- test/fixtures/workflow_executions.yml
- test/lib/irida/pipelines_test.rb
- test/policies/workflow_execution_policy_test.rb
- test/services/workflow_executions/preparation_service_test.rb
- test/system/workflow_executions_test.rb
This PR allows an administrator of IRIDA Next to specify which versions of pipelines are not executable.
This PR relates to issue #680.
1. Sign in
2. Select Projects on the sidebar and click on a project that is listed
3. Select Samples in the side bar and select one or two of the samples
4. Click the rocket-ship button to start creating a workflow execution
5. Compare the pipelines that are listed with the pipelines listed in `config/pipelines/pipelines.json`
6. Check to see that only the pipelines that do not have the executable option set to `false` are …
> Pipeline config/executable

- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
An attempt to fix the flaky test from the screenshot.
Verify running the above test does not error.
> Fixing flaky test

- app/components/activities/group_activity_component.html.erb
- app/components/activities/list_item_component.html.erb
- app/components/namespace_tree/row/row_contents_component.html.erb
- app/components/project_dashboard/activity_component.html.erb
- app/components/project_dashboard/activity_component.rb
- app/components/project_dashboard/information_component.html.erb
- app/components/project_dashboard/information_component.rb
- app/components/project_dashboard/samples_component.html.erb
- app/components/project_dashboard/samples_component.rb
- app/components/project_dashboard_component.html.erb
- app/components/project_dashboard_component.rb
- app/components/samples/table_component.html.erb
- app/components/viral/tooltip_component.html.erb
- app/controllers/data_exports_controller.rb
- app/controllers/projects_controller.rb
- app/views/projects/show.html.erb
- app/views/shared/project/_row.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/previews/project_dashboard_component_preview.rb
- test/components/previews/project_dashboard_component_preview/default.html.erb
- test/components/project_dashboard_component_test.rb
- test/controllers/projects_controller_test.rb
- test/system/dashboard/projects_test.rb
- test/system/data_exports_test.rb
- test/system/projects/group_links_test.rb
- test/system/projects/members_test.rb
- test/system/projects_test.rb
This PR adds in the latest activity, latest samples updated (both display last 10 items), and basic project information such as description, number of samples, number of automated workflow executions setup, number of members, and date created to the project details page. **Note: Previous change to have links take user to the project samples page by default when visiting a project have now been reverted back to the project details page**
1. Create a project
2. Do a bunch of actions (Add/remove members and shared groups, add samples, update samples, attach files …
> Project details UI

- app/components/samples/table_component.html.erb
- app/components/viral/empty_state_component.html.erb
- app/components/viral/pagy/full_component.html.erb
- app/components/viral/pagy/full_component.rb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/previews/viral_pagy_full_component_preview.rb
- test/components/viral/empty_component_test.rb
- test/components/viral/pagy_full_component_preview_test.rb
- test/system/data_exports_test.rb
- test/system/projects/samples_test.rb
When searching for samples, and there were no results, the empty state was just the table footer, which made no sense.  Here we check to see if there should be samples (checking `@pagy.vars[:size]`) and ensuring `@pagy.count.positive?`.
**Before search**
**Search with no results**
**Empty state (No samples in project)**
1. Go to a project that has samples and perform a search for something that is not in the project, I recommend `foobar`
2. Pagy should render the `No items found` message
3. Create a new project and go to the samples page
4. Page should render …
> Enhancement: Created empty search state

- app/components/project_dashboard/information_component.html.erb
- app/components/project_dashboard_component.html.erb
Updated styles on project details page to render properly in dark mode
> Fixed dark mode on project details page

- app/views/groups/bots/_bot_modal.html.erb
- app/views/projects/bots/_bot_modal.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Updated translations for group/project bot accounts listing description and new bot account modal to clarify what the bot accounts are for/what details are used to create the account
> Updated bot translations

- app/controllers/concerns/attachment_actions.rb
- app/controllers/groups/attachments_controller.rb
- app/controllers/projects/attachments_controller.rb
- config/locales/en.yml
- config/locales/fr.yml
Because project and group attachments share the same actions, this PR now migrates those actions into a single concern.
In both project and group attachments, test the following attachment functionality:
1. Index listing
2. Uploading
3. Deletion
4. Table sort and filtering
Ensure they function as expected, and all dialog text are as expected.
> Namespace Attachments: Attachment Actions Concern

- app/controllers/dashboard/projects_controller.rb
- app/views/dashboard/projects/index.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/system/dashboard/projects_test.rb
Allows the user to filter the projects dashboard page by puid or name
1. Go to projects dashboard page
2. Try filtering by any of the puids displayed on the page
> Filter by name or puid to projects dashbaord

- config/locales/en.yml
- config/locales/fr.yml
- docs-site/docs/user/organization/groups/bot-accounts/manage-bot-accounts.md
- docs-site/docs/user/project/projects/bot-accounts/manage-bot-accounts.md
- test/system/groups/bots_test.rb
- test/system/projects/bots_test.rb
This PR updates 'Remove' to 'Delete bot' on settings bot accounts page to help clarify the delete action between the removal of the bot membership on the members page and the bot account in the settings. The confirmation modal was also updated to advise the user that the deletion of the bot account is permanent. Bot documentation was updated to reflect these changes
> [ENHC0010081] Update bot account 'Remove' text

- docs-site/docs/user/organization/groups/bot-accounts/_category_.json
- docs-site/docs/user/organization/groups/group-files.md
- docs-site/docs/user/organization/members/member-permissions.md
- docs-site/docs/user/project/projects/bot-accounts/_category_.json
- docs-site/docs/user/project/projects/project-files.md
This PR adds new documentation for both group and project files.
1. Build the docs
```
cd docs-site
pnpm update
pnpm build
npm run serve
```
2. Read and verify the docs are accurate
- Groups: Use IRIDA Next > Set up your organization > Groups > Group Files
- Projects: User IRIDA Next > Organize work with projects > Projects > Project Files
> Docs: Namespace Attachments

- app/assets/stylesheets/application.tailwind.css
- app/components/list_filter_component.html.erb
- app/components/viral/dialog_component.html.erb
- app/javascript/controllers/list_filter_controller.js
- config/locales/en.yml
- config/locales/fr.yml
- test/system/projects/samples_test.rb
This PR adds a new button to the footer of the filter by sample names or id dialog (`Cancel`) 
> feat: Added cancel button to filter by name or puid

- app/components/attachments/dialogs/new_attachment_component.html.erb
- test/system/groups/attachments_test.rb
- test/system/projects/attachments_test.rb
- test/system/projects/samples_test.rb
Fixes flaky tests on main:
1. Project Attachments 'user with proper access can upload file'
2. Groups Attachments 'user with proper access can upload file'
3. Project Samples 'should update pagination & selection during transfer samples'
> Fix flaky projects samples and attachments tests

- docs-site/docs/user/export/getting-started.md
- docs-site/docs/user/export/working-with-exports.md
- docs-site/docs/user/organization/members/member-permissions.md
This PR updates the Data Export docs to include Linelist exports
1. Build the docs
```
cd docs-site
pnpm update
pnpm build
npm run serve
```
2. Read and verify the docs are accurate (Use IRIDA Next > Export your data)
> Docs: Update Data Exports

- app/components/samples/table_component.rb
- app/controllers/groups/samples_controller.rb
- app/controllers/projects/samples_controller.rb
- app/views/groups/samples/_table.html.erb
- app/views/projects/samples/_table.html.erb
… table during metadata search
Update samples search to highlight the name or puid when the search term contains both a `string` for `:name_or_puid_cont` **and** a metadata query.
1. Go to http://localhost:3000/-/groups/yersinia/-/samples?limit=20
2. Enter `Sample 2 food:tacos` into the search input and press `Enter`
3. Should see an example of the screenshot above
> Updated highlighting on project and groups samples pages when search by name or puid AND a metadata field

- app/components/namespace_tree/row/row_contents_component.html.erb
- app/views/shared/project/_row.html.erb
- test/components/activity_component_test.rb
- test/fixtures/activities.yml
- test/system/dashboard/projects_test.rb
- test/system/groups_test.rb
This PR adds missing UI tests for projects samples_count on the dashboard projects page and the Subgroups and projects tab.
> UI Tests: projects samples_count 

- app/graphql/resolvers/pipeline_resolver.rb
- app/graphql/resolvers/pipelines_resolver.rb
- app/graphql/schema.graphql
- app/graphql/types/pipeline_type.rb
- app/graphql/types/query_type.rb
- db/schema.rb
- test/graphql/pipeline_query_test.rb
- test/graphql/pipelines_query_test.rb
Adds the ability to query pipelines via graphql
1. Test that all pipelines can be queried.
```graphql
query getPipelines {
pipelines(workflowType: "available"){
automatable
description
engine
engineVersion
executable
name
type
typeVersion
url
version
}
}
```
2. Test that a specific pipeline can be queried.
```graphql
query getPipeline {
pipeline(workflowName:"phac-nml/iridanextexample",workflowVersion:"1.0.3"){
automatable
description
engine
engineVersion
executable
metadata
name
type
typeVersion
url
version
workflowParams
}
}
``` …
> GraphQL: add queries for getting pipelines

- .github/workflows/docker-publish.yml
- Dockerfile
Fixes issue in Dockerfile that was preventing build.
Adds in Docker github action to build on PRs and push to ghcr.io on push to main.
> Docker: Publish to ghcr.io

- .github/workflows/sapporo.yml
Updates `Sapporo CI` config to use `GET` request instead of `HEAD` to get that sapporo is up before proceeding with tests.
> Fix: Sapporo CI

- test/system/dashboard/projects_test.rb
- test/system/data_exports_test.rb
- test/system/groups/attachments_test.rb
- test/system/groups/samples_test.rb
- test/system/groups_test.rb
- test/system/projects/attachments_test.rb
- test/system/projects/samples_test.rb
Refactors existing flaky tests that are holding up PRs
1. Run `bin/rails test:all` multiple times and confirm no failures.
> Fix: Various flaky tests

- app/views/workflow_executions/_summary.html.erb
- app/views/workflow_executions/show.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Updated workflow execution show page header by fixing the copy-able id with the workflow execution ID and moving the state down to the summary.
> Updated workflow execution show page to have copy-able  UUID instead of state

- docs-site/README.md
- docs-site/docs/user/organization/namespaces.md
- docs-site/docusaurus.config.js
- docs-site/package.json
- docs-site/pnpm-lock.yaml
Updates to docusaurus 3.6.3 for docs-site.
Enabled experimental faster option for docusaurus which does not introduce any errors from my manual testing of the docs-site.
1. Change to docs-site directory in terminal `cd docs-site`
2. Install dependencies `pnpm install --frozen-lockfile`
3. Test development build `pnpm start`
4. Test build `pnpm build`
> Docusaurus 3.6.3

- app/javascript/controllers/datepicker_controller.js
Add in custom IridaNextDatepicker which subclasses Datepicker from Flowbite to allow passing in `container` option which fixes element in Dialogs.
> Fix: Add IridaNextDatepicker override to fix Datepicker in Dialog

- app/views/workflow_executions/show.html.erb
**On main**
**With fix**
1. Create a workflow execution without a custom name
2. After launching go to the show page for that workflow and ensure the name is there.
> Fixed issue with name not displaying on workflow show page

- Gemfile
- Gemfile.lock
Update view_component gem to version 3.20.0
Tests should cover all cases when view components are used.  Manually check to make sure everything renders well.
> dependency: Update view_component gem to version 3.20.0

- db/seeds.rb
Fixed bug with seeding data exports to database due to hard-coded years for sample names in the `Sample.find_by` queries. 
1. Verify the development database gets seeded without errors
> Fix db seeds

- app/jobs/workflow_execution_cancelation_job.rb
- app/jobs/workflow_execution_preparation_job.rb
- app/jobs/workflow_execution_status_job.rb
- app/jobs/workflow_execution_submission_job.rb
- app/services/data_exports/create_service.rb
- app/services/workflow_executions/cancel_service.rb
- app/services/workflow_executions/cancelation_service.rb
- app/services/workflow_executions/completion_service.rb
- app/services/workflow_executions/create_service.rb
This PR removes are arbitrary queueing delays for all jobs except WorkflowExecution status jobs.
> Chore: Remove queuing delays from all jobs except for status jobs

- app/components/nextflow/samplesheet/column_component.html.erb
Added style `content-visibility: auto;` to the column-component to only render cells when they are within the viewport
N/A
Ensure tables load correctly
> Only render rows when visible within the viewport

- app/views/groups/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
- app/views/groups/bots/personal_access_tokens/_revoke_confirmation_modal.html.erb
- app/views/projects/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
- app/views/projects/bots/personal_access_tokens/_revoke_confirmation_modal.html.erb
- test/system/groups/bots_test.rb
- test/system/projects/bots_test.rb
- test/system/projects/samples_test.rb
This PR refactors the bots tests, fixing selectors to relieve flakiness as well as fix `ID` ambiguity between dialog selectors when multiple dialogs are open.
1. Verify local tests pass
> Refactor: Bots System Tests

- app/views/projects/workflow_executions/_summary.html.erb
- app/views/projects/workflow_executions/show.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/system/projects/workflow_executions_test.rb
Expands upon #847 to update project workflow execution show page
> Updated project workflow execution show page to have copy-able UUID instead of state

- app/services/workflow_executions/create_service.rb
- test/services/workflow_executions/create_service_test.rb
Update `autoset_params` in `WorkflowExecutions::CreateService` to use `merge!` to update the hash in place vs `merge` with returns a new hash with the other hash merged in.
> Fix Autoset Params

- app/controllers/projects/samples/transfers_controller.rb
- app/jobs/samples/transfer_job.rb
- app/services/samples/clone_service.rb
- app/services/samples/transfer_service.rb
- app/views/projects/samples/clones/_dialog.html.erb
- app/views/projects/samples/shared/_errors.html.erb
- app/views/projects/samples/shared/_success.html.erb
- app/views/projects/samples/transfers/_dialog.html.erb
- app/views/projects/samples/transfers/create.turbo_stream.erb
- test/controllers/projects/samples/transfers_controller_test.rb
- test/services/samples/clone_service_test.rb
- test/system/dashboard/projects_test.rb
- test/system/projects/samples_test.rb
Updates Projects::Samples::TransferController to enqueue a new Samples::TransferJob which calls the existing Samples::TransferService to perform the queueing and the new job uses Turbo broadcasts to update the UI with success or errors.
1. Ensure that samples transfer works as expected, e.g. displays errors when unsuccessful, and success messages when successful.
> Async Samples Transfer

- Gemfile
- Gemfile.lock
Updates `azure-blob` dependency to point to [phac-nml/azure-blob](https://github.com/phac-nml/azure-blob), specifically the `copy-blob` branch.
1. Install latest gemfile dependencies `bin/bundle`
2. Update development storage to use azurite (change line 39 in `config/environments/development.rb` from `:local` to `:azurite`
3. Ensure that azurite is running and `irida-next` blob container exists
4. Reset the db with `bin/rails db:reset`
5. Launch the server and submit a workflow execution with a single sample
6. Workflow execution will error when attempting to …
> Deps: phac-nml/azure-blob

- test/jobs/workflow_execution_submission_job_test.rb
- test/system/groups/bots_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
Refactor tests to reduce flakes, a never ending process it seems.
If its green it is good to go
> Flake fixes

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- README.md
- app/models/sample.rb
- app/models/sample/query.rb
- app/services/samples/destroy_service.rb
- config/initializers/pagy.rb
- db/migrate/20241212164410_index_existing_samples.rb
- db/seeds.rb
- test/controllers/groups/samples_controller_test.rb
- test/controllers/projects/samples_controller_test.rb
- test/system/dashboard/groups_test.rb
- test/system/dashboard/projects_test.rb
- test/system/data_exports_test.rb
- test/system/groups/samples_test.rb
- test/system/groups_test.rb
- test/system/projects/samples_test.rb
- test/system/workflow_executions/submissions_test.rb
- test/test_helper.rb
This PR removes the dependency on Searchkick and Opensearch. These dependencies are no longer required for advanced  searching.
Note: Please do not merge until I am given the go ahead from the QA team
1. Confirm that tests pass
2. Confirm that the application works correctly without a running instance of Opensearch
3. Confirm that advanced search still works as expected, and is producing the correct results
> deps: Remove Searchkick and Opensearch

- Gemfile
- Gemfile.lock
- app/components/nextflow_component.html.erb
- app/controllers/workflow_executions_controller.rb
- config/routes/development.rb
- db/migrate/20250210214118_create_flipper_tables.rb
- db/schema.rb
- db/seeds.rb
- test/components/nextflow_component_test.rb
- test/controllers/workflow_executions_controller_test.rb
- test/system/workflow_executions/submissions_test.rb
Adds in [flipper](https://github.com/flippercloud/flipper), which is library that enables feature flags for Ruby.
Currently this moves the workflow execution sharing behind a feature flag named `workflow_execution_sharing`
Before:
After `Flipper.disable(:workflow_execution_sharing)`:
After `Flipper.enable(:workflow_execution_sharing)`:
1. Reset your database with `bin/rails db:reset`
2. Launch the server
3. Login as your user of choice and navigate to your Project of choice
4. Click on `Samples` context menu
5. Select all samples
6. Click on rocketship to launch …
> Flipper feature flagging

- app/javascript/controllers/advanced_search_controller.js
Fixes but where the project advanced search would trigger a close event when chromiums auto-complete was used to populate the value of a field.
N/A
N/A
> Fix advanced search dialog triggering close when auto-completing input

- app/javascript/controllers/advanced_search_controller.js
- test/components/advanced_search_component_test.rb
- test/components/previews/advanced_search_component_preview/default.html.erb
Adds a new `dirty` method to `advanced_search_controller.js` which checks if the form appears to be the same as the original form and then compares the values to ensure it is actually the same.
2. Login as your user of choice then navigate to a Project Samples page
3. Click advanced search button
4. Select a field, then click `x` this should prompt for a confirm (outside of this branch it would close automatically) …
> Advanced Search Close better Dirty Check

- Gemfile.lock
Updates to version of azure-blob fork that only uses copy instead of compose for files <= 256MiB.
> deps: Azure Blob

- app/graphql/schema.graphql
- app/graphql/types/pipeline_type.rb
- docs-site/docs/extend/graphql_workflow_submission.md
- test/graphql/pipeline_query_test.rb
- test/graphql/pipelines_query_test.rb
* remove unneeded fields from graphql pipeline query
* added tutorial for submitting pipelines via GraphQL
The following queries should work, now without the removed fields.
```graphql
query getPipelines {
pipelines(workflowType: "available"){
executable
name
version
}
}
query getPipelineInfo {
pipeline(workflowName:"phac-nml/iridanextexample",workflowVersion:"1.0.3"){
automatable
description
executable
metadata
name
version
workflowParams
}
}
```
Building the docs and running them should result in a new page under `extend/`
```bash
cd docs-site
pnpm update
pnpm …
```
> Graphql: Pipeline updates

- app/components/nextflow/samplesheet_component.html.erb
Updated `data-action` on samplesheet search input to use `search` event instead of `keydown.enter`. This event fires on `Enter` or when the user clicks the `x` in the input, which means that if the user clicks `x` they no longer have to hit enter when inside the input.
> Clear filtered samplesheet when clicking `x`

- app/components/viral/sortable_lists_component.html.erb
- app/components/viral/sortable_lists_component.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/metadata_template_actions.rb
- app/controllers/data_exports_controller.rb
- app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
- app/views/data_exports/_new_linelist_export_dialog.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- db/schema.rb
- test/controllers/concerns/metadata_templates_actions_concern_test.rb
- test/fixtures/metadata_templates.yml
- test/policies/metadata_templates_policy_test.rb
- test/system/projects/metadata_templates_test.rb
- test/system/projects/samples_test.rb
Allow users to select a metadata template during the linelist export process to simplify metadata field selection.
> Metadata Template Field Selection on Linelist Export

- test/jobs/workflow_execution_cancelation_job_test.rb
- test/jobs/workflow_execution_status_job_test.rb
- test/jobs/workflow_execution_submission_job_test.rb
> Fix flakey workflow job tests

- app/components/activities/projects/sample_activity_component.html.erb
- app/components/activities/projects/sample_clone_activity_component.html.erb
- app/components/activities/projects/sample_transfer_activity_component.html.erb
- app/components/activities/projects/transfer_activity_component.html.erb
- app/components/activities/workflow_execution_activity_component.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/projects/sample_activity_component_test.rb
- test/components/projects/sample_clone_activity_component_test.rb
- test/components/projects/sample_transfer_activity_component_test.rb
- test/components/projects/transfer_activity_test.rb
- test/components/workflow_execution_activity_component_test.rb
- test/fixtures/activities.yml
This PR moves the html from the project and workflow execution activities translations into the components. 
**Project**
- create/update/destroy
- metadata template create/update/destroy
- sample create/update/destroy
- sample metadata update/destroy
- sample attachments create/destroy
- transfer samples from project to another (verify activity for both projects)
- copy samples from project to another (verify activity for both projects)
- transfer project namespace to a group (verify activity for group and project)
**Workflow Execution**
- Setup automated …
> Remove html styling from activities translations

- app/components/nextflow/samplesheet_component.rb
- app/models/concerns/file_selector.rb
This PR fixes an issue with the Samplesheet File Cell not recognizing pattern from `anyOf`, this has been updated to do the same combination logic as in `app/validators/workflow_execution_samplesheet_params_validator.rb`. Which is to join all patterns with `|` which in regex is `OR` operator.
Not recognizing the patterns from `anyOf` meant that no file could be selected for File Cells that utilize that property.
This also updates `fastq_2` file selection to not include single end files.
1. Create `config/pipelines/development.json` if it doesn't exist.
2. Add …
> Fix: Nextflow Samplesheet File Cell Pattern Recognition

- app/services/samples/batch_file_import_service.rb
- test/fixtures/files/batch_sample_import_with_metadata_valid.csv
- test/fixtures/files/batch_sample_import_with_metadata_with_empty.csv
- test/services/samples/batch_file_import_service_test.rb
* additional headers on the spreadsheet for sample imports will be used as metadata.
1. seed your db
2. Start irida next with command line enabled
3. Sign into User3
4. navigate to http://localhost:3000/borrelia/borrelia-burgdorferi/outbreak-2024/-/samples
5. in the file `test/fixtures/files/batch_sample_import_with_metadata_valid.csv`, edit the project_puid values to match the project we are importing to.
6. run the following in the terminal to import new samples.
```
u = User.all[3];n = Project.all[0].namespace;
filepath = …
```
> add metadata parsing to batch sample import service

- app/views/layouts/devise.html.erb
- app/views/layouts/lookbook.html.erb
- package.json
- pnpm-lock.yaml
- test/test_helpers/axe_helpers.rb
Upgrades axe-core to 4.10 and enables all rules to be tested.
> Deps: axe-core 4.10

- Gemfile
- Gemfile.lock
- config/environments/development.rb
Added `hotwire-spark` as a development dependency.  See [docs](https://github.com/hotwired/spark)
> Hotwire Spark is a live-reloading system for Hotwire applications. It enhances your development feedback loop by detecting source code changes and updating the page smoothly without requiring a manual reload.
1. `bin/bundle`
2. `bin/dev`
3. Go to any page and open the corresponding HTML file.  Make a change to a style or text and the page should automatically morph. …
> dependency: Added hotwire-spark

- app/services/attachments/create_service.rb
- app/services/attachments/destroy_service.rb
- config/initializers/flipper.rb
- config/locales/en.yml
- config/locales/fr.yml
- test/services/attachments/create_service_test.rb
- test/services/attachments/destroy_service_test.rb
This PR adds in activities for attachments uploaded/removed from a project or group.
1. Create a project and group
2. Upload files to the Project and Group
3. Remove files from the Project and Group
4. Verify the activities for attaching and removing files is visible for both project and group
> Activities: Project/Group Attachments

- app/assets/tailwind/application.css
- app/components/layout/sidebar_component.html.erb
- app/components/layout_component.html.erb
- app/javascript/controllers/layout_controller.js
- app/javascript/controllers/viral/dropdown_controller.js
This PR improves the accessibility of the Sidebar Component, and all buttons within the application for keyboard users and users who need to magnify the application.
This includes automatically hiding the sidebar when zoomed in past a width of `80rem` which equates to the `xl` viewport utility breakpoint class. Additionally when toggling the sidebar at this size it will show the sidebar on top of the body instead of pushing the body over. In addition if the sidebar is toggle below `xl` it will auto collapse when the user clicks outside of it, and/or when the tab outside of it.
Before:
After:
_Numbered steps to set up and validate the …
> Sidebar accessibility improvements

- app/controllers/attachments_controller.rb
- app/policies/attachment_policy.rb
- app/views/workflow_executions/_attachment.html.erb
- app/views/workflow_executions/_attachment_actions.html.erb
- test/fixtures/attachments.yml
- test/policies/attachment_policy_test.rb
1. Added permissions checking to ensure the current user can view the attachment
2.  Fixed bug which prevented the display of paired end data
> fix: Attachment preview permissions & preview of paired end files

- app/assets/tailwind/application.css
Fixes styling issue for namespace tree where the branch was displayed with a dark border
1. Log in as user1
2. Go to the groups dashboard
3. Toggle tree branch and see what it looks like ;)
> Fix issue with namespace tree render dark border for namespace-entry

- app/components/attachments/table_component.html.erb
- app/components/attachments/table_component.rb
- app/components/members/table_component.html.erb
- app/components/metadata_templates/table_component.html.erb
- app/components/viral/data_table/column_component.rb
- app/components/viral/data_table_component.html.erb
- app/components/workflow_executions/table_component.html.erb
Updated the following tables:
1. Attachments
2. Members
3. Metadata Templates
4. Data table component
5. Workflow Executions
Table updates included:
- Updated header cell alignment to be right-aligned for better readability.
- Enhanced tbody styling for improved overflow handling and visual separation.
- Adjusted sticky cell properties for better visibility and layout consistency.
- Ensured proper z-index management for sticky elements to avoid overlap issues.
These changes aim to enhance the user experience by improving the table's visual structure and accessibility. 🎨✨
_Numbered steps to set up and validate the change are strongly …
> Update tables accessibility

- app/components/activities/dialogs/sample_clone_activity_dialog_component.html.erb
- app/components/activities/dialogs/sample_clone_activity_dialog_component.rb
- app/components/activities/dialogs/sample_destroy_activity_dialog_component.html.erb
- app/components/activities/dialogs/sample_destroy_activity_dialog_component.rb
- app/components/activities/dialogs/sample_transfer_activity_dialog_component.html.erb
- app/components/activities/dialogs/sample_transfer_activity_dialog_component.rb
- app/components/activities/projects/sample_activity_component.html.erb
- app/components/activities/projects/sample_clone_activity_component.html.erb
- app/components/activities/projects/sample_transfer_activity_component.html.erb
- app/components/activity_component.html.erb
- app/controllers/activities_controller.rb
- app/models/concerns/track_activity.rb
- config/locales/en.yml
- config/locales/fr.yml
- config/routes.rb
- config/routes/activities.rb
- test/components/activities/dialogs/sample_clone_activity_dialog_component_test.rb
- test/components/activities/dialogs/sample_destroy_activity_dialog_component_test.rb
- test/components/activities/dialogs/sample_transfer_activity_dialog_component_test.rb
- test/components/projects/sample_activity_component_test.rb
- test/components/projects/sample_clone_activity_component_test.rb
- test/components/projects/sample_transfer_activity_component_test.rb
- test/controllers/activities_controller_test.rb
- test/fixtures/activities.yml
This PR adds in activity modals which will display the PUIDs for samples cloned, deleted, and transferred.
**Note: In a follow-up PR , sample names will be displayed along with the PUIDs. Requires a bit of a refactor to set the sample names in the activities when they are created**
1. Create 2 projects `ProjA` and `ProjB`
2. Create 10 samples in `ProjA`
3. Transfer 4 samples from `ProjA` to `ProjB`
4. Copy 4 samples from `ProjA` to `ProjB`
5. Select 2 remaining samples in `ProjA` and delete them with the `Delete Samples` button
6. Verify correct samples are …
> Activities: Modals

- app/components/layout_component.html.erb
- app/javascript/controllers/layout_controller.js
- app/views/profiles/passwords/_form.html.erb
- app/views/profiles/personal_access_tokens/_form.html.erb
- app/views/projects/_edit_name_and_description_form.html.erb
- app/views/projects/_project_namespace_fields.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/layout_component_test.rb
- test/system/dashboard/groups_test.rb
- test/system/dashboard/projects_test.rb
Added a `Skip to Content` link. 
STRY0017591
1. Login to irida-next
2. Press the `tab` key.
3. Verify the `Skip to Content` link becomes visible.
4. Click the link.
5. Verify the link navigates to the main content area, bypassing the navigation items.
> Accessibility: Skip to content link

- app/javascript/controllers/colour_mode_controller.js
In PR #1020 I updated the `app/views/shared/_dark_mode_check.html.erb` to have a default theme of system, this conflicted with `colour_mode_controller.js` as that assumed a default theme of `light` if `theme` was unset in local storage.
This PR updates `colour_mode_controller.js` to have a default of `system` instead of `light`.
> Fix: Colour mode default

- app/jobs/attachments_cleanup_job.rb
- app/jobs/data_exports/cleanup_job.rb
- app/jobs/data_exports/create_job.rb
- app/jobs/samples/batch_sample_import_job.rb
- app/jobs/samples/clone_job.rb
- app/jobs/samples/metadata_import_job.rb
- app/jobs/samples/transfer_job.rb
- app/jobs/samples_cleanup_job.rb
- app/jobs/workflow_execution_cancelation_job.rb
- app/jobs/workflow_execution_cleanup_job.rb
- app/jobs/workflow_execution_completion_job.rb
- app/jobs/workflow_execution_preparation_job.rb
- app/jobs/workflow_execution_status_job.rb
- app/jobs/workflow_execution_submission_job.rb
This PR updates jobs to set a priority, by default priority if unspecified is 0. Jobs with a lower numerical priority are executed before jobs with a higher numerical priority.
Job Class | Job Subtype | Queue | Priority (lower number is higher priority) | Note
-- | -- | -- | -- | --
AutomatedWorfklowExecutions::LaunchJob |   | default | 0 | Launched when pair end data is added to a sample and   project has configured automated pipelines (really fast)
UpdatesMembershipsJob |   | default | 0 | Update memberships after group transfer (really fast)
Turbo::Streams::BroadcastJob |   | transactional_messages | 0 | Send UI updates from backend to client (really fast)
Turbo::Streams::ActionBroadcastJob |   | transactional_messages | 0 | …
> Feat: Job prioritization

- app/models/sample/query.rb
- db/migrate/20250424155356_add_index_to_samples_name.rb
- db/structure.sql
Sample PUID filtering in Sample::Query was using case insensitive matching, this has been updated to now use exact matching (where the query values are upcased ahead of time). This means it is hitting our index on the puid column, vs no index when using case insensitive matching.
Notes: Locally this resulted in a 168.5x speedup for me running the same graphql query between `main` branch and this branch, using a test database dump. …
> Speedup: Sample PUID Filtering

- app/components/attachments/table_component.html.erb
- app/components/attachments/table_component.rb
- app/helpers/sorting_helper.rb
- test/system/groups/attachments_test.rb
- test/system/projects/attachments_test.rb
- Updated `TableComponent` to define metadata and file data columns for sorting/filtering. 
- Implemented `sort_column_name` method to map display column names to Ransack sort attributes, improving sorting functionality. 
- Modified `aria_sort` method in `SortingHelper` to include debug output for better traceability during sorting actions. 
- Adjusted tests in `attachments_test.rb` to use I18n translations for column headers, ensuring consistency with localization. 
Go to a project or group attachments page and upload a file.  Ensure that the `aria-sort` is …
> accessibility: Fixed attachments table sort aria

- app/controllers/concerns/sample_spreadsheet_import_actions.rb
- app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/controllers/groups/samples/spreadsheet_import_controller_test.rb
- test/controllers/projects/samples/spreadsheet_import_controller_test.rb
- test/fixtures/active_storage/blobs.yml
- test/fixtures/files/valid_group_sample_import.csv
- test/fixtures/files/valid_project_sample_import.csv
This PR changes batch sample import to utilize direct upload
1. Navigate to a group that you can import samples
2. Upload `test/fixtures/files/batch_sample_import/group/valid.csv`
3. Submit and verify import works as expected
4. Navigate to a project that you can import samples
5. Upload `test/fixtures/files/batch_sample_import/project/valid.csv`
6. Submit and verify import works as expected
> Batch Sample Import: Direct Upload

- app/components/workflow_executions/table_component.html.erb
- app/components/workflow_executions/table_component.rb
- test/system/groups/workflow_executions_test.rb
- test/system/projects/workflow_executions_test.rb
- Updated `table_component.html.erb` to use `sort_column_name` for better sorting logic in table headers. 
- Introduced `METADATA_FIELDS` in `table_component.rb` to handle special metadata fields for sorting. 
- Added `sort_column_name` method to determine the correct database column name for sorting based on the display column. 
- Modified tests in `workflow_executions_test.rb` to assert sorting functionality using internationalized text for better readability and maintainability. 
Go to a group or project with a workflow execution (or create one).  Ensure …
> accessibility: Fixed workflow executions table sort aria

- app/components/project_dashboard/information_component.html.erb
- app/components/project_dashboard/samples_component.html.erb
- app/components/project_dashboard_component.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Go to a project details page and test the layout at different zoom level, up to 400%
> Project details reflow

- .vscode/settings.json
- app/assets/tailwind/application.css
- app/components/advanced_search/condition.html.erb
- app/components/advanced_search/group.html.erb
- app/components/advanced_search/value.html.erb
- app/components/advanced_search_component.html.erb
- app/javascript/controllers/advanced_search_controller.js
- config/locales/en.yml
- config/locales/fr.yml
- test/components/advanced_search_component_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/samples_test.rb
Added reflow and fieldsets to the groups & conditions of advanced search.
STRY0017835
Open the advanced search of a sample page and test the layout at different zoom level up to 400%.
> Accessibility: Advanced search 

- app/assets/tailwind/application.css
- app/components/activities/groups/sample_activity_component.html.erb
- app/components/activities/projects/sample_activity_component.html.erb
- app/components/activities/projects/sample_clone_activity_component.html.erb
- app/components/activities/projects/sample_transfer_activity_component.html.erb
- app/components/activities/projects/workflow_execution_activity_component.html.erb
- app/components/layout/sidebar_component.html.erb
- app/components/pagination_component.html.erb
- app/components/viral/button_component.rb
- test/components/viral/button_component_test.rb
This PR addresses issues found by siteimprove browser extension where button targets where not of large enough size.  Update to the smallest size of 44px which fixes this issue.
> Update buttons on Projects dashboard to meet size requirement for siteimprove

- app/components/viral/dropdown_component.rb
- test/components/viral/system/dropdown_component_test.rb
Fixes issue that caused poor rendering of the language select (especially on hover)
Go to login page on main branch and hover over the language select, has an ugly green state to it.
Switch to this branch and try again, should look better
> Login page language button cleanup

- app/components/viral/pagy/limit_component.html.erb
- app/components/viral/pagy/pagination_component.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/viral/pagy_pagination_component_preview_test.rb
Fixes siteimprove issues with pagination target size and aria-label on dropdown page size button
Go to a project that has more than 20 samples
Ensure that sitepoint errors are gone.
> Updates accessibility of pagination component

- app/components/viral/dialog_component.html.erb
- app/components/viral/dialog_component.rb
- Removed "overflow-visible" class from the dialog component in dialog_component.html.erb to ensure proper styling and prevent overflow issues.
- Updated the initialization of system arguments in dialog_component.rb to maintain the intended dialog size without the overflow class.
> Fixes dropdown overflowing on dialog

- Dockerfile
- README.md
- scripts/clean_dev.sh
Updated Dockerfile to install icon library
> Fix: Dockerfile - Install icon library

- app/components/layout/sidebar/multi_level_menu_component.html.erb
- app/javascript/controllers/collapsible_controller.js
Fixes:
Updates the button trigger with `aria-expended="true"` when dropdown open.
When closed, the menu items container gets updated with the following:
- `hidden="hidden"` attribute (most important for preventing screen readers from reading area
- `aria-hidden="true"`
> Fix accessibility of the multi level menu component

- app/components/nextflow/samplesheet/header_component.html.erb
- app/components/nextflow/samplesheet_component.html.erb
- app/components/nextflow_component.html.erb
- app/javascript/controllers/nextflow/samplesheet_controller.js
- app/views/workflow_executions/file_selector/create.turbo_stream.erb
- app/views/workflow_executions/metadata/fields.turbo_stream.erb
- test/components/nextflow_samplesheet_component_test.rb
- test/system/workflow_executions/submissions_test.rb
This PR converts the nextflow samplesheet to use a table, allowing for more intuitive tabbing for keyboard users
Verify the samplesheet elements still behave as expected
> Nextflow Samplesheet: Convert to HTML Table

- app/components/namespace_statistic_component.html.erb
- app/components/namespace_statistic_component.rb
- app/components/namespace_tree/row/row_contents_component.html.erb
- app/components/project_dashboard/information_component.html.erb
- app/components/project_dashboard/samples_component.html.erb
- app/components/project_dashboard_component.html.erb
- app/views/groups/show.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/namespace_statistic_component_test.rb
- test/components/previews/namespace_statistic_component_preview.rb
Added a group information section that looks like the project information section.  The group information presented is:
1. Number of samples
2. Number of projects
3. Number of subgroups
This PR also update the look of these counts in the row_component of the namespace tree for consistency.
> Group Information Sidebar

- app/components/layout/sidebar/header_component.html.erb
- app/components/layout/sidebar/item_component.html.erb
- app/components/layout/sidebar/item_component.rb
- app/components/layout/sidebar/multi_level_menu_component.html.erb
- app/components/layout/sidebar/multi_level_menu_component.rb
- app/components/layout/sidebar/section_component.html.erb
- app/components/layout/sidebar_component.html.erb
- app/components/layout/sidebar_component.rb
- app/components/layout_component.html.erb
- app/components/viral/avatar_component.rb
- app/components/viral/pagy/pagination_component.html.erb
- app/helpers/icon_helper.rb
- app/javascript/controllers/collapsible_controller.js
- app/javascript/controllers/sidebar_item_controller.js
- app/views/groups/update.turbo_stream.erb
- app/views/layouts/groups.html.erb
- app/views/layouts/projects.html.erb
- app/views/projects/update.turbo_stream.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/components/layout/sidebar_component_test.rb
- test/components/layout_component_test.rb
- test/components/viral/avatar_component_test.rb
- test/components/viral/page_header_component_test.rb
Lightened the selected colour and added the primary colour back into the selected option
> Tweaking sidebar colours

- app/views/shared/project/_row.html.erb
This now matches the groups dashboard counts
> Update Project Dashboard Samples Counts

- .github/workflows/ruby.yml
- app/assets/tailwind/application.css
- app/components/layout_component.html.erb
- app/components/samples/table_component.rb
- app/javascript/controllers/editable_cell_controller.js
- app/javascript/controllers/nextflow/samplesheet_controller.js
- app/views/groups/show.html.erb
This PR started off with just updating the `nextflow/samplesheet_controller.js` to send compact form data (i.e. remove empty values from `samplesheet_params` to reduce payload when samplesheet is sparsely filled out), and then I added a few other bug fixes:
* fix layout and fixed-table-component so that a scrollbar is not rendered (this was accidentally added when breadcrumb bar was resized)
* fix `editable_cell_controller.js` to reconnect editable cells when page is morphed (e.g. a user has the samples table open with metadata displayed and in another window they add a sample to the project, this would previously only have the newly created or updated sample be editable and the page would have to be refreshed to edit the other …
> Compact samplesheet form data

- app/components/nextflow/samplesheet_component.html.erb
- app/javascript/controllers/form/json_submission_controller.js
- app/javascript/controllers/nextflow/samplesheet_controller.js
- test/system/workflow_executions/submissions_test.rb
This PR updates the metadata selection within the nextflow samplesheet to use json form submission so that we don't hit 4096 param limit. In addition the nextflow form submission submitSamplesheet has been updated to tie into `turbo:before-fetch-submit` so that it can submit as a json payload as well.
2. Create a new Project
3. Import the following samples into the Project 
[5000-import.xlsx](https://github.com/user-attachments/files/20524066/5000-import.xlsx)
4. Ensure that the following pipeline is setup in …
> Nextflow: JSON form submission

- app/components/nextflow/samplesheet_component.html.erb
- app/controllers/workflow_executions/metadata_controller.rb
- app/javascript/controllers/nextflow/samplesheet_controller.js
This PR refactors how the samplesheet table data is created (by `cloneNode` rather than regex'ing over `PLACEHOLDERS`) in response to PR comment https://github.com/phac-nml/irida-next/pull/1064#pullrequestreview-2838200550
1. Verify the samplesheet behaves the same as before, and submission still contains all the expected data
> Samplesheet: Refactor assigning template attributes

- app/components/viral/page_header_component.html.erb
- test/components/viral/page_header_component_test.rb
- Updated the structure of the page header component to improve responsiveness and accessibility.
- Replaced the main container with a semantic <section> element and added appropriate ARIA roles.
- Adjusted layout to stack elements on mobile and align them in a row on larger screens.
- Improved text handling with max-width and added screen reader-only text for titles and subtitles.
- Ensured proper use of TailwindCSS classes for styling consistency.
Play around with different page width on different pages and see how it adjusts …
> refactor: enhance page header component layout and accessibility

- app/components/layout/sidebar_component.html.erb
- app/components/layout_component.html.erb
- app/components/viral/dropdown_component.rb
- config/locales/en.yml
- config/locales/fr.yml
Addresses STRY0018202
- Added title attributes to buttons in the layout and sidebar components for improved accessibility.
- Updated localization files to include titles for navbar elements in both English and French, enhancing user experience.
- Enhanced the `system_arguments_for_icon` method in the `ViralDropdownComponent` to support custom button styles, improving flexibility in design.
- Ensured compliance with accessibility standards by updating ARIA attributes and improving semantic markup.
- Standardizes hover styles on buttons in sidebar
This checklist …
> feat(navbar): enhance accessibility and localization for dropdown components

- app/assets/tailwind/application.css
[STRY0018328](https://publichealthprod.service-now.com/now/nav/ui/classic/params/target/rm_story.do%3Fsys_id%3Dcb4e25c6474e6610f24c0c21516d43b4%26sysparm_view%3Dscrum%26sysparm_record_target%3Drm_story%26sysparm_record_row%3D44%26sysparm_record_rows%3D118%26sysparm_record_list%3Dassignment_group%253D9efb9efb47765a50f24c0c21516d4374%255Eshort_descriptionSTARTSWITHART-%255Epriority%253D2%255EORDERBYstate%26sysparm_view%3Dscrum)
Colour contrast issue with error states on forms.  Now meets AA colour standards
**Before**
**After** …
> Fix field error color contrast

- app/controllers/concerns/metadata.rb
- app/controllers/concerns/metadata_template_actions.rb
- app/models/namespace.rb
- app/views/data_exports/_new_linelist_export_dialog.html.erb
- test/components/previews/advanced_search_component_preview.rb
This PR updates the advanced search component to retrieve the namespace metadata_fields in sorted (alphabetically) order. Addresses [STRY0018762] (https://publichealthprod.service-now.com/rm_story.do?sys_id=bd4b79ca474f6250f24c0c21516d4397)
1. Create a couple of projects in a group, add samples to the projects, and add metadata to samples
2. View the samples page for the projects, and activate the `Advanced Search`
3. In the field dropdown, verify the metadata fields are sorted alphabetically
4. Now view the samples at the group level and activate the `Advanced …
> Advanced Search: Metadata fields sort

- app/components/viral/flash_component.html.erb
- app/components/viral/flash_component.rb
- app/javascript/controllers/viral/flash_controller.js
- config/locales/en.yml
- config/locales/fr.yml
- test/components/viral/flash_component_test.rb
- Updated FlashComponent to improve accessibility by refining ARIA attributes and screen reader text.
- Replaced icon-related screen reader text with message type descriptions for better clarity.
- Added entrance and exit animations to the flash messages for a smoother user experience.
- Updated tests to verify new accessibility features and animation styles.
> Enhance Flash Component Accessibility and Animation

- Gemfile.lock
- app/javascript/controllers/pathogen/datepicker/input_controller.js
This fixes the focus scroll logic, bug happened on Bot Accounts page within `New Bot Account` modal. When focusing the calendar after tabbing to the input it would not scroll into view correctly.
> A11y: Datepicker positioning followup

- config/routes.rb
- lib/irida/path_regex.rb
This PR enables the Rails default healthcheck endpoint at `/up`.
https://api.rubyonrails.org/classes/Rails/HealthController.html
> Feat: Rails healthcheck endpoint

- app/components/viral/form/prefixed/select2_component.html.erb
- app/components/viral/form/prefixed/select2_component.rb
- app/javascript/controllers/viral/select2_controller.js
- app/views/groups/_form_fields.html.erb
- app/views/projects/_project_namespace_fields.html.erb
This PR fixes the viral prefixed select2 reflow which caused a content loss on the create project and create subgroup pages. Addresses:
[STRY0018248](https://publichealthprod.service-now.com/rm_story.do?sys_id=7e4e597b47f12e50f24c0c21516d43dd)
**Create SubGroup**
**100%**
**250%**
**400%**
**Create Project**
**100%**
**250%**
**400%**
1. Set browser to 1280x1024
2. Visit the create project page
3. Zoom in slowly up to 400% and verify that there is no loss of content
4. Repeat for creating a subgroup …
> Fix: Viral Prefixed Select2 reflow

- config/locales/en.yml
- config/locales/fr.yml
This PR updates the `Reserved [NAMSPACE] names` link to have the same styling as the links in the application. Previously these links were the same color as the surrounding text
Addresses: 
[STRY0018448](https://publichealthprod.service-now.com/rm_story.do?sys_id=6b72d08947966250f24c0c21516d432c)
> Accessibility: Create group/project link styling 

- app/assets/tailwind/application.css
- app/components/viral/sortable_list/list_component.html.erb
- app/components/viral/sortable_list/list_component.rb
- app/components/viral/sortable_list/list_item_component.html.erb
- app/components/viral/sortable_list/list_item_component.rb
- app/components/viral/sortable_lists_component.html.erb
- app/components/viral/sortable_lists_component.rb
- app/javascript/controllers/metadata/file_import_controller.js
- app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
- app/views/data_exports/_new_linelist_export_dialog.html.erb
- app/views/data_exports/_new_sample_export_dialog.html.erb
- app/views/shared/metadata_templates/_edit_template_dialog.html.erb
- app/views/shared/metadata_templates/_new_template_dialog.html.erb
- app/views/shared/samples/metadata/file_imports/_dialog.html.erb
- app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- test/controllers/workflow_executions/submission_controller_test.rb
- test/fixtures/groups.yml
- test/fixtures/namespaces/project_namespaces.yml
- test/fixtures/samples.yml
- test/models/group_test.rb
- test/system/data_exports_test.rb
- test/system/groups/metadata_templates_test.rb
- test/system/groups/samples_test.rb
- test/system/projects/metadata_templates_test.rb
- test/system/projects/samples_test.rb
This PR overhauls the sortable lists component to add additional accessibility to the component.
A follow-up PR (once accessibility goals have been achieved) will include refactor this component to specify the Selected/Available list (rather than passing in IDs/naming etc.), utilizing `outlets` rather than `dispatch`, and fixing some import dialog behaviour that do not smoothly pass back unused headers as expected (still functions as expected).
Inspired by: https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-rearrangeable/#ex2_label
Changes include the following:
- Allow users to now select multiple options at once (denoted with a checkmark for selected state)
- Remove `Add All` and `Remove All` buttons and replace with simple `Add` and `Remove`
- Add `Up` and `Down` buttons …
> Accessibility: Sortable Lists Enhancements

- app/components/attachments/dialogs/new_attachment_component.html.erb
- app/javascript/controllers/attachment_upload_controller.js
- app/javascript/controllers/file_upload_controller.js
- app/views/projects/samples/attachments/_form.html.erb
- app/views/shared/samples/metadata/file_imports/_dialog.html.erb
- app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
- config/locales/en.yml
- config/locales/fr.yml
This PR updates the `attachment_upload_controller` to set aria-required to true on the file input and removed the required: true from the forms so that `Invalid Entry` does not get read out by the screenreader even when there are no current errors. Also, the `Upload` button is disabled if there are no uploadable files selected. Addresses:
[STRY0018346](https://publichealthprod.service-now.com/rm_story.do?sys_id=0430b54a474e6610f24c0c21516d43de)
1. Try uploading a variety of valid and invalid files (sequence files not compressed) and verify that the `Upload` …
> Accessibility: Upload files

- app/components/workflow_executions/table_component.html.erb
Fix aria-label for workflow execution checkbox to use presence method
> Fix aria-label for workflow execution checkbox to use presence method

- app/views/dashboard/groups/index.html.erb
- app/views/dashboard/projects/index.html.erb
- app/views/data_exports/show.html.erb
- app/views/groups/bots/index.html.erb
- app/views/groups/samples/index.html.erb
- app/views/groups/show.html.erb
- app/views/projects/automated_workflow_executions/index.html.erb
- app/views/projects/bots/index.html.erb
- app/views/projects/samples/metadata/_table.html.erb
- app/views/shared/metadata_templates/_header.html.erb
- embedded_gems/pathogen/app/components/pathogen/tabs_panel.html.erb
This PR is a followup to fix reflow of more action buttons and search bars
Verify the following pages' reflows:
1. Group and Project dashboards
2. Group show search projects search bar
3. Data export show header buttons
4. Group and Project bot - new bot button
5. Project automated workflow - new workflow button
6. Sample metadata - new and delete metadata buttons
7. Group and project metadata templates - new metadata template button
> Fix: Button/search bar reflow followup

- app/components/viral/sortable_list/list_component.html.erb
- app/components/viral/sortable_list/list_item_component.html.erb
- app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
The change involves commenting out the drag and drop event listeners and the related logic for updating aria attributes based on drag and drop events. This is a temporary measure, and the functionality may be restored in a future commit.
Ensure metadata template creation and editing still work.
> Temporarily disables drag and drop in sortable lists

- app/components/attachments/table_component.html.erb
- app/components/samples/table_component.html.erb
- app/components/workflow_executions/table_component.html.erb
- app/helpers/style_helper.rb
- app/views/projects/samples/metadata/_table.html.erb
Removed link from sample PUIDs in table.
Enhances table component to better handle column widths, especially for the PUID column.
Introduces a helper function to calculate the PUID column width based on the PUID length and checkbox presence, ensuring consistent spacing and alignment.
Updates the table component to use CSS variables for width calculations, improving responsiveness and maintainability.
Update UUID tables (Workflow Execution) to also have a fixed width on their id columns …
> Table PUIDs

- app/javascript/application.js
- app/views/layouts/lookbook.html.erb
- app/views/layouts/partials/_head.html.erb
- app/views/shared/_local_time.html.erb
- config/i18n-tasks.yml
- config/locales/local_time.fr.yml
- test/components/previews/viral_data_table_component_preview/default.html.erb
- test/components/previews/viral_data_table_component_preview/overflow_x.html.erb
- test/components/viral/system/data_table_component_test.rb
- test/system/projects/samples_test.rb
Previously, localization of the `local_time` gem was handled within `javascript/application.js`. This PR now migrates the translations to our `.yml` locale files, which is in line with how the application handles translations.
1. Navigate to a samples table, and use the top right language dropdown. Verify the language changes for datetime columns (such as `Last Updated`)
2. Change the language through Profiles > Preferences and re-visit the samples table and verify the above again.
> Localize local_time

- app/views/dashboard/groups/index.html.erb
- app/views/dashboard/projects/index.html.erb
- app/views/data_exports/index.html.erb
- app/views/groups/attachments/index.html.erb
- app/views/groups/group_links/_invited_groups.html.erb
- app/views/groups/members/_member_listing.html.erb
- app/views/groups/samples/index.html.erb
- app/views/groups/workflow_executions/index.html.erb
- app/views/projects/attachments/index.html.erb
- app/views/projects/group_links/_invited_groups.html.erb
- app/views/projects/members/_member_listing.html.erb
- app/views/projects/samples/attachments/_table.html.erb
- app/views/projects/samples/index.html.erb
- app/views/projects/workflow_executions/index.html.erb
- app/views/workflow_executions/index.html.erb
- test/system/workflow_executions/submissions_test.rb
This PR updates all the tables to only display actions/searching if there are records present (except for functions such as `Add`). The vertical spacing was fixed as well to be consistent across the tables (see the second and third last  screenshots)
1. Go through all the project/group pages which have tables, and confirm that actions/searching only display when records exist **(unless the action is to add a record)**
2. Verify that the spacing between toolbars and tables is consistent across the application
This checklist encourages us to confirm any changes …
> Tables: Hide actions/searching functionality if no records exist

- app/assets/tailwind/application.css
- app/javascript/controllers/projects/samples/metadata/create_controller.js
- app/views/groups/_edit_advanced_transfer_form.html.erb
- app/views/groups/_form_fields.html.erb
- app/views/groups/group_links/_form.html.erb
- app/views/groups/members/_form.html.erb
- app/views/projects/_project_namespace_fields.html.erb
- app/views/projects/_transfer_form.html.erb
- app/views/projects/group_links/_form.html.erb
- app/views/projects/members/_form.html.erb
- app/views/projects/samples/metadata/_form.html.erb
- app/views/samples/clones/_dialog.html.erb
- app/views/samples/transfers/_dialog.html.erb
- app/views/shared/personal_access_tokens/_form_fields.html.erb
- config/i18n-tasks.yml
- embedded_gems/pathogen/config/locales/en.yml
- embedded_gems/pathogen/config/locales/fr.yml
- embedded_gems/pathogen/lib/pathogen/form_builders/pathogen_form_builder.rb
- test/system/projects/samples/metadata_test.rb
- Adds a new form builder to handle label generation with consistent styling and required field indicators.
- Uses an HTML abbr element for the required indicator for improved semantics and accessibility.
- Also updates locale files to allow for customization of the required indicator text.
- Ensure that required fields have the `*` associated with them.
> Implements Pathogen form builder labels

- config/i18n-tasks.yml
- config/locales/action_policy.fr.yml
- config/locales/components.fr.yml
- config/locales/devise.fr.yml
- config/locales/fr.yml
- embedded_gems/pathogen/config/locales/fr.yml
- test/system/projects/samples_test.rb
Adds remaining missing french translations as of 09-26-2025
> French translations 092625

- app/assets/tailwind/application.css
- app/views/profiles/passwords/_form.html.erb
- app/views/shared/form/_required_field_legend.html.erb
- test/system/profile_test.rb
Adds the "required" attribute to the current password, password, and password confirmation fields to improve form validation.
Ensure `*` are added to all labels on the password reset page
> Adds required attribute to password fields
